### ISSUE TITLE
ONNX FATAL: [enforce fail at backend.cc:653] . Caffe2 only supports padding 2D Tensor, whereas padding is [0, 3, 3, 0, 0, 3, 3, 0, ]

### ISSUE THREAD

**Issue by laobadao** [onnx/onnx#1175]
onnx -caffe2

**Comment by houseroad** [comment]
According to https://github.com/pytorch/pytorch/blob/master/caffe2/onnx/backend.cc#L668, you are trying to pad the channel dimension, which is not supported PadImage. Please make sure the behavior is desired. Another possible cause is that you use NHWC instead of NCHW, however, onnx-caffe2 only covers NCHW case.

**Comment by laobadao** [comment]
@houseroad I see, thank you
