### ISSUE TITLE
Optimizer crashes on onnx model converted from Tensorflow graph

### ISSUE THREAD

**Issue by yehenrytian** [onnx/onnx#1385]
Hi, I am trying to invoke the ONNX optimizer following in the instructions in the following post:

[https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#optimizing-an-onnx-model](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#optimizing-an-onnx-model)

The ONNX model is converted from a `TensorFlow .pb file:
```
     onnx_model = tensorflow_graph_to_onnx_model(graph_def, outputs, opset=7,
                             ignore_unimplemented=True)

    all_passes = optimizer.get_available_passes()
    print("Available optimization passes:")
    for p in all_passes:
        print(p)
    print()
    # Apply the optimization on the original model
    passes = ['fuse_consecutive_transposes']

    optimized_onnx_model = optimizer.optimize(onnx_model, passes)
```

I am getting a crash in the optimizer:

```
 File "/home/xxx/PycharmProjects/virtualenv/local/lib/python3.5/site-packages/onnx/optimizer.py", line 52, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at

```

onnx version: 1.3.0

onnx-tf verison: 1.1.2

Thanks!

**Comment by houseroad** [comment]
Could you provide a minimum onnx to reproduce the problem?

**Comment by yehenrytian** [comment]
Like I said, the onnx model is imported from a TensorFlow frozen graph. A .pb file. For some reason stackoverflow does not let me upload the file here (even I compress it to a .zip file)

**Comment by keerthanss** [comment]
I faced this issue too. I found that running onnx.checker.check_model() helped, as it turned out my model itself had issues! After fixing them, the optimize worked just fine.

**Comment by fanghuaqi** [comment]
I met same issue when running onnx optimize.

**Comment by vinialves** [comment]
I met same issue when optimizing onnx model converted from keras using keras2onnx.

Maybe the issue is not in the optimizer, but in the conversion tools, like from keras to onnx using keras2onnx.

Steps:
1) create keras model Resnet50 and convert to onnx:

import keras2onnx
import onnx
from keras.optimizers import RMSprop
from keras.applications.resnet50 import ResNet50
weights = "imagenet"
model = ResNet50(weights=weights, input_shape=(224, 224, 3))
model.compile(optimizer=RMSprop(), loss='categorical_crossentropy', metrics=["accuracy", 'top_k_categorical_accuracy'])
model.save('resnet50.h5', overwrite=True)
# convert to onnx model
onnx_model = keras2onnx.convert_keras(model, model.name)
# Save the new ONNX model
onnx.save(onnx_model, 'resnet50.onnx')

2) Error running optimizer with the optimization 'fuse_bn_into_conv'
    optimized_model = optimizer.optimize(original_model, passes)
  File "/usr/local/lib/python3.5/dist-packages/onnx/optimizer.py", line 55, in optimize
    optimized_model_str = C.optimize(model_str, passes)
IndexError: _Map_base::at

3) I did what @keerthanss suggested and got issues on the model:
#Check model
onnx.checker.check_model(original_model)

onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'activation_1_Relu_0' of node: 
input: "activation_1_Relu_0" output: "bn_conv1_cond_Merge_0" name: "Transpose3" op_type: "Transpose" attribute { name: "perm" ints: 0 ints: 2 ints: 3 ints: 1 type: INTS } doc_string: "" domain: ""
 is not output of any previous nodes.

So, as @fanghuaqi found the issue on tf2onnx and I found on keras2onnx maybe it is an issue in onnxmltools.

**Comment by Zrufy** [comment]
i have the same problem.The error is **invalid unordered_map<K, T> key**

**Comment by dashesy** [comment]
Even if the underlying model is not correct, the error message should be better than `IndexError: _Map_base::at`!

**Comment by red0orange** [comment]
I also encountered the same problem in pytorch-onnx-caffe2. At last, I found that the reason is that the CPU is used when exporting the model, and CUDA is used by default when importing to caffe2, resulting in errors. As long as the code changed as follows, the problem was solved.
`prepared_backend = onnx_caffe2_backend.prepare(model,device='CPU')`

**Comment by flashtang927** [comment]
@red0orange 
Wonderful!!! 
Your are right!
You did a very fantastic exploration!!!

**Comment by jwfromm** [comment]
@red0orange , @flashtang927 , Can you elaborate a little more on the solution to the problem? I'm running into the same error when using pytorch-onnx-caffe2 on a machine without a GPU. It looks like device=CPU is the default everywhere. What needs to be explicitly changed?

**Comment by Redbeard101** [comment]
I am having the same issue, using a Mac without a gpu. I've set CPU both exporting and importing & preparing to no avail. 

Also my model checker doesn't seem to complain when I load the model.
model_onnx = onnx.load('./converted_models/model_simple.onnx')
onnx.checker.check_model(model_onnx)  #no errors

**Comment by nihui** [comment]
hi all
I finally resolved this issue

you have to add keep_initializers_as_inputs=True when exporting onnx

```
torch.onnx._export(model, x, "model.onnx", export_params=True, keep_initializers_as_inputs=True)
```

since this commit

https://github.com/pytorch/pytorch/commit/7583519b870e33ee3182f330c1bb8663559697b6

**Comment by fangyunfeng** [comment]
升级onnx到1.6就解决了

**Comment by jcwchen** [comment]
Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this issue, please raise an issue there. Thank you!

**Comment by datalee** [comment]
> Please note that ONNX optimizer has been moved to another repo https://github.com/onnx/optimizer since ONNX 1.9. If you still have this issue, please raise an issue there. Thank you!

me too
