### ISSUE TITLE
ONNX's shape inference function should at least have rank resolved

### ISSUE THREAD

**Issue by souptc** [onnx/onnx#1420]
In today's ONNX shape inference: 

> Shape inference is not guaranteed to be complete. In particular, some dynamic behaviors block the flow of shape inference, for example a Reshape to a dynamically-provide shape. Also, all operators are not required to have a shape inference implementation.

I understand that in some case it is difficult to resolve dynamic shapes. But as long as we have [symbolic shape](url) defined in ONNX, we should at least be able to resolve the rank of output tensors. Otherwise, the shape inference is totally useless if graph's input is symbolic.

**Comment by houseroad** [comment]
In our shape inference implementation, we try to infer the rank if it is possible. The results really depends on the model and how our implementation handles. If you find something does work as expect, feel free to create new issue.

**Comment by houseroad** [comment]
Yeah, without control flow ops, this should be true. But if we have control flow ops, you may get different ranks...

**Comment by gyenesvi** [comment]
@houseroad Can you give an example of how the _rank_ may become different because of control flow ops? (I understand this could be true for the shape, but not for the rank) Is the problem with branching or looping? In case of branching, wouldn't two branches return tensors of identical rank (otherwise, the subsequent part of the graph cannot work on with them)? In case of looping, how could a dynamic loop could change the rank of the output?
