### ISSUE TITLE
Why store backend test input/output data in the version control system?

### ISSUE THREAD

**Issue by kit1980** [onnx/onnx#1500]
Now if I add a backend test, I need to regenerate test data with `backend-test-tools generate-data` and include generated data protobufs in the commit (and be careful to not include data for already existing tests - they may be different after `backend-test-tools generate-data` because of operating system difference.)

Wouldn't it be easier/cleaner to just store the test sources in the version control system, and make continuous integration machines run `backend-test-tools generate-data` before testing?

**Comment by kali** [comment]
For what it's worth, as a third party backend implementor, I found it great to be able to use the onnx test suite out of the box, by just checking out the onnx repo. A compromise might be to mimick the "real" examples tests and having the data in s3, but please, don't make me setup onnx infrastructure to use its test suite.

**Comment by houseroad** [comment]
directly saving in repos has its cons and pros:

cons: 1) increase the size of the git history

pros: 1) easy to access, 2) easy to pair the schema change with the test cases,

Since the cases stored in the repo are small and the file numbers are still managable, it's ok to directly save them in the main github repository.

**Comment by houseroad** [comment]
Close the discussion, please reopen it if you think it's necessary to disentangle them from the main repo.
