### ISSUE TITLE
Object detection ops

### ISSUE THREAD

**Issue by cha-zhang** [onnx/onnx#1552]
ONNX seems to be missing quite some ops for object detection, most notably those in Detectron that's in PyTorch/Caffe2. What's the plan to add them? 

In the short term, we are looking for the following three: 
https://caffe2.ai/docs/operators-catalogue.html#generateproposals
https://caffe2.ai/docs/operators-catalogue.html#roialign 
https://caffe2.ai/docs/operators-catalogue.html#resizenearest 

Thanks!

**Comment by houseroad** [comment]
Still in progress... https://github.com/onnx/onnx/pull/1010
Probably will push it in this Nov.

**Comment by prasanthpul** [comment]
@houseroad is ResizeNearest part of #1010 too?

**Comment by faxu** [comment]
@houseroad Is ResizeNearest supported via some other change? I don't see it in #1010

**Comment by houseroad** [comment]
ResizeNearest is already supported by Upsample operator.

**Comment by faxu** [comment]
@houseroad Thanks. When will #1010 be completed for the other ops requested here?

**Comment by lilichu** [comment]
thanks!  hopefully it can come soon

**Comment by houseroad** [comment]
I will split #1010 into several small PRs, in each I will probably just introduce one operator. Will start from NMS  first.

**Comment by fuzzyBatman** [comment]
Hello guys. Any updates regarding this?

**Comment by prasanthpul** [comment]
Object detection models like YOLO , SSD, and FasterRCNN are now supported as of ONNX 1.5. Support for image segmentation models like MaskRCNN are planned for ONNX 1.6.

**Comment by fuzzyBatman** [comment]
So ONNX supports a Faster R-CNN model from Detectron? That is fantastic news. Thank you.

**Comment by prasanthpul** [comment]
@ebarsoum can you confirm whether the Faster RCNN model is based on the Detectron one or another source?

**Comment by fuzzyBatman** [comment]
The [operator schemas](https://github.com/onnx/onnx/blob/master/docs/Operators.md) list does not contain **ResizeNearest** and **GenerateProposals**, which I believe are required by Detectron's Faster R-CNN.

**Comment by SnowRipple** [comment]
Does Retinanet is also supported by ONNX

**Comment by dashesy** [comment]
Any progress on `roialign` ops?

**Comment by prasanthpul** [comment]
@dashesy RoiAlign was added few months back: https://github.com/onnx/onnx/blob/master/docs/Operators.md#RoiAlign

**Comment by prasanthpul** [comment]
@SnowRipple I personally have not tried it. Have you tried converting it? Did you run into any issue?

**Comment by SnowRipple** [comment]
@prasanthpul  I was trying to convert RetinaNet for a long time now, but it constantly failing. The error I cannot fix is this:

pydev debugger: starting (pid: 19948)
/home/snow_ripple/workspace/01_detection/mmdet/models/necks/fpn.py:106: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  target[:, :, :, :75] = inputs[1]
QStandardPaths: XDG_RUNTIME_DIR points to non-existing path '/run/user/1000/snap.eclipse', please create it with 0700 permissions.
Backend Qt5Agg is interactive backend. Turning interactive mode on.
/home/snow_ripple/workspace/01_detection/mmdet/core/anchor/anchor_generator.py:61: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  xx = x.repeat(len(y))
/home/snow_ripple/workspace/01_detection/mmdet/core/anchor/anchor_generator.py:62: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  yy = y.view(-1, 1).repeat(1, len(x)).view(-1)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:9: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cls_score_list = cls_scores.tolist()
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:10: TracerWarning: Converting a tensor to a Python list might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bbox_pred_list = bbox_preds.tolist()
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:13: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cls_score = torch.Tensor(cls_score_list[img_id]).detach().to(priors.device)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:14: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  bbox_pred = torch.Tensor(bbox_pred_list[img_id]).detach().to(priors.device)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:32: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nms_pre > 0 and cls_scores.shape[0] > nms_pre:
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:40: TracerWarning: new_tensor is a legacy constructor and is not supported in the JIT.
  means = deltas.new_tensor(means).repeat(1, deltas.size(1) // 4)
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:41: TracerWarning: new_tensor is a legacy constructor and is not supported in the JIT.
  stds = deltas.new_tensor(stds).repeat(1, deltas.size(1) // 4)
/home/snow_ripple/workspace/01_detection/mmdet/models/anchor_heads/ssd_export_helpers.py:46: TracerWarning: new_zeros is a legacy constructor and is not supported in the JIT.
  padding = cls_scores.new_zeros(cls_scores.shape[0], 1)
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:34: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  for i in range(1, num_classes):
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:36: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not cls_inds.any():
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if multi_bboxes.shape[1] == 4:
/home/snow_ripple/workspace/01_detection/mmdet/ops/nms/nms_wrapper.py:39: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if dets_th.shape[0] == 0:
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:50: TracerWarning: new_full is a legacy constructor and is not supported in the JIT.
  dtype=torch.long)
/home/snow_ripple/workspace/01_detection/mmdet/core/post_processing/bbox_nms.py:56: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] > max_num:
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:149: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if bboxes.shape[0] == 0:
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:154: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  bboxes = bboxes.cpu().numpy()
/home/snow_ripple/workspace/01_detection/mmdet/core/bbox/transforms.py:155: TracerWarning: Converting a tensor to a NumPy array might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  labels = labels.cpu().numpy()
/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/jit/__init__.py:301: TracerWarning: torch.from_numpy results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  out_tensor = torch.from_numpy(out[0])
Traceback (most recent call last):
  File "/home/snow_ripple/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2316, in <module>
    main()
  File "/home/snow_ripple/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 2309, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/snow_ripple/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1642, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/snow_ripple/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/pydevd.py", line 1649, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/snow_ripple/.eclipse/360744294_linux_gtk_x86_64/plugins/org.python.pydev.core_7.2.1.201904261721/pysrc/_pydev_imps/_pydev_execfile.py", line 25, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/snow_ripple/workspace/01_detection/tools/onnx_export.py", line 53, in <module>
    main()
  File "/home/snow_ripple/workspace/01_detection/tools/onnx_export.py", line 49, in main
    model.module.onnx_export(export_name=args.output, **data)
  File "/home/snow_ripple/workspace/01_detection/mmdet/models/detectors/base.py", line 98, in onnx_export
    torch.onnx.export(self, img, export_name, verbose=False)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/__init__.py", line 25, in export
    return utils.export(*args, **kwargs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 131, in export
    strip_doc_string=strip_doc_string)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 266, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/onnx/utils.py", line 225, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/jit/__init__.py", line 231, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 505, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/jit/__init__.py", line 306, in forward
    torch._C._tracer_exit(tuple(out_vars))
RuntimeError: output of traced region did not have observable data dependence with trace inputs; this probably indicates your program cannot be understood by the tracer.

I am happy to share my model with you @prasanthpul so you can recreate it

**Comment by pkhigh** [comment]
Hi, 
🐛 Bug
UserWarning: This version of onnx-caffe2 targets ONNX operator set version 9, but the model we are trying to import uses version 10. We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.
warnings.warn("This version of onnx-caffe2 targets ONNX operator set version {}, but the model we are trying to import uses version {}. We will try to import it anyway, but if the model uses operators which had BC-breaking changes in the intervening versions, import will fail.".format(cls._known_opset_version, imp.version))

ONNX FATAL: Don't know how to translate op Resize
ONNX FATAL: Don't know how to translate op NonMaxSuppression
ONNX FATAL: Don't know how to translate op RoiAlign
RuntimeError: ONNX conversion failed

Caffe2 is not able to support most of the operations of object detection.

To Reproduce
Steps to reproduce the behavior:

import onnx
import caffe2.python.onnx.backend
import os
import glob
import numpy as np
from onnx import numpy_helper

#model paths
model = onnx.load('mask_rcnn_R_50_FPN_1x.onnx')
test_data_dir = 'test_data_set_0'
#Prepare the backend
rep = caffe2.python.onnx.backend.prepare(model)

Expected behavior
model should have been loaded without any error

Environment
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==0.3.1
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.1
[conda] blas 1.0 mkl
[conda] mkl 2019.4 243
[conda] mkl_fft 1.0.12 py36ha843d7b_0
[conda] mkl_random 1.0.2 py36hd81dba3_0
[conda] pytorch 1.2.0 py3.6_cuda10.0.130_cudnn7.6.2_0 pytorch
[conda] torchvision 0.4.0 py36_cu100 pytorch

additional information
I build onnx from source.
current version is : 1.5.0

**Comment by pkhigh** [comment]
can someone help me with the inferencing the ONNX mask rcnn model from ONNX model ZOO with caffe2 as backend?

**Comment by prasanthpul** [comment]
@pkhigh the maskrcnn model requires operators that are only available in the latest ONNX opset. Caffe2 does not support these yet as shown in the error message. For any questions with Caffe2, please file an issue in the Caffe2 github.

Consider using [ONNX Runtime](https://github.com/microsoft/onnxruntime) which already supports these operators and has been tested with the mask rcnn model.

**Comment by prasanthpul** [comment]
@SnowRipple do you mind opening a separate issue for RetinaNet?
This issue has gotten old and long

**Comment by bhack** [comment]
About Obeject detection ops what Is missing about emerging ahcor-free models?
