### ISSUE TITLE
[feature/cmake] add soname to the resulting libonnxifi.so

### ISSUE THREAD

**Issue by cdluminate** [onnx/onnx#1679]
A typical shared object has the SONAME and SOVERSION attributes. The required change to cmakelist.txt is trivial.

**Comment by houseroad** [comment]
@zrphercule do you mind to take a look? :-)

**Comment by zrphercule** [comment]
@cdluminate Thanks for your issue! Yeah we are planning to add SONAME for libonnxifi.so (and maybe also libonnxifi_dummy.so) soon, but since framework is expecting the name of the backend to be "libonnxifi.so" but not "libonnxifi.so.1.0", and we are maintainning backward compatibility our selves, we are not going to add SOVERSION. Sounds good? :)

**Comment by cdluminate** [comment]
@zrphercule Understood. Indeed the soname "libonnxifi.so" is more convenient for binary distributions. Although I still have to patch cmake at downstream (Debian/Ubuntu) and keep track of API/ABI changes, but I'm very glad to know that you are maintaining the ABI compatibility. So sounds good to me.
