### ISSUE TITLE
Unsqueeze op problem

### ISSUE THREAD

**Issue by LorenzoGorza** [onnx/onnx#1843]
Hi,

I've a problem with loading and eval a model on application for Microsoft HoloLens. 
When I load the model and eval it through the application that i've build the console give me an exception with op Unsqueeze. 
`no suitable kernel definition found for op Unsqueeze`. 

I'm developing on HoloLens

OS build: 10.0.17763.316

I've tested with ONNX models version: 

ai.onnx v7
ai.onnx v8
ai.onnx v9

**Comment by faxu** [comment]
@LorenzoGorza: is this using ONNX Runtime? Are you able to share the model or provide info on the data type for the input/output for Unsqueeze?

**Comment by LorenzoGorza** [comment]
Hi, 

I load the model through Windos Machine Learning API, c# side, in order to develop a UWP app. 

[core api ](https://docs.microsoft.com/it-it/uwp/api/windows.ai.machinelearning.learningmodel)

Here two screenshot from the netron visualizer: 

![unsqueeze_1](https://user-images.githubusercontent.com/17638261/54034900-59545e00-41b8-11e9-8369-c0df6d39b25b.PNG)
![unsqueeze_2](https://user-images.githubusercontent.com/17638261/54034905-5c4f4e80-41b8-11e9-84db-b244fdbe8c96.PNG)

Thanks for help!

**Comment by prasanthpul** [comment]
What tool or process did you use to create your ONNX model?

Since this seems specific to Windows ML and not ONNX, please use the resources mentioned at https://docs.microsoft.com/en-us/windows/ai/faq to get Win ML experts looking at your issue:

- To ask or answer technical questions about Windows ML, please use the windows-machine-learning tag on Stack Overflow (https://stackoverflow.com/questions/tagged/windows-machine-learning).
- To report a bug, please file an issue on our GitHub (https://github.com/Microsoft/Windows-Machine-Learning/issues).
- To request a feature, please head over to Windows Developer Feedback. (https://wpdev.uservoice.com/)
