### ISSUE TITLE
Why ONNX do not support data processing operator like caffe2's ImageInput

### ISSUE THREAD

**Issue by hexiaoting** [onnx/onnx#2173]
When I convert pytorch model to onnx, then to caffe2,  the converted model's accuracy is decreased 15%-20%.
The first reason I found is the data preprocessing is different in caffe2 and pytorch. 
But when I convert model, I find ONNX donot have any data processing operator like resize, crop...

**Comment by ebarsoum** [comment]
ONNX have resize: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize. Regarding data pipeline this is something we are looking at.

**Comment by prasanthpul** [comment]
If you are interested to help define the data processing/featuring, please join the conversation at https://gitter.im/onnx/pipelines

**Comment by snnn** [comment]
It's not easy to solve. 

As you already now, data preprocessing is super important. If it wasn't done correctly, you'll lose accuracy. However, in most of the ONNX image models, it's impractical to put preprocessing logics there. Because different image has different size, you can't easily put them into a single tensor. Maybe we could separate them into two tensors, one for data, another for shapes of each of the image. 


So far we don't have a perfect solution for this problem yet.
