### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by doug-aero** [onnx/onnx#2175]
Are there plans to expand the model metadata properties to encompass details relating to training procedures and computational requirements?

**Comment by prasanthpul** [comment]
ONNX provides several fields for metadata (https://github.com/onnx/onnx/blob/master/docs/IR.md#models) including fields like 'metadata_props' on the ModelProto which are key/value pairs that can be used to capture a variety of optional metadata. 

I don't expect ONNX to add much more required metadata, However we can always suggest a list of standard keys/values for the optional metadata, that would be fine to document as well. Whether they are used will be up to model authors. Some may not use it because of model size sensitivities. Others may use them to comply with their organizational requirements.

Do you have specific properties in mind?
