### ISSUE TITLE
The rank for "depth" input of OneHot operator is unclear

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx#2210]
In the doc(https://github.com/onnx/onnx/blob/master/docs/Operators.md#onehot), the "depth" input for OneHot operator is declare as a scalar, but in the unit tests the value for "depth" is a 1D tensor. And in the def.cc(https://github.com/onnx/onnx/blob/master/onnx/defs/tensor/defs.cc), I find code that verify the "depth" input need to be a single-element vector. 
May someone please clarify what is the rank for depth, if it is a scalar, the rank is 0. But if it is a 1D tensor with one element then it is rank 1.

**Comment by askhade** [comment]
The spec says depth is a scalar so it should be a scalar. 
You are right the tests and current shape inference is misleading. I will update both to reflect the spec. 

However since right now shape inference allows 1D tensors of length 1 ... disallowing this without op version change will potentially break any existing models... In light of this I will keep the current check too.
