### ISSUE TITLE
Spatial transformer operator

### ISSUE THREAD

**Issue by greatkoara** [onnx/onnx#2383]
It could be really hard to perform geometric deformations on image such as object stretch or horizontal flip with convolutional layers, especially using relatively small models.

There is a [paper](https://arxiv.org/abs/1506.02025) from DeepMind which introduced an approach to perform such operations. 

PyTorch supports layer called `grid_sample` for that. It would be great to have an ability to convert models with this layer in ONNX for further usage.

[Reference](https://github.com/pytorch/pytorch/issues/27212) to my issue in PyTorch repository to add support for conversion of `grid_sample` layer in ONNX.

**Comment by xgirones** [comment]
Is there any update on this request? I also need the `grid_sample` operator for my project.

**Comment by spillerrec** [comment]
I ran into this when trying to convert the model from this project:
https://github.com/pkhungurn/talking-head-anime-demo

which uses the idea of 'appearance flow' from this paper:
https://arxiv.org/abs/1605.03557
https://github.com/tinghuiz/appearance-flow

The paper presents a CNN predicting a map of 2D vectors to transform an input image in order to do:
- 3D object rotation
- Perspective transformation
Visual examples in the second github link.

**Comment by likedan** [comment]
Any plan on adding it?

**Comment by JiayuanSternLi** [comment]
Any plan on adding it?

**Comment by PkuRainBow** [comment]
+

**Comment by yingsiq** [comment]
+1 please add ONNX support for grid_sampler operator

**Comment by RunningLeon** [comment]
+1

**Comment by lingkefeng** [comment]
+1

**Comment by OrkhanHI** [comment]
any updates???

**Comment by gxd1994** [comment]
+1

**Comment by pfeatherstone** [comment]
+1

**Comment by lihaoxiang1989** [comment]
any updates?

**Comment by xmk2222** [comment]
+1

**Comment by m-dawoud** [comment]
+1

**Comment by oqpti** [comment]
+1

**Comment by jayer95** [comment]
+1

**Comment by ShiyangZhang** [comment]
+1

**Comment by askhade** [comment]
https://github.com/onnx/onnx/pull/3557
