### ISSUE TITLE
Please require op version adapter in future breaking PRs

### ISSUE THREAD

**Issue by matteosal** [onnx/onnx#2414]
The version converter is currently missing several adapters: https://github.com/onnx/onnx/blob/master/onnx/version_converter.py#L64

Add this lack of adapters to the fast pace at which new opset versions are released, and to the strict rules that demand bumping an operator's version, and you obtain that external implementations are forced to support several opset versions explicitly in order to have a truly solid ONNX import/export functionality.

The current situation with Conv is particularly interesting: the opset version was switched to 11 in [this](https://github.com/onnx/onnx/pull/2291) PR for a change of documentation, but no adapter was added. This means that frameworks supporting opset 11 only will formally have to reject any old convolution operator, but importing them ignoring the version bump will actually work, because the spec didn't actually change.

Supporting multiple opset versions is additional burden placed on external implementations that can limit the potential of ONNX to allow seamless switchting between frameworks. On the other hand, if the version converter had complete coverage, external frameworks would only need to support the latest opset when it's released, and switching between frameworks will be guaranteed to work.

I am a developer of Mathematica's neural network framework at Wolfram Research, and we're currently working on our ONNX importer. We are very interested in having the adapter expanded, and are considering adding missing adapters for this reason.
Covering the 90+ adapters which are currently missing is a big endeavor which would take a long time, but at least the number could be kept from growing by requiring that every PR which bumps the op version also adds the related adapter.

Is this a reasonable request? Thanks!

**Comment by prasanthpul** [comment]
There have been discussions about requiring a converter to be added when ops are updated. @onnx/sig-operators to comment. @matteosal suggest you join the next operators SIG meeting as well

**Comment by rkpandya** [comment]
I was trying to convert from opset 11 to 9, is that currently possible? I get the error :

**Comment by matteosal** [comment]
@rkpandya the adapter for that conversion is not implemented (although the internal spec is identical in both versions). 
I have added several adapters in [this PR](https://github.com/onnx/onnx/pull/2664/files) including that one, so your conversion should work there (but it might fail due to other missing adapters)

**Comment by rkpandya** [comment]
Thanks! The main reason I had to use opset 11 was the aten operators, specifically bilinear interpolation.

**Comment by rkpandya** [comment]
Anything else I can try here to make this work?

**Comment by askhade** [comment]
@matteosal : 
IMO you have a valid point in making this request. I suggest you attend Operator SIG meetings to bring this to attention. They are announced in the operator sig channel on gitter. In the last meeting I also had a similar request to require version converter adapter for the op along with op version update PR. The reason why adding adapter is not yet mandated today is mostly because testing for these adapters needs to be simplified and without that this could be an added burden on the op submitter. I am planning to explore how best we can simplify testing.

Also, I am trying to understand whether just having a converter for level up is sufficient or level down converters are equally important. For the use cases that I have come across only level up converters are required.

Thanks for your PR for version converter updates! I am looking at it now :)

**Comment by matteosal** [comment]
Thank you @askhade. I will keep an eye at the gitter channel for the next meeting. About testing: in the PR, I have also proposed am alternative testing method which (sometimes) doesn't require additional effort after having introduced a new adapter. Do you think it can make life easier for developers?

**Comment by matteosal** [comment]
Adapters are now required when operator are changed via automatic_upgarde_test.py. Closing
