### ISSUE TITLE
ConvInteger vs QLinearConv

### ISSUE THREAD

**Issue by dashesy** [onnx/onnx#2424]
What is the difference between [ConvInteger](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger) and [QLinearConv](https://github.com/onnx/onnx/blob/master/docs/Operators.md#QLinearConv)?

> ConvInteger
The integer convolution operator consumes an input tensor, its zero-point, a filter, and its zero-point, and computes the output. The production MUST never overflow. The accumulation may overflow if and only if in 32 bits.

> QLinearConv
The convolution operator consumes a quantized input tensor, its scale and zero point, a quantized filter, its scale and zero point, and output's scale and zero point, and computes the quantized output. Each scale and zero-point pair must have same shape. It means they must be either scalars (per tensor) or 1-D tensors (per output channel). Each input or output and its related zero point must have same type.

Only in lack of scale? why couldn't the same ops be re-used?

**Comment by askhade** [comment]
ConvInteger does 8*8=>32 .i.e it takes 2 8 bit inputs and outputs the 32 bit accumulated value for this Where as QLinearConv does 8*8->8 Here as you can tell qlinearconv takes 2 8 bit inputs and outputs an 8 bit output

There are different scenarios where these 2 ops can be useful - 
For example 
In models where few ops in between need to be quantized ConvInteger is a good candidate - you can easily get the dequatized output in fp32 from int32 accumulated output

In models where you have back to back quantized ops like CNN where you have back to back Conv ops QlinearConv is better because you can eliminate dequantizing to fp32 and then back to 8 bit

Another big difference is - QLinearConv needs output scale and zero points which can only be obtained by some kind of calibration or training aware quantization method... whereas with ConvInteger you can use dynamic quantization without any calibration or training

**Comment by dashesy** [comment]
Thanks for the explanation, `ConvInteger` is like a special (more limited) version of `QLinearConv` that would not quantize the output, but still the output is a wider integer.
Does that mean `QLinearConv` will not use a wider integer when internally accumulating the filter? or can assume `ConvInteger` + `QuantizeLinear`  == `QLinearConv`?

**Comment by askhade** [comment]
Yes you can assume QLinearConv = ConInteger + QuantizeLinear
Ideally the backends should try and optimize this step as much as possible. For example, getting the whole output in int32 and then quantizing it down will be the most naive way of implementing QLinearConv. I would imagine the backends to optimize this. For example accumulate the result of row * col into int32 and then quantize this down before going to the next item. This way you never have the result of entire matmul operation in memory. (This is just an example)

**Comment by dashesy** [comment]
Thanks that answered my question.
