### ISSUE TITLE
some ONNX models cannot be recognized by AI inference tools

### ISSUE THREAD

**Issue by hi-bigcat** [onnx/onnx#2438]
Hi,
Our models are trained by PaddlePaddle, then the models are transformed to ONNX models to do inference by Paddle2ONNX. But we found some models cannot be recognized by TensorRT and another inference tool(most of the other models can be recognized), but the models can be loaded by ONNX runtime.

We are wondering whether the ONNX models format will have influence, for example the file header and so on.

Please help to check, thanks

![image](https://user-images.githubusercontent.com/46183033/68371442-afc7d100-0179-11ea-9356-67c53760cd78.png)

**Comment by prasanthpul** [comment]
It sounds like ONNX Runtime is able to run your model successfully. If so, then the model is fine. 
ONNX Runtime supports all versions of ONNX since 1.2. Other engines may not support older versions of ONNX.

Please note that ONNX Runtime has optimized GPU support and also can use TensorRT as an additional accelerator. So that may be a good way for you to run all your models and get acceleration.

If you believe there is a bug in TensorRT, please file the issue with the TensorRT forums so the right experts can take a look

**Comment by hi-bigcat** [comment]
Hi，
The issue has been solved, root cause is that proto buffer versions between different tools are not matched 
Thanks for your quick reply
