### ISSUE TITLE
LSTM hidden_size optional or required?

### ISSUE THREAD

**Issue by brothergomez** [onnx/onnx#2443]
Hi,
In the LSTM operator spec [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM) the attribute `hidden_size` is implied to be required (it has no default and isn't specified as optional). Furthermore, in the shape inference [here](https://github.com/onnx/onnx/blob/b29e78a4efb8e5d8995f576bbf19a846807829b6/onnx/defs/rnn/defs.cc) for RNNs, the output shapes are inferred by the `hidden_size` and not vice versa. Also, all examples seem to specify the `hidden_size` explicitly.

However in the same `defs.cc` `hidden_size` is listed as OPTIONAL. Is this intentional? Surely not specifying the `hidden_size` will always result in an error? 

Thanks,
Matt

**Comment by skottmckay** [comment]
The documentation generation logic seems to be inconsistent and adds '(optional)' for optional input/outputs (implying required otherwise), and does the opposite for attributes and adds '(required)' (implying optional otherwise). 

I believe the hidden size could be inferred at runtime from the input weights as they are required inputs. It also wouldn't be valid to set a default value for hidden_size if it's not specified.

Shape inferencing does its best to populate whatever values it can. If hidden_size is not explicitly specified the value for that dimension in the output stays unknown as the TensorShapeProto::Dimension for hidden_size will have neither dim_param or dim_value set.
