### ISSUE TITLE
Does ONNX support torch.nn.unfold(AKA Im2col)?

### ISSUE THREAD

**Issue by Godricly** [onnx/onnx#2445]
Is the unfold operation defined in ONNX? I checked the operator schemas but didn't find it.

**Comment by askhade** [comment]
A direct 1:1 mapping is not available. @spandantiwari how does pytorch converter handle this ?

**Comment by spandantiwari** [comment]
@Godricly @askhade Not every operator in PyTroch has an exact equivalent in ONNX. Several PyTorch ops are can be supported through a combination of ONNX ops. 

@Godricly - I see that you already have an open issue in PyTorch (https://github.com/pytorch/pytorch/issues/29706) and I agree that PyTorch repo is the place where this should be tracked, since it is a PyTorch support question, not ONNX. 

As mentioned in the other issue, `torch.nn.unfold` has partial support already. If there are models that require full support (im2col), let us know and we will prioritize this higher. 

I think we can close this as a duplicate issue and track the issue in PyTorch.

**Comment by askhade** [comment]
Tracked under under pytorch repo : https://github.com/pytorch/pytorch/issues/29706

**Comment by fdwr** [comment]
Curiously [Col2Im-18](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Col2Im) exists in ONNX now, but not its counterpart Im2Col 🤔.
