### ISSUE TITLE
ValidationError from check_model

### ISSUE THREAD

**Issue by aviaisr** [onnx/onnx#2459]
I exported a PyTorch model to onnx and the file was created successfully. 
When I call         
onnx.checker.check_model(model_onnx)

I get this validation error:

onnx.checker.check_model(model_onnx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\onnx\checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 1 not in range [min=2, max=3].

==> Context: Bad node spec: input: "707" output: "714" op_type: "Pad" attribute { name: "mode" s: "constant" type: STRING } attribute { name: "pads" ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 ints: 0 type: INTS } attribute { name: "value" f: 0 type: FLOAT }

I'm working with onnx version 1.6.0

**Comment by skottmckay** [comment]
If the model exported by pytorch is incorrect I'd suggest posting the issue on https://github.com/pytorch/pytorch/issues

**Comment by aviaisr** [comment]
Isn't is the same constant padding issue you've lately fixed?

https://github.com/onnx/onnx/issues/2423#issue-514020094

**Comment by skottmckay** [comment]
It's the same issue with the model, however the cause of the issue would be on the pytorch side if you've exported a model from pytorch and it has been exported with opset 11 but 'pads' are an attribute instead of an input. Essentially the pytorch export has created an invalid model, and the ONNX checker is failing due to that. I don't know whether that's due to incorrect usage of pytorch (not sure if you explicitly add 'pads' as an attribute or an input or whether pytorch chooses) or that the pytorch exporter is doing the wrong thing. 

In #2423 the example ONNX code was creating the invalid model.

**Comment by aviaisr** [comment]
Thank you very much for the detailed explanation!
