### ISSUE TITLE
Resize reference implementation for downsample + align corners seems wrong

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#2462]
When downsampling an input with mode set to align corners the output of the reference implementation provided with the resize tests in resize.py seems to be wrong.

For example:

node = onnx.helper.make_node(
    'Resize',
    inputs=['X', 'roi', 'scales'],
    outputs=['Y'],
    mode='linear',
    coordinate_transformation_mode='align_corners'
)

data = np.array([[[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
]]], dtype=np.float32)

scales = np.array([1.0, 1.0, 0.6, 0.6], dtype=np.float32)

Test output : 
[[[[1.       3.142857]]]]

 Actual expected output:
[[[[1.       4.0]]]]

**Comment by askhade** [comment]
@daquexian : Can you please take a look at this.

**Comment by daquexian** [comment]
@askhade I'll take a look at it

**Comment by daquexian** [comment]
@askhade It is intended behavior. In https://github.com/onnx/onnx/pull/2057#issue-282303240, I noted that 

> Some frameworks set output_dimension to round(input_dimension * scale) instead of floor(input_dimension * scale), some frameworks re-assign the scale to output_dimension / input_dimension. I think it is not good to add two extra attributes in resize op for these cases. This op has many attributes already, and the converters in frameworks have the ability and responsibility to make the scale compatible with the behavior of this op.

So the training framework (like PyTorch) -> ONNX converter should change the value of `scale` to `round(input_dimension * scale) / input_dimension` or `floor(input_dimension * scale) / input_dimension` based on the behavior of the training framework.

For example, if you want to get `[[[[1. 4.0]]]]`, the scale factor should be `[1.0, 1.0, 0.5, 0.5]`

**Comment by kraiskil** [comment]
I bumped into this problem too, and to me it looks like the backend test `resize_downsample_scales_linear_align_corners` should indeed give `[[[[1. 4.0]]]]`. I only want to look at the given backend test, and how to compute it, completely ignoring what the intention of the creator of the test was.

According to the Operator specification in `align_corners`, the  coordinates are calculated as `x_original = x_resized * (length_original - 1) / (length_resized - 1)`.
Since the lengths are the sizes of the input and output tensors, they are already rounded to integers.

In the innermost dimension `x_original = x_resized * (4 - 1) / (2 - 1) = x_resized * 3`.

In the second innermost dimension `x_original = x_resized * (2 - 1) / (1 - 1)`, which leaves a `0/0`, but I guess it is intended to be taken as a 0 instead of undefined? :)

So the original coordinates of the output  value `4.0` (i.e. coordinates `(0,0,0,1)`) are from the original coordinates `(0, 0, 0, 3.0)`. With an exact integer original coordinate, the bilinear interpolation reduces to picking the exact pixel value.

If `[[[[1. 3.142857]]]]` really is correct, how is that value calculated? Am I reading something wrong in the ONNX specification?

I tried running this test in onnx-runtime, and there too I got the result `[[[[1., 4.]]]]` (but I am new to onnx-runtime, and the test was created by the sclblonnx wrapper, so could be I missed something there).
