### ISSUE TITLE
[feature request] Triangular operations

### ISSUE THREAD

**Issue by perone** [onnx/onnx#2554]
It would be very nice to have triangular ops such as `tril` ([pytorch reference](https://pytorch.org/docs/stable/torch.html#torch.tril)) to get the lower triangular matrix, or `triu` ([pytorch reference](https://pytorch.org/docs/stable/torch.html#torch.triu)) to get the upper triangular matrix. These are very common operations when dealing with Cholesky decompositons.

**Comment by vladislavkoz** [comment]
Any updates? It is extremely important to me.

**Comment by TMVector** [comment]
@perone @vladislavkoz if the matrix is a fixed size, you could work around this with [ScatterND](https://github.com/onnx/onnx/blob/master/docs/Operators.md#scatternd). If you want to export from PyTorch I would recommend looking at related issues on that repo, such as https://github.com/pytorch/pytorch/issues/32968.

Otherwise you can create a PR to add a new operator. If so, please read https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md and refer to https://github.com/onnx/onnx/pull/2575 as a good example. We also recommend (require?) you implement the operator in a backend too, such as ONNX Runtime, to iron out any unforeseen issues. If you'd like help you can try the [gitter](https://gitter.im/onnx/operators) :)
