### ISSUE TITLE
authority concerns on trade issues about US EAR

### ISSUE THREAD

**Issue by ilikelucifer** [onnx/onnx#2561]
We are concerned about the authority of ONNX as recently arised trade issues between US and the rest of the world (especially China). We are looking forward to get your official answers for the questions below:
1. Is the ONNX project subject to U.S. Export Administration Regulations (EAR) and classified under ECCN 0D521? Or such AI software is subject to EAR, but not classified under ECCN 0D521? 
2.  Is U..S. Bureau of Industry and Security license required for exporting this project to China？

**Comment by ibrahimhaddad** [comment]
Hi there,  I am Ibrahim Haddad, Executive Director of LF AI Foundation. We host the ONNX project since Nov 2019. I'd like to address your questions:
- ONNX software, specs and discussions are all publicly available and open source, therefore not subject to the encryption requirements of the US Export Administration Regulations (EAR). ONNX does not use or implement publicly available encryption technology; and in any event a notification for ONNX have been sent to the Bureau of Industry and Security (BIS).
- Additionally, ONNX does not implement ECCN 0D521 No. 1, geospatial imagery “software” “specially designed” for training a Deep Convolutional Neural Network to automate the analysis of geospatial imagery and point clouds, which may be what you were referring to.
- Copies of the EAR notifications sent on behalf of LF projects can be found at: https://www.linuxfoundation.org/export/.
Best, 
Ibrahim
