### ISSUE TITLE
What is the definition of a valid ONNX model

### ISSUE THREAD

**Issue by liukuanlk** [onnx/onnx#2594]
May I ask what is the definition of a valid ONNX model? 

I tried to look for the doc about definition of a valid ONNX model but I did not find it. So I looked into the source code, [https://github.com/onnx/onnx/blob/master/onnx/checker.cc](https://github.com/onnx/onnx/blob/master/onnx/checker.cc). 

In [check_model function](https://github.com/onnx/onnx/blob/f12ec7991867a138c6ab7ed6fe81f19b18381b07/onnx/checker.cc#L736), it checks the IR version and duplicated keys in metadata. But it seems 
1. it does not check if there is size mismatch between layers(tensors)
2. it does not check if the tensor is empty (it contains fields but inside fields can be empty )

So my question here is,  could you give me a clear definition of a valid ONNX model? It would be very helpful for me to design a ONNX model. Thank you very much in advance!

**Comment by linkerzhang** [comment]
ONNX defines two things, 1) model format (*.proto files); 2) operator sets.

A valid ONNX model means that it follows the model format and all operators referred by nodes in the model follow the operators defined. The current ONNX checker tool tries to check the format and also op signature (type/shape) matching but does not check all rules. Some may be because it can't be checked statically. For example, the #1 point in your message, size mismatch can't be checked when the model is using dynamic shape (inputs' shape may be unknown) until model running time. For your #2 point, it can only be checked in model running time, which is NOT what ONNX can do, but an ONNX compatible framework or runtime can do.

http://github.com/microsoft/onnxruntime is one ONNX compatible runtime for loading/running onnx models for your reference..
