### ISSUE TITLE
module 'onnx' has no attribute 'optimizer'

### ISSUE THREAD

**Issue by MrGrayCode** [onnx/onnx#2599]
Getting the following error when using onnx optimizer
```
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-4-8cb35c759686> in <module>()
----> 1 onnx.optimizer.get_available_passes()

AttributeError: module 'onnx' has no attribute 'optimizer'
```

Got this error on both pip and source installations of onnx.

**Comment by linkerzhang** [comment]
unfortunately, the onnx optimizer in this repo is not well maintained.

you may run your model with https://github.com/microsoft/onnxruntime, which applies many optimization to an onnx model.

**Comment by gmt710** [comment]
Do you have demo for us？

**Comment by gmt710** [comment]
I’ve tried serveral versions, but all is disavailable.

**Comment by Greg7000** [comment]
You could try 'pip install onnxoptimizer' (https://github.com/onnx/optimizer) and replace all your onnx.optimizer. with onnxoptimizer. 

However, most likely, you will get an error later on due to the fact that you don't use the right version of the onnx library for your source (I am in this situation...). 

If your source want to use onnx.optimizer than the best way to deal with this would be to find the right version of onnx expected by your source
