### ISSUE TITLE
torch.nn.pixelshuffle does not support dynamic_axes when using onnxruntime.InferenceSession.run?

### ISSUE THREAD

**Issue by reddandelion217** [onnx/onnx#2618]
Environment: PyTorch version---1.2.0, Cuda---10.0
Related Link:  https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

Question: when I use the example provided by the above link, it is ok. but as I change the value 
of parameter 'dynamic_axis' to {'input' : {0 : 'batch_size', 2 : 'height', 3 : 'width'},  'output' : {0:'batch_size', 2 : 'height', 3 : 'width'}}), and the shape of input change to (1, 3, 200, 200), it shows that **The input tensor cannot be reshaped to the requested shape. Input shape:{1,9,200,200}, requested shape:{-1,1,3,3,224,224}**, from the verbo trace I can see this line : %16 : Tensor = onnx::Constant [value=  -1    1    3    3  224  224 [ CPULongType{6} ]](), it seems the shape cannot be changed ! so I wonder wheather torch.nn.pixelshuffle does not support dynamic_axes when using onnxruntime.InferenceSession.run?

Best sincerely
Thanks all !

**Comment by linkerzhang** [comment]
Looks to me, this is either an unsupported scenario - can't support multiple dynamic dimensions' export, or a bug in the exporter, or the model itself does ask for fixed image size (height and width) because of some ops' limitation so that the two dimensions can't be exported as "dynamic" one. In anyway, the final exported shape as [-1, 1, 3, 3, 224, 224] should be a bug. Number of dimensions does not match there.

@spandantiwari can you help to take a look at this please? Thank you very much!

**Comment by reddandelion217** [comment]
Thank you anyway for your suggestion, I will move this issue to PyTorch community. @linkerzhang

**Comment by jb2020-super** [comment]
By using opset_version=11 solved this issue. The pixelshuffle op is converted to DepthToSpace.
