### ISSUE TITLE
chang input dtype

### ISSUE THREAD

**Issue by sezarxray** [onnx/onnx#2738]
dear sir,
I tried to convert my model  tensorflow->onnx->tensorrt
but tensorrt said your input has type uint8 (no support)
is there a way to change model input from uint8 to int32 in onnx model?
regards.

**Comment by linkerzhang** [comment]
One way is parsing the model into a protobuf object, update and save it. 

Is there a way to do type replacement during conversion? @guschmue Sir.

**Comment by sirius0503** [comment]
> One way is parsing the model into a protobuf object, update and save it.
> 
> Is there a way to do type replacement during conversion? @guschmue Sir.

@linkerzhang : Can you link to it, how we can do so, parsing the protobuf and updating it and then saving it?

**Comment by sezarxray** [comment]
> > One way is parsing the model into a protobuf object, update and save it.
> > Is there a way to do type replacement during conversion? @guschmue Sir.
> 
> @linkerzhang : Can you link to it, how we can do so, parsing the protobuf and updating it and then saving it?

import onnx

onnx_model = onnx.load("ssd_inception_v2_coco_2018_01_28.onnx")
graph = onnx_model.graph

for tensor_info in [graph.node[0]]:
    print(tensor_info.attribute)
    att= tensor_info.attribute
#     for at in att:
#         print('get',getattr(at, "type", None))

#         if (getattr(at, "type", None)==2):
#             setattr(at, "type",2)
        
#         setattr(at, "type",7)
    print('############',tensor_info.attribute)    
#     for value_info in tensor_info:
#         print(value_info)
#         dim = value_info.type.tensor_type.shape.dim
#         if not len(dim):
#             continue
#         val = getattr(dim[0], "dim_param", None)
#         if val == 'Sequence':
#             dim.remove(dim[0])

# while len(graph.value_info):
#     graph.value_info.remove(graph.value_info[0])
tp=getattr(graph.input[0], "type", None)
if getattr(tp, "tensor_type", None).elem_type==2:
    getattr(tp, "tensor_type", None).elem_type=6
#     int32 6
onnx.save(onnx_model, 'ssd_inception_v2_coco_2018_01_28_nouint.onnx')

**Comment by sirius0503** [comment]
Hi @sezarxray :

For me the following happens when I run your code:
```
graph.node[0] = output: "67"
op_type: "Constant"
attribute {
  name: "value"
  t {
    data_type: 7
    raw_data: "\000\000\000\000\000\000\000\000"
  }
  type: TENSOR
}

```
So, we have:
```
att =  [name: "value"
t {
  data_type: 7
  raw_data: "\000\000\000\000\000\000\000\000"
}
type: TENSOR
]
```
And then, **getattr** returns None since there is no attribute named type, I have dtype don't know how to access it.

Also, then trying to code below it:

```
tp=getattr(graph.input[0], "type", None)
#gives 
tp = tensor_type {
  elem_type: 1
  shape {
    dim {
      dim_value: 54
    }
    dim {
      dim_value: 1
    }
    dim {
      dim_value: 64
    }
    dim {
      dim_value: 64
    }
  }
}
# But on doing
tp.elem_type 
AttributeError: elem_type # is the output

```
So, still don't know how to work with this, also would be great if you can also explain the _type_ and _dtype_ numbers **2** , **6**, **7**, etc , their meanings, etc.

Thanks

**Comment by TMVector** [comment]
I'm not sure what the posted snippet is trying to achieve exactly, but changing just the graph inputs won't be sufficient. Unfortunately I think changing the types manually is likely to be error prone, and you'd be much better off changing your TensorFlow model to int32 and exporting that.

However, if you have the model in float32 format, it's probably better to export that directly, and maybe to use the TensorRT compression tooling if you need it.

---

If you were to change the ONNX model by hand, OTTOMH you would need to change:
* [Graph input and output](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L423-L424) ValueInfoProtos (change the `model.graph.input[*].type.tensor_type.elem_type` field to `onnx.TensorProto.INT32`)
* [Initializer](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L414) tensors
* Tensors on [`Constant`](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant) nodes

Plus it's not unlikely your model could contain operators which are more involved to fiddle with (because then you're changing the algorithm), such as `Cast`, `QuantizeLinear`, `MatMulInteger` -> `MatMul`, and so on. I would definitely avoid this route if at all possible!

---

@sirius0503 the numbers are from the [`TensorProto.DataType` enum](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L449-L478), which can be accessed by name in Python as e.g. `onnx.TensorProto.UINT32`.

**Comment by waittim** [comment]
@TMVector 
Hi, I tried to change the ONNX model from INT64 to INT32 by hand. However, it brings a weird problem. Would you mind have a look?
```
from onnx import numpy_helper
import struct
onnx_model = onnx.load('weights/yolo-fastest.onnx')
```
I used this code to change the datatype of initializer:
```
changed_initializer = []
for i in range(len(onnx_model.graph.initializer)):
    ini = onnx_model.graph.initializer[i]
    if ini.data_type == 7:
        print('#'*50)
        print(ini)
        dims = ini.dims
        data_type = ini.data_type
        name = ini.name
        changed_initializer.append(name)
        raw_data = ini.raw_data
        array = numpy_helper.to_array(ini)
        print(array)
        array_byte = struct.pack('i', array[0])
        print(array_byte)
        print(dims)
        print('-'*50)        
        new_ini = onnx.helper.make_tensor(
            name=name, 
            data_type=onnx.TensorProto.INT32, 
            dims=dims, 
            vals=array_byte, 
            raw=True)
        onnx_model.graph.initializer.remove(ini)
        onnx_model.graph.initializer.insert(i, new_ini)
        print(new_ini)
```
This code for changing nodes:
```
for n in range(len(onnx_model.graph.node)):
    node = onnx_model.graph.node[n]
    name = node.name
    inputs = node.input
    outputs = node.output
    op_type = node.op_type
    for att in node.attribute:
        if att.t.data_type == 7:
            print('#'*50)
            att_name = att.name
            print(node)
            print('-'*50)
            print(onnx.numpy_helper.to_array(att.t))
            numpy_array = onnx.numpy_helper.to_array(att.t).astype(np.int32)
            new_tensor =  numpy_helper.from_array(numpy_array)
            # X = onnx.helper.make_tensor_value_info(att_name, onnx.TensorProto.INT32, numpy_array)
            print('-'*50)
            print(new_tensor)
            new_node = onnx.helper.make_node(
                name=name,
                inputs=inputs,
                outputs=outputs,
                op_type=op_type,
                value=new_tensor
            )
            print(new_node)
            onnx_model.graph.node.remove(node)
            onnx_model.graph.node.insert(n, new_node)
    continue
```
Everything looks good. The converted model passed the `onnx.checker.check_model(onnx_model)`.  However, when I was trying to run it by onnxruntime, it told me:
`InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from weights/yolo-fastest-transfer.onnx failed:This is an invalid model. Type Error: Type 'tensor(int32)' of input parameter (1540) of operator (ConstantOfShape) in node (ConstantOfShape_245) is invalid.`

So I checked the related initializer and node again by this code:
```
name = '1540'

print('#'*50,'\nFound in initializer: ')
for initializer in onnx_model.graph.initializer:
    if initializer.name == name:
        print(initializer)
        print(onnx.numpy_helper.to_array(initializer))

print('#'*50,'\nFound in output: ')
for node in onnx_model.graph.node:
    if name in node.output:
        print(node)

print('#'*50,'\nFound in input: ')
for node in onnx_model.graph.node:
    if name in node.input:
        print(node)
```
It looks everything is alright. There is nothing different from the original version but the datatype and raw_data:
```
################################################## 
Found in initializer: 
dims: 1
data_type: 6
name: "1540"
raw_data: "\005\000\000\000"

[5]
################################################## 
Found in output: 
################################################## 
Found in input: 
input: "1540"
output: "757"
name: "ConstantOfShape_245"
op_type: "ConstantOfShape"
attribute {
  name: "value"
  t {
    dims: 1
    data_type: 6
    raw_data: "\001\000\000\000"
  }
  type: TENSOR
}
```
The model I used can be found [here](https://github.com/waittim/mask-detector/blob/master/modeling/weights/yolo-fastest.onnx).
May I know that do you have any idea about it? Maybe the idea from an expert will be helpful.
Thank you so much!

**Comment by TMVector** [comment]
@waittim sorry I have not been very active on ONNX lately.

The reason this is an error, is that the INT64 values in [this case](https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-20) represent a _shape_ -- and tensor dimensions are int64. Is there a reason you want int32 instead of int64 in this case?

**Comment by serg06** [comment]
@TMVector I'm trying to do this myself too. I have an ONNX model with some `int64` weights, but since `onnxjs` doesn't support `int64`, I need to convert them to `int32` to use it. Do you think that's possible?
