### ISSUE TITLE
Shape inference pass

### ISSUE THREAD

**Issue by crackcomm** [onnx/onnx#2766]
Hello, In [ShapeInference.md](https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md) I read "Shape inference is not guaranteed to be complete.". Does that mean it is sometimes expected to do multiple infer_shapes calls? In my experience, one call to `infer_shapes` only infers shapes of one layer, is that the way it was intended to work?

Thanks.

**Comment by linkerzhang** [comment]
Shape inference is not guaranteed is because,
1. Shape inference is not a MUST of a standard spec, so that it may not be fully focused in terms of engineering.
2. Shape inference is not always doable without running thru the model. For example, the cases when there're dynamic shapes (symbolic ones).

Back to your case, if it's not because of the 2nd reason above, then it may be due to "shape inference function is missed for some op", which can be improved (add the function for the op needed).

**Comment by crackcomm** [comment]
@linkerzhang Thank you for your answer.

**Comment by linkerzhang** [comment]
sure. I'm going to close this issue. Feel free to reopen it if there're more help needed on shape inference functionality.
