### ISSUE TITLE
confusion about shape inference

### ISSUE THREAD

**Issue by Channingss** [onnx/onnx#2819]
1. Is Mul have shape inference? I don't find function:`TypeAndShapeInferenceFunction` of Mul, of course some other OPs too, which means some OPs don't have realizition of  shape inference?
https://github.com/onnx/onnx/blob/925b3657924c0c16cd20b54595f41e76159b03ab/onnx/defs/math/defs.cc#L179
2. I export a Bert model from this repo:https://github.com/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb
I found this input of model is symbolic(not Int64), through input tensor is given by torch.onnx,export, and shape inference of some node is also failed, witch means onnx.shape_inference don't support symbolic shape, right?
![image](https://user-images.githubusercontent.com/12471701/84225300-62498300-ab11-11ea-93c7-a629f5e6d2b5.png)

**Comment by Channingss** [comment]
thanks for your reply,   I export a Bert model from this repo:https://github.com/huggingface/transformers/blob/master/notebooks/04-onnx-export.ipynb
why this input of onnx model is symbolic(not Int64), through input shape is fixed for torch.onnx,export
https://user-images.githubusercontent.com/12471701/84225300-62498300-ab11-11ea-93c7-a629f5e6d2b5.png

**Comment by TMVector** [comment]
If you dig into the code a little you can see they are providing a list of `dynamic_axes`, which tell PyTorch which axes of which inputs should be treated as named dimensions instead of fixed dimensions. You should still be able to run inference exactly the same though.
https://github.com/huggingface/transformers/blob/699541c4b34479451c91b3c6c204d904f62bed83/src/transformers/convert_graph_to_onnx.py#L130

You can find the documentation for that function [here](https://pytorch.org/docs/stable/onnx.html#torch.onnx.export).

Does this cause any issues for you @Channingss, or are you just curious? 🙂
