### ISSUE TITLE
[Bug] - Output type of QuantizeLinear operator should be uint8_t if y_zero_point is not provided

### ISSUE THREAD

**Issue by kevinch-nv** [onnx/onnx#2839]
Spawned off https://github.com/onnx/onnx/pull/2772/files/7ab93cc1b635eada330dae7424d4ff7e8c22c295#r440422245, opening issue to track resolution

**Comment by linkerzhang** [comment]
will you help to fix it please?

**Comment by nvg24** [comment]
Is this resolved?
Looking at it as first issue, so could you provide some more context.
Thanks

**Comment by yufenglee** [comment]
The bug lies in the type and shape inference of QuantizeLinear. It uses input 2 (y_zero_point) to infer the output type. However input 2 can be null, and it leads to a crash. Please refer to the code here:
https://github.com/onnx/onnx/blob/cc2230603422bae893d5bc900d2d773ab34400a4/onnx/defs/quantization/defs.cc#L56

**Comment by difince** [comment]
Hi, I am a new contributor. 
Can I work on this ?

**Comment by askhade** [comment]
Closing this as duplicate of #3744 . PR #3806 is in progress to fix this.
