### ISSUE TITLE
Question about split optimizers

### ISSUE THREAD

**Issue by zpaarish** [onnx/onnx#2847]
I have some questions about the split optimizers (https://github.com/onnx/onnx/blob/master/onnx/optimizer/passes/split.h)

1. Currently I'm using split_predict by calling "optimizer.optimize(original_model, ['split_predict'])" . I wonder if this is the right way to call split_predict. 

2. I compressed resnet using split_predict and I found that the predict network is an empty network without any weights. Weights are in the init network. Does that mean I will have to combine the init and predict networks in order to do inference? If I have to combine them, it seems to me that this method does not reduce the network's size. 

3. Could you give me a pointer to the paper that split optimizer is implementing (if there is any)?

4. Could you suggest a good use case of split optimizer? What network structure would you recommend to compress by using split init/predict?

**Comment by jacky82226** [comment]
Hi @zpaarish,
Currently we are planning to remove the optimizer from onnx since it is not updated with every ONNX spec (model format and op spec) update and therefore it is possible that it cannot apply to your model.
https://github.com/onnx/onnx/pull/2834

1. Yes, you can also use other optimizers at the same time. e.g., `optimizer.optimize(original_model, ['fuse_consecutive_transposes', 'eliminate_nop_transpose', 'split_predict'])`
2. Yes, I think for the purpose of split optimizer is to do some other optimization for separate graphs instead of reducing the networks's size.
3. I only have these things: 
[Optimizer.md](https://github.com/onnx/onnx/blob/master/docs/Optimizer.md)
[Related PR](https://github.com/onnx/onnx/pull/400)
4. Same as 3. I think it might be useless if you only call split_predict for the `onnx.optimize`. More details are [here](https://github.com/onnx/onnx/blob/master/onnx/optimizer/passes/split.h).

Other folks @houseroad might provide more detailed and correct feedback of this. 
Hope it helps.
