### ISSUE TITLE
ONNX node and initializer order

### ISSUE THREAD

**Issue by grjulian** [onnx/onnx#2860]
I've created a simple neural network using keras and converted it to an onnx-file:

```
onnx_model = keras2onnx.convert_keras(model, model.name)
onnx.save_model(onnx_model, "model.onnx")
```

When I read this file again and check the order of graph.node and graph.initializer I recognized, that the initilizer nodes are in the wrong order.

```
onnx_model = onnx.load("model.onnx")  # load onnx model
print (onnx_model.graph.node[0].input[1]) # dense_input         = 1. layer
print (onnx_model.graph.initializer[0].name) # dense_1/kernel:0 = last layer
```

When I try the upper code with an onnx-file from onnx model zoo it works fine but with my own onnx-file the initializer-array is the way arrond (first layer is the last element).

What I'm doing wrong??

**Comment by linkerzhang** [comment]
ONNX does have definition on the node order in a model. Nodes in a model should be in topological order (per the dependencies). ONNX does NOT have any requirements on the order of "tensors", say, the initializers in your case. It is because in ONNX all tensors are referred by "name", which is unique in the model.

That said, your model (converted from keras) should be a valid ONNX model and can be run against an ONNX compatible framework, say, ONNX RUNTIME. if that's not the case, adding @wenbingl who's keras->onnx expert.

**Comment by jacky82226** [comment]
Similar to https://github.com/onnx/onnx/issues/2838?
If you want to get the tensor information with the same order of execution.
You can try this:
```
import onnx
model = onnx.load('model.onnx')
for node in model.graph.node:
  print(node.input)  # output, op_type, attribute or name
```
It seems a few users are confused about this. How about I add a usage of this  in [PythonAPIOverview.md](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md)?

**Comment by jacky82226** [comment]
Similar to https://github.com/onnx/onnx/issues/2838.
It seems a few users are confused about this. Maybe we can update some explanation for the usage in the document.

**Comment by linkerzhang** [comment]
> Similar to #2838.
> It seems a few users are confused about this. Maybe we can update some explanation for the usage in the document.

Good idea! Do you want to try to propose a PR to update the IR.md? we may ask @gramalingam to help review when PR is out :).

**Comment by jcwchen** [comment]
Sure! I will propose a PR for this.
