### ISSUE TITLE
Something wrong in F.upsample while pytorch to onnx 

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx#2882]
# When I transform torch model to onnx, with op 11(or 12),the model seems wrong ,and can't transform from onnx to tensorrt。

### Question
![1](https://user-images.githubusercontent.com/27938135/86684748-69db4980-c035-11ea-9829-2ce98b28e398.png)

This is onnx model in Netron. And It seems wrong in this upasmple node.
When I transform to trt:
**Parsing model
[2020-07-07 01:40:21 WARNING] /home/fffan/fffan_files/other/onnx2trt/onnx-tensorrt-master/onnx2trt_utils.cpp:235: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
While parsing node number 196 [Resize -> "573"]:
ERROR: /home/fffan/fffan_files/other/onnx2trt/onnx-tensorrt-master/builtin_op_importers.cpp:2520 In function importResize:
[8] Assertion failed: (transformationMode == "asymmetric") && "This version of TensorRT only supports asymmetric resize!"**

ONNX: 1.7
Opset version:    11
pytorch version:    pytorch 1.5
tensorRT version: 7.0.0

The upsample code in pytorch is :
![2](https://user-images.githubusercontent.com/27938135/86685967-8a57d380-c036-11ea-9549-b0444a94bcbb.jpg)

And also , I add this following code in torch2onnx ,but it is wrong:
![3](https://user-images.githubusercontent.com/27938135/86686324-d571e680-c036-11ea-87c4-8a80fd7e32e6.jpg)
![4](https://user-images.githubusercontent.com/27938135/86686342-da369a80-c036-11ea-9519-898a021ef33b.jpg)

### Any information I can tell you if you ask me . Thank you for help.

**Comment by askhade** [comment]
@Tian14267 : When exporting a model to pytorch all resize ops with only mode == nearest are mapped to transformation_mode asymmetric. Bilinear mode is mapped to align_corners if align_corners is set to true otherwise pytorch_half_pixel. 
You can check this to see how transformation mode is assigned to onnx resize op
def __interpolate(g, input, size, scale_factor, mode, align_corners, recompute_scale_factor):

You should either fix original model to change the mode to nearest instead of bilnear or add support for pytorch_help_pixel\align_corner mode in trt

**Comment by askhade** [comment]
Closing this item. Please reopen this or create a new one in case you have more questions regarding this.
