### ISSUE TITLE
ONNX Optimizer raises error "Input 0.weight is undefined!" 

### ISSUE THREAD

**Issue by dtch1997** [onnx/onnx#2902]
# Bug Report

### Describe the bug
When running `onnx.optimizer.optimize(model, passes)` with `passes = ['fuse_bn_into_conv']`, optimizer fails with error: 
```
Input 0.weight is undefined!
```

### System information
- OS Platform and Distribution: Windows 10
- ONNX version: 1.7.0  
- Python version: 3.7.4

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
model = onnx.load("models/conv_dummy.onnx")
onnx.checker.check_model(model)
model = onnx.optimizer.optimize(model, passes=['fuse_bn_into_conv'])
```
Model file: [models.zip](https://github.com/onnx/onnx/files/4927215/models.zip)

### Expected behavior
Expected optimizer to run correctly and return an optimized model. 

### Notes

Model was exported from PyTorch with `torch.onnx.export`

**Comment by jcwchen** [comment]
Hi @dtch1997,
Same as https://github.com/onnx/onnx/issues/2903, applying this PR https://github.com/onnx/onnx/pull/2901 should help. You need to use the model after `infer_shapes`. 
```
import onnx
import onnx.optimizer
model = onnx.load("models/conv_dummy.onnx")
onnx.checker.check_model(model)
inferred_model = onnx.shape_inference.infer_shapes(model)
model = onnx.optimizer.optimize(inferred_model, passes=['fuse_bn_into_conv'])
```
Please note that currently we are planning to move the optimizer from onnx/onnx since it is not updated with every ONNX spec (model format and op spec) update and therefore it is possible that it cannot apply to your model.

**Comment by dtch1997** [comment]
@jcwchen thanks. How long do you think it will take for the PR to be merged into master and the package on Anaconda to be updated? I notice the PR changes one of the .cc files - does this mean that I need to compile and build from source if I want to use it right now? 

Re: optimizer, if you're planning to move it, will it be implemented elsewhere? Or will you simply deprecate the functionality and ask clients to reimplement themselves? Whatever the case, I think I'm happy as long as optimizer remains usable in ONNX 1.7.0.

**Comment by jcwchen** [comment]
Hopefully it should be merged into master soon, but I suppose it would take a while to merge into the release version (onnx have just released 1.7.0 recently).

It's a short modification in `onnx/shape_inference/implementation.cc` so you need to add them in your original `implementation.cc` file and compile it from source.
I am still working on it (writing some tests). If there is any bug in this PR, I will inform you here. Sorry for the inconvenience. 

The decision for optimizer is still debatable (keep it in onnx or move to another repo). Since there are some users depend on it, I would say it will still exist. No worries about it.

**Comment by dtch1997** [comment]
After using the workaround discussed in #2903, I was able to resolve this by manually adding all initializer to model input. 

```
for init in model.graph.initializer:
  for value_info in model.graph.value_info:
    if init.name == value_info.name:
      model.graph.input.append(value_info)
```

**Comment by LeBaronDean** [comment]
I have pulled down dtch1997's conv_dummy and tried there workarounds, but am still getting IndexError: Input 0.weight is undefined!
Has this issue been solved?
