### ISSUE TITLE
modify onnx topk

### ISSUE THREAD

**Issue by manhongnie** [onnx/onnx#2921]
I want to know how to modify the topk node. I have an onnx model, but the topk node in it has been damaged. I want to modify it to make it work properly. What do I need to do, like this type of operation that operates on the input, I don’t know how, please tell me a topk

**Comment by manhongnie** [comment]
@askhade

**Comment by skottmckay** [comment]
How was the model created? Models are usually created in different frameworks like pytorch or scikit-learn and converted to onnx, so generally any editing to 'fix' the model should happen there.

**Comment by manhongnie** [comment]
@skottmckay 
The model was created by mmdetection's retinanet, and due to the fact that there are too many files, many of which I did not check, but there are a few nodes such as Gether, which are supported in pytorch, and onnx also supports them, but they are transferred through pytorch2onnx , Its operation is actually unrecognizable, and I can't understand it for a while, so I plan to change the broken nodes on onnx, but obviously my level is not enough, there are many operation nodes I don't know how to deal with it.

**Comment by spandantiwari** [comment]
@manhongnie - Are you using the ONNX export API in PyTorch? I am not sure if I understand your comment about "due to the fact that there are too many files, many of which I did not check,". The export API should typically generate a single ONNX file (unless you are using use_external_data_format=True). Could you explain what files? Finally have you tried running the model in any backend?
