### ISSUE TITLE
How to know what ceil mode is used in ONNX Conv, MaxPooling, AveragePool ? 

### ISSUE THREAD

**Issue by nitin2212** [onnx/onnx#2943]
### Question
Is there any way to determine the ceil_mode ("CEIL" or "FLOOR") or padding info ("SAME" or "VALID") from a node ?

### Further information
In MaxPooling node, when I iterate through the node:
```
for attr in node.attribute:
    print(attr.name)
```

I get the pads/stride/kernel information but not the ceil mode or pad type info ?

I am parsing the graph from alexnet model mentioned in onnx-zoo : https://github.com/onnx/models/tree/master/vision/classification/alexnet

**Comment by jcwchen** [comment]
Hi @nitin2212,

You can find the details in [Operators.md](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and [Changelog.md](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#MaxPool-8) with the model's opset version.

Take MaxPooling as an example.
If the model uses MaxPool of opset 9 (AlexNet models from Model Zoo are using opset version < 10), you need to check the description in [Changelog.md#MaxPool-8](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#MaxPool-8).
It says it uses explicit padding (default). For ceil_mode, I suppose since onnx introduced this attribute from [opset 10](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#MaxPool-10), opset 8 should use the default value of it, which is floor.

**Comment by nitin2212** [comment]
Hey @jcwchen , Thank you very much. That helped !! 
Have a great day :)
