### ISSUE TITLE
Input 1 is undefined on running onnx_caffe2_backend.prepare

### ISSUE THREAD

**Issue by Somdyuti2** [onnx/onnx#2975]
# Bug Report

### Describe the bug
I am trying to convert caffe model to pytorch as per the tutorial given in https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html

On running the line ` prepared_backend = onnx_caffe2_backend.prepare(model)` the following error is thrown:  
`Input 1 is undefined!
`  
I believe this is the same issue or similar to #2902, which was closed a while ago, as the fix seems to be merged.  In fact, `onnx.optimizer.optimize(model) ` raises the identical error. However, I am still facing this problem and I have also tried the workarounds suggested in that issue with no luck. 

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubuntu 18.04
- ONNX version: 1.7.0  
- Python version: 3.6.9

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
import caffe2.python.onnx.backend as onnx_caffe2_backend

# Load the ONNX ModelProto object. model is a standard Python protobuf object
model = onnx.load("super_resolution.onnx")

# prepare the caffe2 backend for executing the model this converts the ONNX model into a
# Caffe2 NetDef that can execute it. Other ONNX backends, like one for CNTK will be
# availiable soon.
# for init in model.graph.initializer:
#   for value_info in model.graph.value_info:
#     if init.name == value_info.name:
#       model.graph.input.append(value_info)
# model = onnx.shape_inference.infer_shapes(model)
prepared_backend = onnx_caffe2_backend.prepare(model)
...
```
### Expected behavior
Expected the function to convert the model to caffe2

### Notes
Ran from a Google Colab notebook.

**Comment by ytaous** [comment]
@jcwchen - can u please take a look?

**Comment by jcwchen** [comment]
Hi @Somdyuti2,
I tried your model with the latest onnx from master, but I still encountered the same error as yours.
I would say this should be not related to the IR version issue and it is more likely be other `onnx.optimizer` issue.

Please note that currently we are planning to remove the optimizer from onnx (move it to other repo) since it is not updated with every ONNX spec (model format and op spec) update and therefore it is possible that it cannot apply to your model. Thanks.

**Comment by Somdyuti2** [comment]
Hi @jcwchen thanks for looking into this. But is it only the issue with the optimizer, because I encountered this error with ` onnx_caffe2_backend.prepare` as well? I am not sure if `onnx_caffe2_backend.prepare` internally calls the optimizer though. Does that mean that the model conversion would no longer be supported by onnx? 

Since the example is on official pytorch documentation, it was probably working at some point earlier. Is it possible to use a previous version of onnx that supports this? It will be helpful if you can clarify.

**Comment by jcwchen** [comment]
Yes it is an issue of `onnx.optimizer` and `onnx_caffe2_backend.prepare` does internally use the `onnx.optimizer`.
I am not sure what the final decision from Facebook is, but it seems that they deprecated caffe2 (including onnx_caffe2): https://github.com/pytorch/pytorch/issues/21726

For the corresponding onnx version, it depends on what the version of onnx_caffe2 you are using. You can open an issue about this in pytorch since onnx_caffe2 was moved to pytorch repo. Sorry that I cannot be more helpful.

**Comment by Somdyuti2** [comment]
Thanks for the information, closing it here then.
