### ISSUE TITLE
Inconsistency in operator description (Pow) - multidirectional  vs. unidirectional broadcastable?

### ISSUE THREAD

**Issue by gineshidalgo99** [onnx/onnx#2998]
# Ask a Question
From the documentation, for the Pow operator, https://github.com/onnx/onnx/blob/master/docs/Operators.md#Pow, is it multidirectional (i.e., Numpy-style) broadcastable or only unidirectional broadcastable?

### Question
1. The doc of Pow says in its first paragraph that "This operator supports multidirectional (i.e., Numpy-style) broadcasting;".
2. The doc for the output Z of Pow also says that Z has the "same size as X".

(I am not a CS expert, so please correct me if I am wrong!) If Z must always have the same size than X, then the Pow operator is "only" unidirectional broadcastable rather that multidirectional, right? I mean, if Pow was multidirectional, then Z would not necessarily have the same size than X, but rather the same size than either X or Y (or both if they have the same size), am I correct?

Thanks!

**Comment by jcwchen** [comment]
HI @gineshidalgo99,
I think you are right. Since `Pow` does support multidirectional, the size of Z is **not necessarily** have the same size than X. The description for Z needs to be corrected for `Pow-7`, `Pow-12` and `Pow-13`. I will send a PR to update the document. Sorry for the confusion and thank you for reporting this!

**Comment by askhade** [comment]
Change merged
