### ISSUE TITLE
Cannot build with pybind11 2.6.0

### ISSUE THREAD

**Issue by xkszltl** [onnx/onnx#3084]
# Bug Report

### Describe the bug

We cannot build with pybind11 2.6 released recently, 2.5 works fine.
Basically a `-I` for `Python.h` is missing.

A bug is filed to them: https://github.com/pybind/pybind11/issues/2632
They mentioned it could be caused by the wrong use in onnx's cmake.
Could you take a look?

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): CentOS 7 / Ubuntu 18.04
- ONNX version (*e.g. 1.7*): Built from latest release tag (1.7.0)
- Python version: distro stock python3
- GCC/Compiler version (if compiling from source): gcc-9 / gcc-8
- CMake version: Built from latest release tag
- Protobuf version: Built from latest release tag

**Comment by henryiii** [comment]
There is a typo: `${PYTHON_INCLUDE_DIR}` should be `${PYTHON_INCLUDE_DIRS}` [here](https://github.com/onnx/onnx/blob/0c070abb0c40fec649f81a73a75b0098662ec486/CMakeLists.txt#L399) ([see docs](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html)). pybind11 2.6 dropped Python from the `pybind11_INCLUDE_DIRS`. It may be restored, as it wasn't really intentional AFAIK; `pybind11_INCLUDE_DIR` is just the pybind11 directory, and `pybind11_INCLUDE_DIRS` has both (not a great idea to combine IMO, but users should be using targets anyway, and both variables are available).

**Comment by jcwchen** [comment]
Hi @xkszltl @henryiii,
Actually I cannot repro this error on Linux, Windows or Mac with pybind11 2.6.0... All of them worked.
So @henryiii what you are suggesting is: even though `PYTHON_INCLUDE_DIR` works for now, it's better to use `PYTHON_INCLUDE_DIRS`? Does `PYTHON_INCLUDE_DIRS` support backward compatibility? Since we probably update pybind11 2.6.0 in ONNX 1.8 Release https://github.com/onnx/onnx/pull/3095, this issue is important to us. Thank you all!

**Comment by henryiii** [comment]
I'm hoping to fix the usage of `pybind11_INCLUDE_DIRS` to be identical to previous versions in pybind11 2.6.1. It looks like `PYTHON_INCLUDE_DIR` is always set by the module and is it internal cached value, but the official output variable has always been `PYTHON_INCLUDE_DIRS`. Now I'm not totally sure why it would have failed for @xkszltl. Yes, `pybind11_INCLUDE_DIRS` unintentionally dropped Python's include dir in 2.6.0 (I personally think it should not have ever been there, as variables should not be recursive, but didn't intend to change the existing behavior), but Onyx is adding it (as it should), so don't see why there was a problem.

It is slightly better to use the publicly documented output `PYTHON_INCLUDE_DIRS` instead of `PYTHON_INCLUDE_DIR`, which is only documented as an input CACHE variable. But they are functionally identical in master and CMake 3.0.0.

**Comment by xkszltl** [comment]
Are you talking about this?
https://github.com/onnx/onnx/blob/72b701f7a55cafa4b8ab66a21dc22da0905b2f4c/CMakeLists.txt#L409

This is before `find_package(pybind11)` and it's not linked to pybind11 anyway, so it won't fix pybind11's missing header.

**Comment by xkszltl** [comment]
@jcwchen Are you using python-customized environment like venv/conda?
It's possible that you have Python.h available under some common dir searched by linker, or from other unrelated `-I`.

**Comment by henryiii** [comment]
Ah, I missed the PRIVATE/PUBLIC.

The line here:
```cmake
  target_include_directories(onnx_cpp2py_export PRIVATE
                             $<BUILD_INTERFACE:${ONNX_ROOT}>
                             $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
                             $<INSTALL_INTERFACE:include>
                             ${PYTHON_INCLUDE_DIR})
```

Will not propagate `PYTHON_INCLUDE_DIRS` (okay, without the S, but they are the same) to users. If there are any dependent targets, this will fail, _unless_ you get `PYTHON_INCLUDE_DIRS` from this line:

```cmake
  if(pybind11_FOUND)
    target_include_directories(onnx_cpp2py_export PUBLIC
      ${pybind11_INCLUDE_DIRS})
```

But in 2.6.0, you don't get that. You really shouldn't, variables should not be transitive, so including `"${PYTHON_INCLUDE_DIRS}"` here too.

By the way, the following else is always wrong:
```cmake
  else()
    if(EXISTS ${ONNX_ROOT}/third_party/pybind11/include/pybind11/pybind11.h)
      target_include_directories(onnx_cpp2py_export PUBLIC
        ${ONNX_ROOT}/third_party/pybind11/include)
```

This will never include Python's include directory, so it only works if you have Python.h already included in a common location somehow. This is one of the reasons "PACKACKE_INCLUDE_DIRS" should not be transitive, but only include the directory(s) that a project itself provides. Targets (like `pybind11::pybind11`) should be used if transitive requirements are needed.

**Comment by henryiii** [comment]
And if there are no targets depending on `onnx_cpp2py_export`, then this is correct as far as I can tell, other being a bit confusing by using PUBLIC and PRIVATE differently when no one uses it.

**Comment by henryiii** [comment]
Also any raw usage of a CMake variable that might have a path in it should have quotes around it.

**Comment by jcwchen** [comment]
@henryiii Thank you so much for the detailed and helpful instructions!
@xkszltl Do you have bandwidth to send a PR to fix this? (Done after ONNX 1.8.0 is fine) Otherwise I cannot repro this in my local or on CIs so it is quite hard for me to verify the correction. Thank you.

**Comment by xkszltl** [comment]
@jcwchen 
Got some busy work to do recently.
Besides, I think it's important to repro it in CI, or it can be easily broken again in other places.

**Comment by jcwchen** [comment]
I tried but still failed to reproduce... @xkszltl how did you fix this issue in your machine? Did you go with changing `PYTHON_INCLUDE_DIR` into `PYTHON_INCLUDE_DIRS`? Did you use pip install git+https://github.com/pybind/pybind11 or change the commit in the pybind11 submodule of ONNX to update pybind11 (2.6.1)? Thank you for sharing your experience.

I think the CIs didn't break because they will use a fixed version of pybind11 (2.4.3 for main branch) as a submodule under ONNX (By default if ONNX does not find pybind11 locally, it will use its pybind11 submodule), but even if I used 2.6.0 commit, the CIs still pass... Just like you said, there should be something (conda/virtualenv) has included `Python.h` already. @henryiii May I ask you what's your suggestion to solve this kind of issue? (Like finding Python packages in `CMakelist.txt` before importing pybind11 or import pybind11 submodule by another way?) Thank you.

**Comment by henryiii** [comment]
I would recommend the suggestions I listed above. I can make a quick PR to outline them.

**Comment by jcwchen** [comment]
> I would recommend the suggestions I listed above. I can make a quick PR to outline them.

That would be great! Thank you so much.

**Comment by xkszltl** [comment]
Basically I build latest release tag of pybind as part of our CI. And I add an additional git cherry-pick to backport the patching commit from master

**Comment by jcwchen** [comment]
> Basically I build latest release tag 2.6.0 of pybind as part of our CI. And I add an additional git cherry-pick to backport the patching commit from master

So it looks like you didn't change anything in ONNX? (like modify CMakelists.txt) If so, does ONNX only have issue with pybind11 2.6.0? Thanks.

**Comment by henryiii** [comment]
I think @xkszltl back ports the patch to pybind11. Could you try it without the pybind11 patch, but with the patch in the PR to Onnx?

**Comment by jcwchen** [comment]
> I think @xkszltl back ports the patch to pybind11. Could you try it without the pybind11 patch, but with the patch in the PR to Onnx?

Yes I did try that, but it (only use pybind11 2.6.0 submodule) still worked for me...

**Comment by xkszltl** [comment]
@jcwchen 
Pybind11 release tag (2.6.0) + pybind11 patch + onnx release tag works.
But the issue is in onnx, because it relies on undefined behavior in pybind11, which uses the non-recursive (so only pybind, no python) cmake var to link pybind11.
The pybind11 patch restore the old behavior of that UB.

**Comment by jcwchen** [comment]
@xkszltl Thank you for the explanation! That makes sense to me. If you have time, please take a look at https://github.com/onnx/onnx/pull/3105 to see whether it solves this issue.

**Comment by xkszltl** [comment]
@jcwchen That one LGTM

**Comment by xkszltl** [comment]
The linked PR is still opened.
@jcwchen Could you help clarify what's the current status or what's blocking there? Thanks

**Comment by henryiii** [comment]
Feel free to ping me if anything is needed there.

**Comment by jcwchen** [comment]
@xkszltl Thanks for the reminder. I think we should forward it since it can solve some potential problems.

@henryiii Could you please resolve the pybind11 version conflict in your PR #3105? Let's see how it goes with current CIs. Thank you for the contribution.
