### ISSUE TITLE
function 'expect' not work in this example

### ISSUE THREAD

**Issue by lkyf** [onnx/onnx#3177]
# Bug Report

```
import numpy as np
import onnx
from onnx.backend.test.case.node import expect

node = onnx.helper.make_node(
    'Cos',
    inputs=['x'],
    outputs=['y'],
)

x = np.array([-1, 0, 1]).astype(np.float32)
y = np.cos(x) - 2

expect(node, inputs=[x], outputs=[y], name='test_cos_example')
```

**Comment by jcwchen** [comment]
Hi @lkyf,
Could you elaborate what the bug is? Thank you.

**Comment by jcwchen** [comment]
Please note that the `expect` function [here](https://github.com/onnx/onnx/blob/d3923792b7eeb2b4d616b66e0853f54a579ea038/onnx/backend/test/case/node/__init__.py#L127) is not doing any logic check. It's a tool to create testcases by numpy for other runtime framework to verify their runtime logic. So here what we need to do is using numpy to do the same logic as ONNX operator. 

Since I haven't received any response for a while, I will close it now. Please reopen it if you still have other ONNX issue. Thank you!
