### ISSUE TITLE
An API to get the ONNX release version from the model

### ISSUE THREAD

**Issue by Nirmal-Neel** [onnx/onnx#3287]
Hi,

Do you have any plan to provide an API using which a user can get the ONNX release version from the model (which was created somewhere else)? This will be helpful because by looking at the **ir_version** and **opset_imports**, it is hard to determine the ONNX release version which was used during the model creation time.

Thanks!

**Comment by jcwchen** [comment]
Hi @Nirmal-Neel,
Does current version table meet your requirement? https://github.com/onnx/onnx/blob/9696da66a398ccbb6a31c6defd2ce5da0a03a024/onnx/helper.py#L28
You can get it from `onnx.helper.VERSION_TABLE`. Thanks.

**Comment by Nirmal-Neel** [comment]
Hi @jcwchen, I did refer to this table. But this table becomes confusing for onnx version **1.8.0** and **1.8.1**. For these two versions, all the remaining elements in the tuple are same. So, which version to select in that case?

**Comment by jcwchen** [comment]
You can use 1.8.1 directly for opset 13 because there is no operator modification between 1.8.0 and 1.8.1. (1.8.1 is a patch release for 1.8.0 and there are only some build/utility changes in 1.8.1) If there is something related to operator modification in the patch release, the opset version will bump. (e.g., 1.1 vs 1.1.2)  Thanks.

**Comment by Nirmal-Neel** [comment]
Thanks @jcwchen! Just one final question - 
```python
    ('1.0', 3, 1, 1),
    ('1.1', 3, 5, 1),
    ('1.1.2', 3, 6, 1),
    ('1.2', 3, 7, 1),
    ('1.3', 3, 8, 1),
    ('1.4.1', 4, 9, 1),
    ('1.5.0', 5, 10, 1),
    ('1.6.0', 6, 11, 2),
    ('1.7.0', 7, 12, 2, 1),
    ('1.8.0', 7, 13, 2, 1)
```
My understanding from the above table is that a model with IR version 3 cannot have _ai.onnx_ opset version higher than 8. Similarly, a model with IR version 4 cannot have _ai.onnx_ opset version higher than 9 and so on. Is my understanding correct? If so, then there are few models which use higher opset version than expected.

For example - [T5](https://github.com/onnx/models/tree/master/text/machine_comprehension/t5) model from onnx model zoo says that it uses ONNX version 1.6.0 and opset 12. The ir_version of the model is set to 6 and the opset_import contains version 12 for _ai.onnx_. But from the VERSION_TABLE, it can be seen that opset 12 was released with version 1.7.0. 

Could you please make it clear to me? Am I missing something?

**Comment by jcwchen** [comment]
Good question. Although I don't have the history context here, I guess perhaps this model was produced between 1.6.0 and 1.7.0 with the main branch of ONNX repo. During the development before ONNX 1.7.0, it is possible that the opset_version has been bumped into opset 12, but VERSION_NUMBER and IR_VERSION is still the old one as ONNX 1.6.0.

**Comment by Nirmal-Neel** [comment]
So, will you agree with me that by looking into the ir_version and opset_import of a model and then referring to this VERSION_TABLE will not always give us the correct onnx version? Actually in some cases it will confuse us. In my above example, for the T5 model, the ir_version is 6 and the opset version is 12. In that case it is really confusing to select the onnx version (1.6.0 or 1.7.0).

**Comment by jcwchen** [comment]
Yes... this table is only consistent for the released version of ONNX. If the model is produced by development of source code instead of the released ONNX, the versions might be differ. May I ask you why you need the exact ONNX version for the model? Actually, in your case, I would suggest you use the newer one (ONNX 1.7.0) for this model because ONNX does support backward compatibility to some extent. 

Since it is possible that the model was produced by development of ONNX (somewhere between the released versions), I don't think ONNX proto needs to include the used ONNX version. Instead, ONNX proto has opset_version and IR_VERSION already, which were exactly what the model was using. Please let me know if you have other thought. Thank you!

**Comment by askhade** [comment]
ONNX maintains backward compatibility so using the latest version should be good. The table above indicates the onnx version in which the opset\irversion were released

Take a look at this helper function: https://github.com/onnx/onnx/blob/bd2ff65b775580d21ab38cb655a04854c348ff49/onnx/helper.py#L62

**Comment by Nirmal-Neel** [comment]
Thanks @jcwchen and @askhade! Actually I am trying to write an API which can provide all the properties of an ONNX model. For that I thought I will extract the ONNX version too. I have made a small modification to that helper function so that it gives me the onnx release version too.
```python
def create_op_set_id_version_map(table):
    result = dict()

    def process(release_version, ir_version, *args): 
        for pair in zip(['ai.onnx', 'ai.onnx.ml', 'ai.onnx.training'], args):
            if (pair not in result):
                result[pair] = (ir_version, release_version) #adding the release_version too
    for row in table:
        process(*row)
    return result
```
