### ISSUE TITLE
Div operator - Inputs of different types

### ISSUE THREAD

**Issue by bsledz** [onnx/onnx#3289]
# Div operator

### Question
In the specification of the Div operator in version 7 and later, the clarification that both inputs should be of the same type has been removed. Does this mean that inputs of different types are supported? What is the expected behavior?

**Comment by jcwchen** [comment]
Hi @bsledz,
I don't think so. The main change between opset 6 and opset 7 for div is supporting Multidirectional Broadcasting. Besides, the output description for Div-7 is `... has same element type as two inputs`. Thanks.

**Comment by bsledz** [comment]
So why does the model checker allow inputs of different types?

**Comment by askhade** [comment]
the type constraint T in the spec indicates that both the inputs need to be of the same type:

Div
Performs element-wise binary division (with Numpy-style broadcasting support).

This operator supports multidirectional (i.e., Numpy-style) broadcasting; for more details please check the doc.

(Opset 14 change): Extend supported types to include uint8, int8, uint16, and int16.

Version
This version of the operator has been available since version 14 of the default ONNX operator set.

Other versions of this operator: 1, 6, 7, 13

Inputs
A (differentiable) : **T**
First operand.
B (differentiable) : **T**
Second operand.
Outputs
C (differentiable) : **T**
Result, has same element type as two inputs
Type Constraints
T : tensor(uint8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(int8), tensor(int16), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double), tensor(bfloat16)
Constrain input and output types to all numeric tensors.

Currently checker does not check type-constraints specified in the op-schema spec and it is on our list to fix this.

**Comment by askhade** [comment]
checker support type check when full_cehck is enabled: check_model(model, full_check=True)
