### ISSUE TITLE
RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.

### ISSUE THREAD

**Issue by SheikZaidhCoder** [onnx/onnx#3330]
while converting the pytorch to ONNX
RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.

**Comment by jcwchen** [comment]
Hi @SheikZaidhCoder,
What's your desired opset_version? As mentioned in the error message, for lower opset_version, I think dynamic input for slice is not supported by the converter because DynamicSlice was deprecated. However, dynamic input should be supported since Slice-10. Could you try opset_version >= 10? Thanks.

**Comment by SheikZaidhCoder** [comment]
Thanks
