### ISSUE TITLE
Creating a plugin to replace current operators

### ISSUE THREAD

**Issue by hoangmt** [onnx/onnx#3399]
# Ask a Question

### Question
Is it possible to write a plugin in python to replace a current operator? For example, the current NMS operator requires dtype=int64, I want to create a new operator with dtype=int32 so the model can be parsed by trtexec.

**Comment by jcwchen** [comment]
Hi @hoangmt,
Actually it you don't use onnx.checker/shape_inference or ONNXRuntime, you can change the operator to whatever you want. (Simply change the dtype from int64 into iny32 by Python) Basically, ONNX is a spec that all other frameworks should follow. So it depends on whether trtexec has the flexibility to accept int32 for NMS or not.

**Comment by askhade** [comment]
You can write a custom op.

**Comment by askhade** [comment]
I don't understand what you exactly mean by plugin... if you are wondering whether you can make modifications to the model then the answer is yes... 
If tensorrt is not able to load an onnx model because it does not support an onnx op then you should open a bug in their repo to have them support this op. You can also check out onnxruntime and use Tensorrt execution provider... the advantage is, if for any reason tensorrt does not support a particular op, the op execution will fallback to cuda or cpu provider and your model will work.
