### ISSUE TITLE
Pow support for bfloat16

### ISSUE THREAD

**Issue by manbearian** [onnx/onnx#3409]
I see that with opset13 bfloat16 support has been added to [Pow](https://github.com/onnx/onnx/blob/master/docs/Operators.md#pow
), however only the first operand `T` has been updated to support bfloat16 ; should the second operand `T1` be updated as well?

Reproduced here from https://github.com/onnx/onnx/blob/master/docs/Operators.md#pow

```
T : tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double), tensor(bfloat16)
Constrain input X and output types to float/int tensors.
T1 : tensor(uint8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(int8), tensor(int16), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double)
Constrain input Y types to float/int tensors.
```

**Comment by jcwchen** [comment]
Hi @manbearian,
I don't have the history context here, but it does make sense to me that the power of the exponent should support bfloat16 as well... Originally, the types of base and power are different since ONNX wants to prevent overflow issue for base (not allow small integer/float). So, if bfloat16 is acceptable for base, I would say bloat16 should be OK for power, too.

@onnx/sig-operators Does anyone have other concerns about it? Thanks.

**Comment by gramalingam** [comment]
Makes sense to me to extend it, thanks!
