### ISSUE TITLE
how to change batchsize for the whole model

### ISSUE THREAD

**Issue by ShiyangZhang** [onnx/onnx#3483]
### Question
I have a model whose batch-sizeis one. I need a batch-size-32 onnx model, but cannot find the original pytorch model.
Is their any method to do this?

 I can update model's input and output dims by update_model_dims.py, but the result model cannot be used:
' The input tensor cannot be reshaped to the requested shape. Input shape:{32,16,1,1}, requested shape:{1,16} '

**Comment by jcwchen** [comment]
Hi @ShiyangZhang,
Could you please provide your ONNX model and the python script you used to repro this error? Thanks!

**Comment by swithmn1** [comment]
I have same question with you ,so how to do?@ShiyangZhang

**Comment by askhade** [comment]
you will need to update the model itself... You can do something like this
Update input shape
For every node n in graph.node:
  get the inferred shape 
  override the existing shape with inferred shape

You can check the current graph level shape inference logic here: 
https://github.com/onnx/onnx/blob/master/onnx/shape_inference/implementation.cc#L189

You can't directly use this because if shape exists for a node input then it will complain with the inferred shape is not same as existing shape... In your case you know the inferred shape will be different so you will have to force replace it
