### ISSUE TITLE
Pytorch export onnx: RuntimeError Exporting the operator var to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator 

### ISSUE THREAD

**Issue by SanjanaUdayashankar** [onnx/onnx#3528]
Feature Request
would you support operator "var" ? Thanks a lot

System information
ONNX opset version: opset 9~11

**Comment by jcwchen** [comment]
Hi @SanjanaUdayashankar,
This op is not supported by the converter yet: https://pytorch.org/docs/stable/onnx.html#supported-operators. And there are existing issues about this: https://github.com/onnx/onnx/issues/2045, https://github.com/onnx/onnx/issues/3216. Please track this issue at https://github.com/onnx/onnx/issues/2045 or pytorch repo. Or perhaps use use `torch.std()^2` instead of `torch.var()` in your PyTorch models. Close it now. Thanks
