### ISSUE TITLE
Docker container is too old

### ISSUE THREAD

**Issue by pooyadavoodi** [onnx/onnx#353]
The ONNX container here seems too old: https://hub.docker.com/r/onnx/onnx-docker/

It would be great if the docker build was automatic. Perhaps it's because the Dockerfile is stored in a repo that is not under onnx: https://github.com/houseroad/dockerfiles

**Comment by mkolod** [comment]
Yes, it's because the Dockerfile is in the "houseroad" repo. That repo only contains the Dockerfiles. If there is no update to the repo (since the Dockerfiles don't need updating often), Dockerhub won't rebuild the image just because the onnx-caffe2 repo, or some other repo, get updated.

I think one solution here is to put the Dockerfiles the onnx-caffe2 repo. That would force a rebuild of the containers upon every commit to onnx-caffe2 master. Another option is to do nightly rebuilds of the container independent of onnx-caffe2, since the container includes things other than onnx-caffe2 (e.g. PyTorch). This might be a better option, since things from several different repos converge into this Docker image, and the Dockerhub auto-rebuild can only depend on updates from one repo for the rebuild trigger.

The current Docker images is ancient (7 weeks, which IIRC was the time of the initial ONNX announcement). Many things have changed in onnx-caffe2 and other packages shipped in this image.

**Comment by houseroad** [comment]
The [universe repo](https://github.com/onnxbot/onnx-fb-universe) contains onnx, onnx-caffe2, caffe2, pytorch, and it is easy to set up. I will move the Dockerfiles there and update the docker images.

**Comment by mkolod** [comment]
@houseroad Great! Of course, people can just locally do 

```docker build -t my-onnx-container .```

but it would definitely be good for the docker images.

Thanks!

**Comment by houseroad** [comment]
Just updated the ONNX docker images. Try it. :-)
I would leave this open until the autogenrated script is set up.

**Comment by mkolod** [comment]
@houseroad Yes, I just tried the GPU container. Thanks!

**Comment by ezyang** [comment]
@houseroad Can we close this now?
