### ISSUE TITLE
RuntimeError: Exporting the operator _convolution_mode to ONNX opset version 9 is not supported.

### ISSUE THREAD

**Issue by pawopawo** [onnx/onnx#3534]
# New Operator

### Describe the operator
Why is this operator necessary? What does it accomplish?

### Can this operator be constructed using existing onnx operators?
If so, why not add it as a function?

### Notes
Any additional information

**Comment by pawopawo** [comment]
`/opt/tiger/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py:440: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at  /pytorch/aten/src/ATen/native/Convolution.cpp:660.)`

**Comment by pawopawo** [comment]
torch==1.9.0
padding="same"

cannot covert onnx, hope for help

**Comment by jcwchen** [comment]
Hi @pawopawo,
Currently `torch.onnx.export` does not support _convolution_mode op. You can check the supported operator list here: https://pytorch.org/docs/stable/onnx.html#supported-operators. Please raise an issue for this op support in [pytorch](https://github.com/pytorch/pytorch/issues/new?assignees=&labels=&template=feature-request.md) repo. Close it now due to it's a converter issue. Thanks!
