### ISSUE TITLE
index_put works wrong when repeated indices  and True accumulate exist

### ISSUE THREAD

**Issue by johnnyleeRH** [onnx/onnx#3547]
# Bug Report

### Is the issue related to model conversion?
no
### Describe the bug
when repeated indices exist, the result will only add the last index element even the accumulate set to True

### System information
-  Linux Ubuntu 18.04: 
- ONNX version :  1.9
- Python version: 3.8.5
- GCC/Compiler version (if compiling from source): 7.5
- CMake version: 3.10.2
- Protobuf version: 
- Visual Studio version (if applicable):

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import onnxruntime


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        

    def forward(self,  index,  A, B):
        A = A.index_put((index,), B, accumulate=True)
        return A

trained_model = Net()
A= torch.ones(5, 3)
B = torch.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1],[1, 1, 1],[1,1,1]], dtype=torch.float)
index = torch.tensor([0, 4, 2,2,4])
input = (index,A,B)
torch.onnx.export(
                trained_model,
                input,
                "net_demo.onnx",
                # operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
                opset_version=11)

ort_session = onnxruntime.InferenceSession("net_demo.onnx")
ort_inputs = {ort_session.get_inputs()[0].name:index.cpu().numpy(),
    ort_session.get_inputs()[1].name:A.cpu().numpy(),
    ort_session.get_inputs()[2].name: B.cpu().numpy()}

ort_outs = ort_session.run(None, ort_inputs)
print('ort_outs:')
print(ort_outs)
```

### Expected behavior
expect result is :
[array([[2., 2., 2.],
       [1., 1., 1.],
       [3., 3., 3.],
       [1., 1., 1.],
       [3., 3., 3.]], dtype=float32)]
but the actual result is:
[array([[2., 2., 2.],
       [1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 1.],
       [2., 2., 2.]], dtype=float32)]

**Comment by jcwchen** [comment]
Hi @johnnyleeRH,
Actually ONNX does not have index_put op so it seems like a converter issue to me, only happened while  accumulate=True. You can check whether the produced ONNX model is as expected. If the produced model is correct, then something in Runtime is wrong and please open an issue in ONNXRuntime. By contrast, if the produced model is incorrect, please raise an issue in PyTorch since the ONNX model is not correctly converted.

Close it now. Please reopen it if you have other ONNX question. Thank you!

**Comment by martinResearch** [comment]
I found a workaround which consists rewriting `A = A.index_put((index,), B, accumulate=True)` as 
```
        index1d = (index * A.shape[1])[:, None] + torch.arange(A.shape[1])
        A = torch.scatter_add(A.flatten(), 0, index1d.flatten(), B.flatten()).reshape(A.shape)
```
This might need some rewriting to handle different case for the shapes of A, index and B than used in the example above.
You will also using `opset_version=16` when exporting to onnx, otherwise you will get wrong results (see https://github.com/pytorch/pytorch/issues/32960).

The revised code looks like this 
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import onnxruntime


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

    def forward(self, index, A, B):
        index1d = (index * A.shape[1])[:, None] + torch.arange(A.shape[1])
        A = torch.scatter_add(A.flatten(), 0, index1d.flatten(), B.flatten()).reshape(A.shape)
        return A


trained_model = Net()
A = torch.ones(5, 3)
B = torch.tensor([[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]], dtype=torch.float)
index = torch.tensor([0, 4, 2, 2, 4])
input = (index, A, B)
torch.onnx.export(
    trained_model,
    input,
    "net_demo.onnx",
    # operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
    opset_version=16,
)

ort_session = onnxruntime.InferenceSession("net_demo.onnx", providers=["CPUExecutionProvider"])
ort_inputs = {
    ort_session.get_inputs()[0].name: index.cpu().numpy(),
    ort_session.get_inputs()[1].name: A.cpu().numpy(),
    ort_session.get_inputs()[2].name: B.cpu().numpy(),
}

ort_outs = ort_session.run(None, ort_inputs)
print("ort_outs:")
print(ort_outs)
```
Would still be good to fix `index_put`.
