### ISSUE TITLE
infer_shapes fails but onnxruntime works

### ISSUE THREAD

**Issue by xadupre** [onnx/onnx#3565]
# Bug Report

### Is the issue related to model conversion?
onnx raises an exception while running ``infer_shapes`` (``onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Sqrt, node name: ComplexAbsoutput__19): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 1: (4) vs (3)``).

### Describe the bug

The following code fails (onnx graph: [bug_shape_inference.zip](https://github.com/onnx/onnx/files/6785879/bug_shape_inference.zip)):
```
import onnx
with open('bug_shape_inference.onnx', 'rb') as f:  #see attached file
    model_proto = onnx.load(f)
onnx.checker.check_model(model_proto, full_check=True)
```

Exception:
```
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Sqrt, node name: ComplexAbsoutput__19): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 1: (4) vs (3)
```

However, onnxruntime is able to compute the output:

```
from onnxruntime import InferenceSession
import numpy
mat = numpy.random.randn(3, 4).astype(numpy.float32)
sess = InferenceSession('bug_shape_inference.onnx')
print(sess.run(None, {'input:0': mat}))
```

It produces a matrix (3,3) as mentioned in the onnx graph:

```
  output {
    name: "output:0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
```

The error message seems to say onnx expects an output with shape (4,3) or (3,4) when it should be (3,3).

### System information
- OS Platform and Distribution (*Windows, Ubuntu 20.04*): 
- ONNX version (*e.g. 1.7*):  1.9.0
- Python version: 3.9.5
- Visual Studio version (if applicable): 2019

### Reproduction instructions
See the bug description.

### Expected behavior
I would expect infer_shapes to succeed and find a shape equal to (3,3).

**Comment by jcwchen** [comment]
Hi @xadupre,
Actually ORT does complain that the output shape (3, 4) is not same as the expected shape (3, 3) during `onnxruntime.InferenceSession` (since it uses node-level ONNX shape inference), but it can still produce the result with shape (3, 3) anyway... So there does exist a mismatch between ONNX and ORT.

Is (3, 3) the correct expected shape for this graph? If so, could you please help me identify where the bug is? Thank you. My thought:
(3, 4) -> Transpose 1, 0 = (4, 3) -> MatMul with (2, 4, 4) = (2, 4, 3) -> Slice -> Transpose 0, 2, 1 = (2, 3, 4) -> Gather axis=0, indices = 0 or 1 = (1, 3, 4) -> Pow -> Add -> Squeeze axes=0 = (3, 4) -> sqrt -> output = (3, 4)

**Comment by xadupre** [comment]
The Slice operator changes the dimension, you should get (2, 3, 3). It is not possible to guess the output shape in all cases as slice parameters are given as inputs and could be different for each run. However, in that example, Slice inputs (starts, ends, axes) are constants, so it should be possible to guess the output shape. It works for Gather so I assumed it could work for Slice.
