### ISSUE TITLE
AttentionBlock with for loop exporting a large graph?

### ISSUE THREAD

**Issue by luvwinnie** [onnx/onnx#3597]
# Ask a Question
Is there any way to handle this kind of loop model? The implementation is on this [Colab Link](https://colab.research.google.com/drive/1n6t-mtM8DBBiP8er6jpU_7KxwYBeNJYf?usp=sharing)

### Question
I wish to export a Attention Block that include a loop for decode.
It seems like the LSTMCell can't export to ONNX due to this [issue](https://github.com/pytorch/pytorch/issues/25533). So I used the LSTM work like LSTMCell by taking single time step to inference. How can I handle this kind of model? Is this a problem with the ONNX export function in Pytorch? 

If i export with use_external_data_format=True option, it doesn't save to a single file but instead a lot of separated files. 

Or when exporting a recursive model, the dynamic number of steps inputs should very small ?

### Further information
Model that use for Hybrid CTC/Attention model which including an attention block for OCR or speech recognition.

- Is this issue related to a specific model?  
**Model name**: [Hybrid CTC/Attention Architecture for End-to-End Speech Recognition](https://ieeexplore.ieee.org/document/8068205)
**Model opset**: 11

### Notes
It seems like the following implementation exporting a very large graph can't be export to ONNX and show the following errors.

```
RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.
```

I'm not sure this is a bug/feature issue or not so I open an issue and post also in [stackoverflow](https://stackoverflow.com/questions/68463124/attentionblock-with-for-loop-exporting-a-large-graph)

**Comment by jcwchen** [comment]
Hi @luvwinnie,
Two issues here:
1. The converter (`torch.onnx.export`) does not support LSTMCell conversion.
2. To work around 1), using LSTM instead of LSTMCell for conversion. However, it seems that the converter failed due to the protobuf limitation. Please note that a protobuf python object cannot be larger than 2GB and it's a protobuf limitation. So the solution is just what you did: use_external_data_format=True. Then there will be separated files instead of one single model file. It's expected.

I would suggest you raise a question under PyTorch repo to ask how to convert models with LSTMCell to ONNX properly, or request this op support. Close now since it should not be an ONNX issue. Thanks.

**Comment by luvwinnie** [comment]
@jcwchen Thank you so much, I would like to communicate on pytorch issue for supporting this issue.
