### ISSUE TITLE
Validation/Checker at Operator Granularity

### ISSUE THREAD

**Issue by houseroad** [onnx/onnx#362]
Now, our checker is very general, not able to check whether the attribute value is valid for each operator. For example, we don't want negative pads attribute in Pad op, but our checker is not able to enforce this.

Shall we improve our def-schema and/or checker?

**Comment by houseroad** [comment]
https://github.com/onnx/onnx-caffe2/pull/89, we implement the pad validation in onnx-caffe2. But I think this check should also appear in onnx repo.

**Comment by linkerzhang** [comment]
Shall we add some attribute_parser during operator registration, like typedef std::function<bool(const NodeProto)> AttributeParser, so that in operator declaration, all attributes are able to be checked in detail.

**Comment by ezyang** [comment]
Remember that any validators which are implemented as arbitrary blobs of C++ code cannot be exported to protobuf and would need to be subsequently reimplemented if we ever get a serializable schema format.

**Comment by linkerzhang** [comment]
@ezyang  Thank you! I understand your point.

Given the discussion here is operator-level validation, including specific attribute check. We either need to deliver a "language" (or descriptive rules) to describe the specific checking logic and store this in a protobuf (so that backend could parse and apply for it), or we deliver a "shared" parser codes (together with operator declaration) that backend could refer to. I personally prefer the second one if this discussion (requirement) is the one that we want to support. ONNX as an open standard may be covering the protocol (all protobufs) and a shared library. Thoughts?

**Comment by ezyang** [comment]
Farming it off to a shared library is far far easier, in terms of amount of work we have to do. So it is probably what is going to happen.

I will feel better about it if we try to simultaneously standardize the checking logic in English and not rely on "spec by reference implementation".

**Comment by linkerzhang** [comment]
Agree that "we try to simultaneously standardize the checking logic in English" as well as having implementation in-place. "English version" is used to document the rules while checker implementation is used to enforce these rules.
