### ISSUE TITLE
ONNX to Mxnet

### ISSUE THREAD

**Issue by BenLag2906** [onnx/onnx#3692]
![convertonnx](https://user-images.githubusercontent.com/26578899/131685435-d54d11fc-1049-4b07-83a6-cdd7801a7fd8.jpg)
Hi,

Regarding your issus on onnx,
I am interesting to adapt YoloV5 and I have some onnx file ( extracted from pytorch). Is it possible to export in mxnet format ? Because in Mxnet documentation, we have no solution which runs. Maybe a singular layer is not correctly exported ?
Could you please give a piece of advice.
Thanks in advance.

Ben

**Comment by jcwchen** [comment]
Hi @BenLag2906,
So YoloV5 can be converted to ONNX model by Pytorch-To-ONNX converter (pytorch.onnx.export), right? If so, ONNX itself does support YoloV5 and it should be a question/enhancement for the converter (https://github.com/apache/incubator-mxnet/tree/master/python/mxnet/contrib/onnx/). I saw you opened a discussion there, which is a better place to track this issue. Close the issue here now. Please reopen it if you still have other ONNX questions. Thank you!
