### ISSUE TITLE
Shape inference for Subgraphs

### ISSUE THREAD

**Issue by harishch4** [onnx/onnx#3704]
Does the shape inference work for subgraphs too?

**Comment by gramalingam** [comment]
Can you clarify the question? Inference for a whole model does recursively process subgraphs as well. Is there something unexpected you see?

**Comment by harishch4** [comment]
Okay, my understanding of shape inference is once you're done with infer_shapes(), all the dynamic shapes turn to static shapes(Please correct me if I am wrong).  

I have a model where even after shape inference, I see dynamic shapes in it. I'm attaching the link to the sample code.
https://github.com/harishch4/shape_inference/blob/833445f4e3cf5811f37ce378732a939ae2d1f162/inference.py#L18

**Comment by jcwchen** [comment]
Hi @harishch4,
> shape inference is once you're done with infer_shapes(), all the dynamic shapes turn to static shapes

Not really. Basically, although shape inference propagates shapes from input to output, it will be blocked by some dynamic behaviors. For more details, please check the shape inference document here: https://github.com/onnx/onnx/blob/master/docs/ShapeInference.md Also, for those shapes which can be only known during Runtime (e.g, batch_size), onnx shape inference cannot turn them to static shapes because it does not know the actual input.

However, ONNX does improve shape inference to handle some dynamic scenarios (Reshape node after Shape node) by data propagation, but it only works with the latest opset_version (>=15). I have converted your model from opset_version=9 to opset_version=15 and used onnx.shape_inference(model, data_prop=True). The inferred model is [here](https://github.com/onnx/onnx/files/7146845/inferred_model.zip)  . BTW, you can use netron to visualize the inferred shapes.

**Comment by harishch4** [comment]
Thanks for the clarification.
