### ISSUE TITLE
it is not clear where to get png file in tutorial

### ISSUE THREAD

**Issue by gggh000** [onnx/onnx#3818]
https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb
Run the model in Tensorflow section has code that is no go.

```
...
img = Image.open('assets/two.png').resize((28, 28)).convert('L')
...
img = Image.open('assets/three.png').resize((28, 28)).convert('L')
...

Traceback (most recent call last):
  File "onnx-to-tf.py", line 25, in <module>
    img = Image.open('assets/two.png').resize((28, 28)).convert('L')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")

```

**Comment by jcwchen** [comment]
Those example files are under [tutorials/assets](https://github.com/onnx/tutorials/tree/master/tutorials/assets). Typically the tutorials under [tutorials/](https://github.com/onnx/tutorials/tree/master/tutorials) use assets from there and running those notebooks under tutorials/ directory should work fine.

Close the issue here since it's not an issue in onnx main repo. If you still have other questions related to onnx/tutorials, please open an issue there https://github.com/onnx/tutorials/issues.
