### ISSUE TITLE
I trained a model using libtorch ,how to convert it to onnx?

### ISSUE THREAD

**Issue by henbucuoshanghai** [onnx/onnx#3841]
not using the pytorch in python,I trained my model in libtorch.
tks

**Comment by jcwchen** [comment]
Hi @henbucuoshanghai,
According to the issue [here](https://github.com/pytorch/pytorch/issues/17869), I think currently it is not supported yet. Please track this issue there because it should be a question for the converter. Close here now. Please reopen it if you still have other ONNX questions. Thanks

**Comment by wschin** [comment]
I think we can save the model using `torch::jit::save` as a file and load it using `torch.jit.load` in Python. Then following standard ONNX exporting process should do it.

[This article](https://pytorch.org/tutorials/advanced/cpp_export.html) gives a reverse-direction example (save Python model and load it in C/C++) for step 1. For another step, I guess it'd look like

```
torch_script_model = torch.jit.load('path_to_model')
torch.onnx.export(torch_script_model , (dummy_input_tensor_1, dummy_input_tensor_2), "mine.onnx", verbose=True, input_names=input_names, output_names=output_names)
```
