### ISSUE TITLE
Enable type constraint check in onnx checker

### ISSUE THREAD

**Issue by askhade** [onnx/onnx#3849]
# Feature Request

### System information
ONNX version (you are using): 1.10.2

### Describe the feature
Enable type constraint check for node inputs and outputs in onnx checker. Today a model with unsupported types for an operator does not fail checker. Adding such a check strengthens the checker and enables for thorough validation of the model.

Example: This model should fail checker.
<
  ir_version: 8,
  opset_import: [ "" : 13],
  producer_name: "FunctionProtoTest",
  producer_version: "1.0",
  model_version: 1,
  doc_string: "A test model for model local functions."
>
agraph (float[N] x, bool[N] y) => (float[N] w)
{
    z = Div(x, y)
    w = Identity(z)
}
### Will this influence the current api?
No

### Feature Area
Which area in ONNX does this impact?  (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*): 
onnx checker

**Comment by gramalingam** [comment]
The example above does not capture the issue (as @liqunfu explains in the linked PR). I think a better example would be mixed-precision arithmetic: for example doing addition/subtraction on a float and an int. I suspect that the above example is being rejected because bool is not valid for division anyway. If we replace the "bool" with "int", we may get a proper counterexample.

**Comment by liqunfu** [comment]
updated (https://github.com/onnx/onnx/pull/3902) to cover the input type mismatch case. Type checking has been implemented at: https://github.com/onnx/onnx/blob/65974860e20b311d14b642ce22b5a56b8c176ca5/onnx/defs/schema.cc#L81
