### ISSUE TITLE
Shape inference for Reshape op should catch empty shape error

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#3854]
# Bug Report
Original issue: https://github.com/onnx/onnx/issues/3728

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx import version_converter
model = onnx.load('bertsquad-8.onnx')
model_opset_15 = version_converter.convert_version(model, 15)  # onnx/models
# onnx.save(model_opset_15, "bertsquad-8_opset_15.onnx") # For C++ side to load
inferred_model = onnx.shape_inference.infer_shapes(model_opset_15, True, True)
...
```
- Attach the ONNX model to the issue (where applicable)
https://github.com/onnx/models/blob/master/text/machine_comprehension/bert-squad/model/bertsquad-8.onnx

### Expected behavior
Shape inference should complain Reshape node cannot have empty shape

**Comment by gramalingam** [comment]
I don't think we should disallow an empty shape as the target shape in Reshape. It is a valid shape, and expected for scalars. (However, we do expect the input and output to have same size in a Reshape op. That's a more complex check.) I suspect that the fix for the underlying problem may be elsewhere, eg., in the version-converter etc.

**Comment by jcwchen** [comment]
Thanks @gramalingam. Yes it should not be an issue in shape inference for Reshape. Close this issue.
