### ISSUE TITLE
Converting Pytorch model to .onnx format

### ISSUE THREAD

**Issue by Ninad-Chaudhari** [onnx/onnx#3864]
# Bug Report

### Is the issue related to model conversion?
If the ONNX checker reports issues with this model then this is most probably related to the converter used to convert the original framework model to ONNX. Please create this bug in the appropriate converter's GitHub repo (pytorch, tensorflow-onnx, sklearn-onnx, keras-onnx, onnxmltools) to get the best help.

### Describe the bug
Please describe the bug clearly and concisely

### System information
- OS Platform and Distribution : Windows 10
- ONNX version (*e.g. 1.7*):  1.10.2
- ONNX runtime version : 1.9.0
- Python version: 3.7.12
- Protobuf version: 3.16.0

### Problem
-  I am trying to convert a `Pytorch model` to  `.onnx model`.
- I load the model using pretrained weights in .pt file and use model.eval() 
-  Then I use the following command to export the model in .onnx fomat
```python
    torch.onnx.export(model ,
                      img , 
                      "model_opset11.onnx" , 
                      export_params=True , 
                      do_constant_folding=True,
                      opset_version=11)
``` 
- img is the test image
- The model is successfully converted into .onnx format
- But when I run  my inference session in onnxruntime using the command :
```python
import onnxruntime as rt
sess = rt.InferenceSession("PATH_TO_ONNX_FILE")
```
- Iam getting the following error :
![image](https://user-images.githubusercontent.com/65274398/143572483-b1dbe8ee-aaf4-4383-a418-420bbed53178.png)
- Can anyone please tell me where iam going wrong?
- Here is a link to my .pt and .onnx files : [Link](https://drive.google.com/drive/folders/1809YrximwaDsDe1e6w9qMYyYVesi4QVV?usp=sharing)

**Comment by jcwchen** [comment]
Hi @Ninad-Chaudhari,
Thank you for providing the details. I can repro this error. ONNX shape inference complains that the matrix dimensions for Mul op are incompatible. I guess something wrong happened in the converter (torch.onnx.export) since the converted ONNX model seems wrong. Could you please raise this issue in PyTorch repo and mention ONNX in the title to get the best help from the converter team? Close here. Please reopen it if you still have other ONNX questions. Thanks!
