### ISSUE TITLE
node order is topological sorted?

### ISSUE THREAD

**Issue by germanjke** [onnx/onnx#3865]
Hey!

Want to ask, is `model.graph.node` sorting nodes in model by topological sort? 

It's interesting for complex branchless models like BERT, MASKRCNN, DETR etc

**Comment by jcwchen** [comment]
Yes, ONNX requires models to be topological-sorted. However, you might still be able to run such a model without topological-sorting in some Runtimes like ONNXRuntime(ORT) because ORT will help ONNX models to run topological-sorting before inference.

Reference: https://github.com/onnx/onnx/blob/master/docs/IR.md#graphs

**Comment by jcwchen** [comment]
Close it now since this question seems to be answered. Please reopen it if you still have other ONNX questions. Thanks.
