### ISSUE TITLE
How to Change Input and Output Layer Shape - Squeeze Dimensions

### ISSUE THREAD

**Issue by GotG** [onnx/onnx#3867]
Hello
I have an onnx model converted from pytorch with input shape [1, 2, 3, 448, 1024] and output shape [1, 1, 1, 2, 448, 1024].

I would like to change the input shape to [2, 3, 448, 1024] and the output shape to [1, 2, 448, 1024].

Please let me know how I should do this. Thank you

**Comment by jcwchen** [comment]
Hi @GotG,
IIUC, currently there is no easy utility to squeeze an input in ONNX model because a lot of nodes will need to be updated as well due to different rank. If you do have the original PyTorch model, I would suggest you try to do it in PyTorch-level before conversion since it would be easier, I believe.
