### ISSUE TITLE
Find the corresponding operation of pytorch from onnx node information

### ISSUE THREAD

**Issue by Usernamezhx** [onnx/onnx#3883]
when I convert pytorch model to onnx. it will raise erro. Maybe some unsupported op in onnx. The model is so large that I can't find the corresponding operation in pytorch. Do you have good idea? thanks in advance.

**Comment by jcwchen** [comment]
Hi @Usernamezhx,
What kind of error did you encounter? If there are some unsupported operators, `torch.onnx.export` should show something like:
```
RuntimeError: Exporting the operator XXX to ONNX opset version is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```
If it showed other errors, there might be other issues. You can check all supported ONNX ops in these [files](https://github.com/pytorch/pytorch/tree/master/torch/onnx). Still, this should be a question for the converter (torch.onnx.export). Please raise this issue on PyTorch repo. Close here now. Thanks!

**Comment by Usernamezhx** [comment]
thanks for your reply. I don't think it is a pytorch issue. I convert the pytorch model to onnx. The onnx op graph is slight different from the pytorch model for optimising. When I convert onnx to openvino. it will raise node erro. If I familiar with the model and the model is shallow. I can find the node in pytorch easy. And then I will change the pytorch operation to convert successfully. But  if the model is large and complex. I can't locate the erro node in pytorch model.

**Comment by jcwchen** [comment]
Thanks for the clarification. So the error did not happen during PyTorch to ONNX exporter. Instead, it happened during ONNX to OpenVINO. 

Couple of things for targeting ONNX model issue:
- If PyTorch exporter converts a model successfully without error, the model should be good. If the produced ONNX model is incorrect, it probably needs to be fixed in the exporter side.
- If there is any unsupported PyTorch op for ONNX in a PyTorch model, ideally the exporter should complain. If not, those ops should be under custom domain instead of ONNX domain.
- It is possible that OpenVINO does not support certain kind of ONNX model.

Back to your original question --  PyTorch from ONNX node information.
All conversion information can be found [here](https://github.com/pytorch/pytorch/tree/master/torch/onnx). Take opset9 as an example. Here is the file: https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py. You should be able to figure out the mapping of PyTorch op to ONNX op here. You can further utilize https://netron.app/ to inspect your PyTorch model and ONNX model (ctrl+F can help you quickly search certain node). Besides, onnx.checker and onnx.shape_inference can help you verify your ONNX model. If the conversion (PyTorch to ONNX) looks good and the produced ONNX model passes onnx.checker. Then you can further inspect the Runtime side.

**Comment by Usernamezhx** [comment]
> You can further utilize https://netron.app/ to inspect your PyTorch model and ONNX model (ctrl+F can help you quickly search certain node).
That is a good idea. but the netron support pytorch model not well. I think tensorboard and netron may be the good combination for pytorch and onnx visualization. thanks for your reply.
