### ISSUE TITLE
Un-existing operator

### ISSUE THREAD

**Issue by mikel-brostrom** [onnx/onnx#3891]
Hi! 

I am trying to export my custom PyTorch model to ONNX as following:

```
im = torch.zeros(1, 3, 640, 256).to(device)
model_onnx_path = "torch_model.onnx"
dummy_input = Variable(torch.randn(1, *input_shape).cuda())
output = torch.onnx.export(my_model,
                                       (im, im),
                                       "./model.onnx",
                                       verbose=False),
                                       operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
                                       opset_version=12
```

But onnx crashes with no clear explanation, giving warnings about an un-existing operator. 

`Warning: Checker does not support models with experimental ops: ATen`

Shouldn't this (`operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK`) fix it? Why not? How can I know which torch operator is causing the problems and how can I fix this?

**Comment by jcwchen** [comment]
Hi @mikel-brostrom,
It looks like a converter issue to me since the crash happened during the conversion. I would suggest you raise this issue on the converter repo (torch.onnx.export is in PyTorch) to get the best help from the converter experts. Close this issue here now. Please reopen it if you still have other ONNX questions. Thanks!
