### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'load'

### ISSUE THREAD

**Issue by zhaodadu111** [onnx/onnx#3945]
# Ask a Question

it shows **AttributeError: module 'onnx' has no attribute 'load'** when Im trying to load my model with onnx.load(). how can i solve it

**Comment by zhaodadu111** [comment]
The solution is, I named my .py coda as onnx.py. The problem gone after i renamed it.

**Comment by jcwchen** [comment]
Hi @zhaodadu111,
It seems that you have other onnx module (it can be another onnx.py in the same directory). If you are using official ONNX package from PyPI or built from source, you should see onnx.load as expected. I will close this issue here. Please reopen it if you still have such an issue. Thanks!

**Comment by ZubairKhan001** [comment]
installing onnx version 1.14 solved the issue, 1.12 was installed before
