### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by garymm** [onnx/onnx#3975]
[Python 3.6 has reached end-of-life](https://www.python.org/dev/peps/pep-0494/). We should remove it from all of our CI, release automation, etc.

**Comment by jcwchen** [comment]
Thank you for catching it! I can pick this up. Also while upgrading NumPy from 1.16 to 1.21 in ONNX, I bumped into an issue that NumPy 1.21 does not support Python 3.6 either.

However, after discussing with @askhade, we think it's better for ONNX to still keep Python 3.6 wheel in the upcoming ONNX 1.11 release since it is too close to the release date. Typically ONNX should early announce the deprecation in the previous release. Therefore, I will announce the Python 3.6 deprecation and NumPy upgrade, and submit a PR for it, but it won't be included in the upcoming 1.11. Please let me know if you have any concern with it. Thanks!
