### ISSUE TITLE
pad values of convolution don't seems to be correct 

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx#401]
Hi,
I am facing a problem with model from onnx/models at https://github.com/onnx/models 

The "conv" nodes have "pads" attribute which represents zero values to add before or after each spacial dimension.

So, normally, the output shape should be : 
out_width = (in_width + pad_left + pad_right - kernel_width) / stride_width + 1

The main utility the have the pad_right pad_left is to be sure to have 
(in_width + pad_left + pad_right - kernel_w) % stride == 0.
This gives the following property:
in_width + pad_left + pad_right = (out_width - 1)*stride_width  +  kernel_width
That you can logically verify when apply a convolution with explicit padding value before and after.

I think if onnx wants to be a truly open exchange format, this rule should be guaranty. 

But when I take a look to the model zoo of onnx, I can see that this rule is not respected.

Examples : 
**inception_v1** first convolution:
pad_left = 3
pad_left = 3
kernel_w = 7
stride_width = 2
in_width = 224
-> (in_width + pad_left + pad_right - kernel_w) % stride != 0

**Squeezenet** first convolution:
pad_left = 0
pad_left = 0
kernel_w = 3
stride_width = 2
in_width = 224
-> (in_width + pad_left + pad_right - kernel_w) % stride != 0

Can someone explain to me the onnx position about padding value ? 
And why this occur ?
For me, it is a bug in the front-end which produced the onnx models.

**Comment by bddppq** [comment]
>The main utility the have the pad_right pad_left is to be sure to have
> ```(in_width + pad_left + pad_right - kernel_w) % stride == 0.```

This is not the intention to have both pad_left and pad_right, in fact we had a discussion about whether we should always enforce symmetric paddings, and at the end we decided to keep asymmetric paddings for flexibility.

**Comment by LucasMahieu** [comment]
Keep asymmetric paddings is the right thing to do according to me.

But as I can see in onnx models, paddings before/after are the same.
So in the two cases I cited (for inceptionv1 and squeezenet) it is impossible to know how to make the convolution !
The aime to do an "Open Exchange Foramt" is to be generic.
But in the case where : (in_width + pad_left + pad_right - kernel_w) % stride != 0,
we could not know if we have to take floor or ceil ...  So it is not generic.

And the way to be really generic is to provide into onnx the explicit padding before and after. 
So, if onnx use pad_before and pad_after but are always equal, it is really strange and confusing !! 

Can some ONNX member can take a little bit of his time to think about this ?

**Comment by julien-le-maire** [comment]
Hi,
Having asymmetric padding is a good thing for flexibility, but is also required for interoperability between frameworks:
Even if the layer model of a framework doesn't allow asymmetric padding, in practice the padding implicitly applied are always almost asymmetric: each framework will apply the filters in a way following some internal convention.

For example, in caffe, a 3x3 convolution with stride=2 and padding=1 on a 2x2 image will produce a 1x1 image, but a pooling will produce a 2x2 image. And this is just for caffe: more frameworks will bring different internal conventions about how to apply padding when the filters doesn't fit exactly right with the padding.

But theses ambiguities can be removed by expliciting the padding actually used by the framework: in the case of caffe, the 3x3 convolution with stride=2 and padding=1 have in fact a pad_left=1 and pad_right=0, and the pooling has a pad_left=1 and pad_right=2.

If you want ONNX to be a real exchange format, making possible to evaluate a network the same way in different frameworks, I really think that it is ONNX responsibility to remove ambiguities in the way the network should be evaluated.
Enforcing the formula given by @LucasMahieu will allow the format to actually (and unambiguously) represent the padding that should actually be used, and it does nothing more than that: it does not reduce the expressiveness of the format: you can represent exactly the same network as before.

Otherwise, you won't even guarantee that the size of a tensor produced by a layer is the same across framework, and I'm not even talking about computing the same values: even guaranteeing the right output size will be difficult.
Interoperability is critical for an exchange format, otherwise it's just an export format that can not be used across frameworks.

**Comment by bddppq** [comment]
I think this makes senses since ONNX models are supposed to be generated by frontends (instead of directly constructed by users).
@ezyang @ebarsoum @dzhulgakov

**Comment by dzhulgakov** [comment]
I think current semantics are well-defined - i.e. for conv/pool/etc one applies `out_width = floor((in_width + pad_left + pad_right - kernel_width) / stride_width) + 1` with shift to the left/top.

The reason to go this way instead of enforcing perfect divisibility you described are following:
1) there can be models with varying input size (e.g. superresolution or style transfer). In that case it's impossible to get your formula correct statically
2) majority of frameworks are actually using this approach of not enforcing divisibility and prefer symmetric padding overall
3) we don't have to put additional burden on frontends to do the extra pass and figure out whether the gap is on the left


For the caffe pooling/conv discrepancy it was actually a bug/feature in Caffe :) I'm not aware of other frameworks following this logic. We had a discussion about it earlier and decided to deprecate this behavior. If you want to have historical perspective here's a doc in Caffe2: https://github.com/caffe2/caffe2/blob/master/caffe2/proto/caffe2_legacy.proto#L23 

Indeed in Caffe case one needs to figure out correct padding based on the input size. But it's better to get rid of the legacy behavior instead of carrying it over forever.

**Comment by bddppq** [comment]
@dzhulgakov 
1. doesn't really apply in onnx, all the shape information are pretty static in an onnx model. Once you changed the shape of an input, you very likely need to regenerate the model already.
2. & 3. The burden is either at the frontend side or at the backend side. I mean either one needs to figure out the indivisibility, and IMO frontends normally have better context on what's the desired semantics.

I agree the current specs are well defined, making this change is more to help preventing conversion mistakes in an e2e case (basically it adds an additional check in onnx instead of relying on all backends having the same interpretation). Now that I have written down this, I feel the reason is probably not strong enough to make a post-1.0 breaking change (esp. in conv/pool such core ops) :) .

**Comment by julien-le-maire** [comment]
I agree: as long as the convention used is well-defined, there should be no interoperability problem. In addition keeping the current formula might help having a less static model in the future.

However, the current formula should at least appear on the layers documentation. Currently, the only thing said about the output tensor is: "The output dimensions are functions of the kernel size, stride size, and pad lengths".
I had no idea that this convention was explicitly used in ONNX before you told me, and it would really help people writing backends, visualisation tools, or others to make this explicit.

**Comment by bddppq** [comment]
Fixed in #423 by @LucasMahieu
