### ISSUE TITLE
Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

### ISSUE THREAD

**Issue by Murphy122** [onnx/onnx#4014]
#Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.
### Question
When I converted my yolov3_pytorch（https://github.com/ultralytics/yolov3） to onnx ,I met an error like:
"Unsupported: ONNX export of index_put in opset 9. Please try opset version 11." But in fact, I need Unsample Layer, so I need to use opset 9.Please give me some help,Thanks!

### Further information
Traceback (most recent call last):
  File "pt2onnx.py", line 31, in <module>
    convert_onnx()
  File "pt2onnx.py", line 22, in convert_onnx
    torch.onnx.export(model, dummy_input, onnx_path, 
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/utils.py", line 691, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/utils.py", line 460, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/utils.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 1412, in index_put
    sym_help._onnx_opset_unsupported('index_put', 9, 11)
  File "/root/anaconda3/envs/wz/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 229, in _onnx_opset_unsupported
    raise RuntimeError('Unsupported: ONNX export of {} in '
RuntimeError: Unsupported: ONNX export of index_put in opset 9. Please try opset version 11.

### And there're some codes in my file:

    torch.onnx.export(model, dummy_input, onnx_path, 
                        input_names=['input'], output_names=['output'],
                        opset_version=9, 
                        training=torch.onnx.TrainingMode.EVAL,
                        do_constant_folding=True
                        )
where model is my own model, dummy_input is '''torch.randn(1, 3, 640, 640).to(device)'''

**Comment by jcwchen** [comment]
Hi @Murphy122,
Similar to https://github.com/pytorch/pytorch/issues/46237, https://github.com/onnx/onnx/issues/3057. This should be a question for the converter (PyTorch-ONNX exporter). Typically the solution is using a newer opset_version which supports.

> But in fact, I need Unsample Layer, so I need to use opset 9.Please give me some help

I was curious why you need UpSample to exist in your graph? (I would like to understand the use case of a deprecated op) If you specify opset_version=11 during conversion, is there any conversion error? I am not familiar with the converter, but I guess for opset_version>=10, the exporter will produce Resize op instead of UpSample op because UpSample has been deprecated since opset_version 10 in ONNX.

**Comment by Murphy122** [comment]
Thanks for your reply!
 First, I need to convert pytorch(.pt) -> .onnx ->.caffemodel. Then I'll convert the caffemodel to '.wk', which is  usd on Hi3559V100 desingned by Huawei. I dont't know which one (.caffemodel or .wk) needs the unsample Layer, but I need it indeed. 
And when I set 'opset_version=11', it can be converted successfully, but  the next step(onnx->caffemodel) will go wrong. In anothor project (yolov5   https://github.com/ultralytics/yolov5), I can convert .pt->onnx with 'opset_version=11', and the next steps( .onnx ->.caffemodel->.wk) are also successful. I applied the same settings in yolov3 but it doesn't work.So I am very confused.

Looking forward to your reply!

**Comment by jcwchen** [comment]
Thank you for the details. My first guess would be somehow the conversion (.caffemodel to .wk) does not support opset_version>=10 because Resize was introduced since opset_version 10 to replace deprecated  UpSample from opset_version 9. However, If the conversion for yolov5 with opset_version 11 is successful, it seems to me that the conversion (.caffemodel to .wk) does support opset_version 11. And it should support new Resize op instead of deprecated UpSample op. I would suggest you contact the converter team (.caffemodel to .wk) for assistance and share the error log with them.

Just out of curiosity: is there any way to directly convert .onnx to .wk? Please note that caffe2 has been deprecated for quite a while (see https://caffe2.ai/) so I believe the current support is very limited.
