### ISSUE TITLE
tf2onnx test test_hashtable_lookup failed with onnx 1.11 rc1 and rc2 version.

### ISSUE THREAD

**Issue by fatcat-z** [onnx/onnx#4020]
# Bug Report

### Describe the bug
While running tf2onnx test case BackendTests.test_hashtable_lookup with latest RC2 version, the test case failed with below exception:

======================================================================
ERROR: test_hashtable_lookup (__main__.BackendTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/repos/fatcat-z/tensorflow-onnx/tests/common.py", line 201, in test
    func(self)
  File "/repos/fatcat-z/tensorflow-onnx/tests/common.py", line 235, in test
    func(self)
  File "/repos/fatcat-z/tensorflow-onnx/tests/test_backend.py", line 5232, in test_hashtable_lookup
    self._run_test_case(func, [_OUTPUT], {_INPUT: query}, constant_fold=False, as_session=True)
  File "/repos/fatcat-z/tensorflow-onnx/tests/test_backend.py", line 178, in _run_test_case
    return self.run_test_case(func, feed_dict, [], output_names_with_port, **kwargs)
  File "/repos/fatcat-z/tensorflow-onnx/tests/backend_test_base.py", line 402, in run_test_case
    self.assert_shapes_correct(g, self.config.allow_missing_shapes, not self.config.skip_onnx_checker)
  File "/repos/fatcat-z/tensorflow-onnx/tests/backend_test_base.py", line 301, in assert_shapes_correct
    model_shapes = onnx.shape_inference.infer_shapes(model_proto)
  File "/anaconda3/envs/tfonnxdebug/lib/python3.8/site-packages/onnx/shape_inference.py", line 41, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode, data_prop)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [TypeInferenceError] Cannot infer type and shape for node name hash_table_Lookup/LookupTableFindV2. No opset import for domainai.onnx.ml optype CategoryMapper
This exception was thrown by onnx.checker, but only onnx version is changed in the environment so we should take a look.

### System information
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*):   Ubuntu 20.04.1 LTS
- ONNX version (*e.g. 1.7*):  1.11 RC1 and 1.11 RC2
- Python version:  3.8.5
- GCC/Compiler version (if compiling from source):
- CMake version:
- Protobuf version:  3.14.0
- Visual Studio version (if applicable):

### Reproduction instructions
1. Clone tf2onnx code: https://github.com/onnx/tensorflow-onnx
2. Change the current folder to above local code folder, execute command:

python tests/test_backend.py --opset 12 BackendTests.test_hashtable_lookup

(Test code link: https://github.com/onnx/tensorflow-onnx/blob/872a96b076f5dadd55eb59997297b7b2da85e087/tests/test_backend.py#L5220)

### Expected behavior
This test should pass.

### Notes

Any additional information

**Comment by jcwchen** [comment]
Hi @fatcat-z,
It is a enhanced check from [here](https://github.com/onnx/onnx/blob/fb586d09aed80fa8529a87fdf01a6a98cd3619d5/onnx/shape_inference/implementation.cc#L358) by this [PR ](https://github.com/onnx/onnx/pull/3722). Previously if shape inference bumps into a node has a domain which model.opset_import doesn't have, it will simply skip and continue. Now the enhanced check brought by ONNX 1.11 will throw an error complains the node's domain cannot be found in model.opset_import. Although this enhancement looks fine to me, since it changes current behavior, please let me confirm with the team. Thanks.

P.S. Here is the model (a node is using opset from ai.onnx.ml domain but it does not exist in model.opset_import) to repro: 
[ml_model_without_opset_import.zip](https://github.com/onnx/onnx/files/8077401/ml_model_without_opset_import.zip)

**Comment by jcwchen** [comment]
I have confirmed it with the team: it's an invalid model that it should always have the used domain in model.opset_import. The check is enhanced and it was not caught previously. @fatcat-z Could you please fix the model? Simply add `ai.onnx.ml` into model's opset_import should help. Thanks!
