### ISSUE TITLE
[TypeInferenceError] Inferred elem type differs from existing elem type: (INT64) vs (FLOAT)

### ISSUE THREAD

**Issue by HoangTienDuc** [onnx/onnx#4037]
# Ask a Question

### Question
To make my onnx model run on jetson device, I need to convert the layer that has datatype INT64 to Float32. 
However, changing one layer output will not affect the sequential layers.
How can I convert that layer datatype?

### Further information
```
import onnx_graphsurgeon as gs
import onnx
import numpy as np

model_path = "/ws/model.onnx"

graph = gs.import_onnx(onnx.load(model_path))
for node in graph.nodes:
    if node.name == "squeeze_detected_classes":
        for outp in node.outputs:
            if outp.dtype == np.int64:
                outp.dtype = np.float32

onnx.save(gs.export_onnx(graph), "updated_model.onnx")
model = onnx.load("updated_model.onnx")
print("check update model: ", onnx.checker.check_model(model))
```
**Model opset** 10

### Notes
onnx model was stored at this [location](https://drive.google.com/drive/folders/17xr7_cQCnMOJhttYEgf8kukWC7iZlWGG)

**Comment by jcwchen** [comment]
Hi @HoangTienDuc,
int64 is inferred from your previous nodes with given input so you cannot just modify the output data type. Are you doing this because somehow your Runtime does not support INT64 type for certain operator? If there are only few operators which have unsupported issue, I would say try to add a Cast node to change data type. In you case, I think you can try to add a Cast node after ArgMax node to convert int64 to float32. (ArgMax only produces int64) And then you need to manually change every data type from every node after ArgMax node.
