### ISSUE TITLE
Named Dimensions

### ISSUE THREAD

**Issue by tjingrant** [onnx/onnx#406]
Hi all,

We have had quite a bit of trouble trying to support both NCHW and NHWC format in our ONNX-Tensorflow backend/frontend. Tensorflow is deeply rooted in NHWC format due to some initial implementation decisions and thus we cannot ignore this issue in our backend/frontend.

cf, related discussion: https://github.com/onnx/onnx/issues/369

To reduce complexity in the ONNX spec repository and possible overhead for other backends, we'd like to integrate optional named dimensions to tensors so that data format-sensitive operations like convolution and pooling can behave more intelligently (instead of assuming all the inputs to be in NCHW format as it is now, which introduces transpositions here and there for CPU execution).

Specifically, in this [file](https://github.com/onnx/onnx/blob/211336180e1da62752027a7926ba24b4b7ae5a11/onnx/onnx-ml.proto) I'd like to add an optional enum by the name "DimensionName" which consists of 
```
{ 
DATA_BATCH, 
DATA_CHANNEL, 
DATA_SPATIAL, 
FILTER_IN_CHANNEL, 
FILTER_OUT_CHANNEL, 
FILTER_SPATIAL 
}
```

And in TensorShapeProto.Dimension, I'd like to add an optional parameter `name` with the above-mentioned type. In caffe/torch backend, one simply needs to assert that the names of the dimensions, if present, correspond to the format (N, C, H, W) and throw an error otherwise whereas we can intelligently discern between two cases to better our native support.

If those names are not present, then assume NCHW as the spec dictates at present.

This has the advantage of added confidence for data format correctness as well, say if the user accidentally transposes C and N dimensions, the backend can promptly detect such misplacement.

I'd like to hear from the community before actually submitting an PR.

**Comment by dzhulgakov** [comment]
On adding annotations - it sounds reasonable to me. Maybe call `name` to be `standard_meaning` and instead of enum we can put string there and have some predefined constants in the proto file (for expandable enums it seems more convenient).

My concern though is that then Conv op (and similar ones) effectively changes semantics. Right now the semantics are the input is NxCxD1xD2x... which would not be the case for NHWC. To be sensible I think we need to define annotation on the operator level in one of the ways:
1) Have a separate ConvChannelLast op (ugly)
2) Have an attribute `channel_last` or `channel_axis` on the op that defaults to false/1
3) Have an attribute `data_order` which is not very generic

Then backend implementations can go and complain if the unexpected attribute value is encountered.

Even if we introduce this, I think having input annotations on dimensions is a good idea.


However, I want to better understand which operations are causing trouble for you. With sufficiently smart graph rewriter one should be able to completely propagate layout change through the model with no Transposes left. Recent trend so far has been to adopt NCHW in newer solutions. Maybe we should build sufficiently smart graph transformer.


I think we had extensive discussions on this topic in earlier. @ezyang @Yangqing might have better memort.

**Comment by LucasMahieu** [comment]
You can take a look here, were we had discussions on this topic for onnx-tensorflow.
https://github.com/onnx/onnx-tensorflow/issues/31

**Comment by tjingrant** [comment]
Hi, there are nothing stopping us from going ahead and deal with NCHW using a global flag in fact a patch is actively being worked on that does it. 
However, we are also interested in pushing a minimally intrusive change to the Spec for the most natural/error-proof way of dealing with this issue. Let me walk you through three ideas we had and benefit/drawbacks:
1. I assume your "Graph Rewriter" is some sort of graph optimizer to eliminate transpose. Seems to be a lot of work involved in implementing the infrastructure for such an optimizer and may end up rebuilding a good portion of the wheel ONNX generic optimizer has already built.
2. Global flag to specify default data format. This is our current approach but I fear that this involves a lot of un-checkable assumptions to be made. I.e, my predecessor node has given me the tensor in the correct format. Such assumption, if broken, is terrible to debug/trace. In addition, we also have filters in different data format. The list will grow...
3. Operation-level data-format flag: are we really going to change the input signature of a whole bunch of critical ops like (Conv, Pool) and not support it in the majority of the frameworks? Doesn't sound appealing to other backend developers.
4. Named dimensions. As discussed above, the assumptions made in this approach are easier to check. Data formats are used to describe tensors, not operations/graph, lets put the description close to what it is describing for easiness of checking.

Best wishes,
Tian Jin.

**Comment by dzhulgakov** [comment]
I want to note that current ONNX spec:
1) describes "math" part of computation that can be differently translated to the backend
2) points to axes numerically, not semantically. I.e. Concat op says 'axis=2' instead of 'axes=channels'. Semantical meaning of axes is only local to some ops like Conv.

This means that the global data layout format doesn't make sense in general - it doesn't apply to some ops and also modifies semantics of other ops in unexpected way.

There's also an aspiration of standartizing model representation. We either allow only one axis layout (in which case burden goes only to backends/frontends that support different ones) or we allow multiple axis layouts via flags/separate ops (in which case every backend would need to figure out how to handle all them). Thus I'm leaning to allow only one data layout in the serialized model.

In other words, serialized ONNX model should be represented in a single well-defined layout (which currently happens to be NCHW as more common one).

Given this, it seems that we need to have a set of transforms for changing the layout when importing/exporting to frameworks that have different one (like TF). What would it take to do it:

1) run a path through the graph and annotate edges which are coming from the input and thus have semantical axes assigned to them (i.e. figure out which tensors are 'images'). This can be done by having the information on inputs as you described

2) for tensor transformation ops like Concat or Flatten apply relevant transposition, e.g. replace axis=1 to axis=3

3) for ops like Conv replace them with some fake ConvNHWC that assumes different input layout and can be translated to the backend differently. One option is to add ConvNHWC as a legit op to ONNX but instead of requiring people to implement it directly, rely on the transformation pass to get rid of it for the backends that don't support different layout.

4) if there are some graph initializers that get transposed as the result we can do constant folding.

Those transformations need to happen when importing or exporting the model. On way is to put them in onnx-tf directly.

Another option is to put them in a shared place (onnx repo itself) and effectively have a prepackage tool that can take a model and change its data layout producing another model (with fake ops like ConvNHWC).

As you correctly noted, it's a non-trivial undertaking (maybe still simpler than LLVM :) ) but I feel that's the only valid way to address the issue systematically. Also, we started doing some scaffolding for graph rewrites in https://github.com/onnx/onnx-caffe2/tree/master/optimize-onnx with the goal to put it to the onnx repo eventually. We can consider putting this kind of rewriter on the same infra.

P.S. TF should have built this kind of graph rewriter long ago, but it seems they haven't.

**Comment by Yangqing** [comment]
If I recall correctly, TF has native support for NHWC and NCHW so this should not be an issue. TF also provided functionality for NCHW and NHWC conversions - and as a result you might just want to use those tools. For ONNX, it probably makes sense to stick to one single storage format as the NHWC/NCHW format is more of an implementation choice, and can be addressed via e.g. graph rewriting.

**Comment by tjingrant** [comment]
Thanks for your detailed analysis, I'll talk to my colleagues more on this.

@Yangqing that is almost true but TF only supports NHWC on CPU so we ended up inserting transpositions everywhere (and yes we were trying to leverage NCHW to NHWC conversion utilities in this case) and got quite a few complaints from users who look closely at what we generate. This arguable is a performance hit b/c you will only encounter such a problem on a CPU which has orders of magnitude lower throughput than a GPU and every transpose counts (ps. with a graph rewriter you cannot eliminate the first one, or maybe you can with annotated dimensions).

P.S. @dzhulgakov  TF does have something like that but operates on a lower level, i.e., https://github.com/tensorflow/tensorflow/blob/a0d784bdd31b27e013a7eac58a86ba62e86db299/tensorflow/compiler/xla/service/gpu/convolution_folding.h .

**Comment by LucasMahieu** [comment]
@dzhulgakov @tjingrant What is the solution we can start to implement ?
