### ISSUE TITLE
Sigmoid and relu ONNXRuntimeError

### ISSUE THREAD

**Issue by olegzhos** [onnx/onnx#4092]
Hello everybody! I have the next error when I inference sigmoid and relu operators with dtype=float64(double), opset version=11:

    self._create_inference_session(providers, provider_options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7fd0734ef220>
providers = None, provider_options = None

    def _create_inference_session(self, providers, provider_options):
        # Tensorrt can fall back to CUDA. All others fall back to CPU.
        if 'TensorrtExecutionProvider' in C.get_available_providers():
            self._fallback_providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
        else:
            self._fallback_providers = ['CPUExecutionProvider']
    
        session_options = self._sess_options if self._sess_options else C.get_default_session_options()
        if self._model_path:
            sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
        else:
            sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    
        # initialize the C++ InferenceSession
>       sess.initialize_session(providers or [], provider_options or [])
E       onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Sigmoid(Relu)

I inference these activation functions succesfully when I use dtype=float16 or float32. It looks strange bacause in all the opset versions of these operators according to https://github.com/onnx/onnx/blob/main/docs/Changelog.md Type Constraints: T : tensor(float16), tensor(float), tensor(double). But it seems to me dtype=float64 is not supported in reality

**Comment by jcwchen** [comment]
Hi @olegzhos,
It should be a question for ONNXRuntime. IIUC, the kernels in ONNXRuntime do not exactly follow ONNX spec due to binary size issue. Sometimes some types will only be supported on demand so such a support might be missing.

Still, it seems to me that the double (float64) kernel for Sigmoid-11 is registered from [here](https://github.com/microsoft/onnxruntime/blob/4c3319cb3807b7f3398ddcfd00195a6a4feca362/onnxruntime/core/providers/cpu/cpu_execution_provider.cc#L713). I would suggest you raise this issue in ONNXRuntime and let the Runtime experts take a closer look at it. Thanks.

**Comment by olegzhos** [comment]
jcwchen, thanks, I got you!

**Comment by jcwchen** [comment]
Close it now since it's should be a question for ONNXRuntime. Please reopen it if you still have other ONNX questions. Thanks.
