### ISSUE TITLE
Limited Shape Inference for Concat (or maybe Resize)

### ISSUE THREAD

**Issue by ganler** [onnx/onnx#4093]
# Ask a Question

### Question

I found that shape inference of Concat (or maybe Resize) may not conduct some trivial output shapes in a static graph and returns variable dimensions in the attaced model (simplified and randomized):

![image](https://user-images.githubusercontent.com/38074777/160251973-978592b2-8325-4497-94ea-d39a4e73363c.png)

Attached model: [64.zip](https://github.com/onnx/onnx/files/8356082/64.zip)

I am curisou if this is intended or just a miss/bug of implementation? Thanks!

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*):  shape_inference

- Is this issue related to a specific model?  No.

cc: @jcwchen

**Comment by jcwchen** [comment]
Hi @ganler,
Basic shape inference cannot propagate static shape info from Shape operator. To solve it, ONNX 1.10 brought partial data propagation to handle this case to some extent. Please note that not every operator supports partial data propagation now and the model you provided cannot work because Resize has not supported partial data propagation yet. The supported operators are: Shape, Reshape, Add, Sub, Mul, Cast, Concat, Gather, Slice, Size, Squeeze, UnSqueeze, ConstantOfShape.

Reference: [Proposal - Symbolic Shape Inference And Partial Data Propagation](https://github.com/onnx/onnx/blob/main/docs/proposals/SymbolicShapeInfProposal.md).

**Comment by ganler** [comment]
@jcwchen I see. Thank you for the detailed explanation!
