### ISSUE TITLE
Sequence initializers

### ISSUE THREAD

**Issue by jantonguirao** [onnx/onnx#4105]
# Ask a Question

### Question
Is there a good reason why GraphProto doesn't have a sequence initializers field (like it is the case for tensors and sparse tensors)?

### Further information
- Relevant Area (*e.g. model usage, backend, best practices, converters, shape_inference, version_converter, training, test, operators*):
 GraphProto definitions

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*): NA  
**Model opset** (*e.g. 7*): NA

### Notes

To give you some context, it was spotted during the use of SequenceEmpty with ONNX Runtime: https://github.com/microsoft/onnxruntime/issues/11041

Having support for sequence initializers would enable constant folding.

**Comment by gramalingam** [comment]
On a related note: we should probably reuse proto definitions from https://github.com/onnx/onnx/blob/main/onnx/onnx-data.in.proto for this purpose, since they are intended to represent values of other types like sequence in proto format.

Another related open question is whether the Constant op needs to be extended to capture such sequence constants.

**Comment by liqunfu** [comment]
[add sequence, map, and optional as model graph initializer](https://github.com/onnx/onnx/pull/4148). The PR is in progress:
- need to work with onnxruntime in order to support this feature.
- need more use cases
