### ISSUE TITLE
[build] class member OPTIONAL has conflict with Windows SDK

### ISSUE THREAD

**Issue by JackBoosY** [onnx/onnx#4109]
# Bug Report

### Describe the bug
Build ONNX is okay, but when I use it to build static library, I got the following error logs:
```
F:\vcpkg\installed\x64-windows-static\include\onnx/onnx-data.pb.h(254): error C2059: syntax error: '='
F:\vcpkg\installed\x64-windows-static\include\onnx/onnx-data.pb.h(255): error C2238: unexpected token(s) preceding ';'
F:\vcpkg\installed\x64-windows-static\include\onnx/onnx-data.pb.h(783): error C2059: syntax error: '='
F:\vcpkg\installed\x64-windows-static\include\onnx/onnx-data.pb.h(784): error C2238: unexpected token(s) preceding ';'
```
source code in _onnx-data-pb.h_:
```cpp
...
class ONNX_API SequenceProto :
...
  public:
...
  static constexpr DataType OPTIONAL =
    SequenceProto_DataType_OPTIONAL;
};
...
```

Generated from 
https://github.com/onnx/onnx/blob/cf6dfad9a770e4d6412ea88f1833c8e0118e163d/onnx/onnx-data.proto#L45
or
https://github.com/onnx/onnx/blob/cf6dfad9a770e4d6412ea88f1833c8e0118e163d/onnx/onnx-data.proto3#L45

It has conflict with Windows SDK 10.0.19041.0 in file _minwindef.h_ line 86:
```cpp
#ifndef OPTIONAL
#define OPTIONAL
#endif
```

### System information
- OS Platform and Distribution Windows 10
- ONNX version: 1.10.0
- Python version: 3.7
- GCC/Compiler version (if compiling from source): -
- CMake version: 3.12
- Protobuf version: 3.19.4
- Visual Studio version (if applicable): Visual Studio 2019 community 16.11.11

### Expected behavior
Build success.

### Notes

It can be built as dynamic, no idea why.

**Comment by JackBoosY** [comment]
I have to add the following code before the class declaration:
```cpp
#ifdef OPTIONAL
#undef OPTIONAL
#endif
```
Then it will compile success.

**Comment by jcwchen** [comment]
Hi @JackBoosY,
Similar to https://github.com/protocolbuffers/protobuf/issues/6683, https://github.com/protocolbuffers/protobuf/issues/9256?

It seems to make more sense to me to fix it in the upstream (Protobuf) for preventing similar issues in all the downstream repos.  I guess Protobuf does handle it by the line in [port_def.inc](https://github.com/protocolbuffers/protobuf/blob/791a4355c365bd92720160671a7491be168055cb/src/google/protobuf/port_def.inc#L460) since the produced `onnx-data-pb.h` has included `port_def.inc` and `port_undef.inc`. However, I only see `#undef OPTIONAL` after Protobuf 3.11. May I understand what's the Protobuf version you are using?

**Comment by JackBoosY** [comment]
@jcwchen Thanks for the info, it seems the same issue. I will check later.

**Comment by JackBoosY** [comment]
@jcwchen Yeah this issue was fixed, my protobuf on static build is outdated: 3.11.2.
That's why there is no problem in dynamic build: using 3.19.4.

Thanks and sorry for this mistake.
Jack.
