### ISSUE TITLE
quantized operator supported list?

### ISSUE THREAD

**Issue by lucasjinreal** [onnx/onnx#4147]
quantized operator supported list?

**Comment by avinashsai** [comment]
@jinfagang can I take this up? Please, provide a bit more context.

**Comment by jinfagang** [comment]
Oh, we have onnx standard opset in a readme with version tagging, just wonder if we can also have a dedicated op descriptions on Quantized op supported in onnx? (acutually am not sure if it belongs to onnx standard or if it will be, or if it was belongs to onnxruntime), since all are from same company.

**Comment by avinashsai** [comment]
Thanks for your reply! If possible can you please point to the block in readme?

**Comment by jinfagang** [comment]
Hi, from here https://github.com/onnx/onnx/blob/main/docs/Operators.md, will QLinearConv, QLinearConcat so on will be added into?
