### ISSUE TITLE
Why ONNX OneHot allows negative values which is in range [-depth, depth) ?

### ISSUE THREAD

**Issue by wm2012011492** [onnx/onnx#4154]
### Question
According to my test, ONNX OneHot treats negative value in range [-depth, depth) as value+depth. But the behavior is different with TF or PyTorch.
For example, indices = [0, -1], depth = 3
onnx.one_hot(indices, depth) will generate the outputs [[1, 0, 0], [0, 0, 1]].
tf.one_hot(indices, depth) will generate the outputs [[1, 0, 0], [0, 0, 0]].
Pytorch doesn't allow negative index and will report an error.

**Comment by gramalingam** [comment]
Thanks for pointing this out. I don't know the background, but I guess this behavior is consistent with the behavior in some other ops and the python/numpy convention of using negative values to count backwards. Is there any concern about this specification (the documentation clearly says that these negative values are allowed)? For valid pytorch or TF models, conversion to ONNX shouldn't be a problem since the ONNX behavior is more general. Is there a concern with any specific backend implementations?

**Comment by garymm** [comment]
It's the responsibility of the TF-ONNX converter to make sure tf.one_hot is converted properly. In the case of using a negative index in TF, putting something like MAX_INT in ONNX should result in equivalent behavior. If the converter doesn't do the right thing today, please file a bug in onnx/tensorflow-onnx.

Any remaining problems / issues?
