### ISSUE TITLE
Question about onnx opset

### ISSUE THREAD

**Issue by r2ba7** [onnx/onnx#4214]
# Ask a Question

### Question
So, I was trying to convert tensorflow v2 to onnx then to tensorrt, the problem is my pc *windows 10, python 3..8 tensorflow 2.5.0* cannot convert SSD Mobilnet V2 to onnx unless opset is 11, the problem I want to deploy it on my nano, but when I did it using opset 9 it gave 
`raise  ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported`
, and from what I know, the nano accepts opset 9 .. so why is this problem ? and how to fix it if possible ? I shifted all my work from tensorflow 2.5.0 to tensorflow 1.15

**Comment by jcwchen** [comment]
Hi @r2ba7,
It seems like a question for the converter (tf2onnx). Based on the comment [here](https://github.com/onnx/tensorflow-onnx/issues/1814#issuecomment-1072970472), tf2onnx started to support new_axis_mask since opset 10. I would suggest you raise this issue in tf2onnx repo instead to get better help from the converter experts.

A possible workaround might be still using tf2onnx to covert to opset 11 model and then using onnx.version_converter to convert such an ONNX model from opset 11 to opset 9, but it's possible that it will fail because version_converter is not very good at downgrade.

**Comment by r2ba7** [comment]
@jcwchen So, I guess is this a problem with Mobilenet V2 specifically ?

**Comment by jcwchen** [comment]
I don't have too much context about it -- For some reasons, the converter (tf2onnx) does not support StridedSlice for older opset (opset <= 9). Not sure it is really because some hard limitation like older ONNX opsets cannot handle it, or it just got supported after opset 10 release and opset 9 support is missing. It's better to confirm this question (why tf2onnx cannot handle StrideSlice with opset 9) with the converter folks.
