### ISSUE TITLE
install failed by pip

### ISSUE THREAD

**Issue by yushikmr** [onnx/onnx#4317]
Hi, I tied to install `onnx` by `pip`.
When I used `pip install onnx`, the error occured. 
I can't understand  why the error occured. 

### my enviroment
about OS
```
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```

about python enviroment
```
Python 3.8.5
pip 22.1.2 
```

### error detail

```bash
Collecting onnx
  Using cached onnx-1.12.0.tar.gz (10.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/nf/g9c51mfj7fv4sq4f5wk8rtnc0000gn/T/pip-install-26rs6su8/onnx_f7100bbe097e441e8b741d5365fc9602/setup.py", line 81, in <module>
          assert CMAKE, "Could not find cmake executable!"
      AssertionError: Could not find cmake executable!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by daquexian** [comment]
@jcwchen It is possible to cross-compile arm wheels on x86 github actions machines. I have built and published [onnxsim](https://github.com/daquexian/onnx-simplifier) universal2 wheel (whichs contains both x86 and arm binaries) in this way. I'd like to submit a PR for onnx, too.

**Comment by jcwchen** [comment]
> @jcwchen It is possible to cross-compile arm wheels on x86 github actions machines.

Good question. I don't have much context about this topic, but I guess it's doable. Still, even if it is feasible, it seems to me that ONNX cannot test the built arm wheel in current GitHub Action machines. Personally I slightly prefer to wait until GitHub Action has finally supported M1 machines (ideally it should happen in the near future I hope since M1 becomes more and more popular https://github.com/github/roadmap/issues/528) and then we can test the built ARM64 wheel on Mac.

> I have built and published [onnxsim](https://github.com/daquexian/onnx-simplifier) universal2 wheel (whichs contains both x86 and arm binaries) in this way. I'd like to submit a PR for onnx, too, if it is needed.

That sounds great to me! Thank you for the contribution. For now, I think at least at this moment ONNX can provide universal2 wheel additionally to let users have the option to use prebuilt ONNX wheel for M1 (although we can only test the binaries on x86_64). In the future we can then add ARM wheel support for Mac after GitHub Action has finally supported it.

**Comment by MoravianLion** [comment]
Same issue, but on Windows 11 x64 build 10.0.19045
