### ISSUE TITLE
Can I convert the model format to specific version?

### ISSUE THREAD

**Issue by zihaomu** [onnx/onnx#4460]
Hi team,

The ONNX model has two properties, format and imports. Is there a way to convert the format of the model? Such as from ONNX v3 -> ONNX v7.

**Comment by jcwchen** [comment]
Hi @zihaomu,
Yes, ONNX has a version_converter for this use case. Please see the example [here](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx) and note that not every operator was supported.

**Comment by zihaomu** [comment]
Hi @jcwchen, thanks for your reply. Maybe my description is ambiguous.
The ONNX model has two properties: format (ONNX v4) and imports (ai.onnx v12) if you visiulize ONNX model with Netron. If I understand correctly, `version_converter` can only convert the imports (ai.onnx version), but not the format version.
What I want is to change the version of the format.

**Comment by zihaomu** [comment]
More details:
We try to support ONNX model of float 16 in OpenCV. And we parse ONNX model of float 16 through the protobuf C++ API, which was generated by `https://github.com/onnx/onnx/blob/main/onnx/onnx.proto`. And when the model format version is < 7, I found that protobuf will parse the float 16 tensor into int32_t, because the `tag` value obtained by the protobuf API is 42 (int32_t) instead of 66 or 72 (string or raw_data type). This will cause the model weight to be all 0.

Some example:
[mobilenetv2 with ONNX format V3](https://github.com/zihaomu/zihaomu/files/9316504/mobilenetv2-1.0_fp16.tar.gz) (Fail)
[mobilenetv2 with ONNX format V7](https://github.com/zihaomu/zihaomu/files/9393786/mobilenetv2_fp16_v7.tar.gz) (Yes)

**Comment by jcwchen** [comment]
Thanks for clarification. Currently there is no official utility to convert ONNX model to specified IR version. You can check the detailed IR change [here](https://github.com/onnx/onnx/blob/main/onnx/onnx.proto3#L59-L104).

I just checked the IR changed log, but I think there was no update related to "float16". IIUC, the proto definition about float16 did not change after IR_VERSION 3. In principle, IR updates are usually like proto extension without breaking existing models. Did you see this kind of issue globally between other v3 and v7 ONNX models? Since these 2 models you gave are actually quite different, is it possible that there is other issue instead of different IR versions?

> found that protobuf will parse the float 16 tensor into int32_t, because the tag value obtained by the protobuf API is 42 (int32_t) instead of 66 or 72 (string or raw_data type).

I don't quite follow this -- is it related to ONNX proto? The number for the same member in ONNX proto should be always consistent. Does it mean opencv will need "fixed" IR version to use ONNX? For instance, is it OK to use the latest IR_VERSION 8?

**Comment by zihaomu** [comment]
My previous conclusion was slightly wrong, It only happened when the model format version is **< 6**.

> I don't quite follow this -- is it related to ONNX proto? 

Yes, it is related ONNX proto.

> Did you see this kind of issue globally between other v3 and v6 ONNX models?

I did a series of experiments locally.
Including:
- tinyyolov2-7.onnx IR v5, ai.onnx v7, fail
- yolov4.onnx IR v6, ai.onnx v11, pass.
- yolov5s.onnx IR v7, ai.onnx v12, pass.
- resnet50-v1-12.onnx IR v4, ai.onnx v12, fail.
- [crnn_en.onnx](https://github.com/opencv/opencv_zoo/tree/master/models/text_recognition_crnn) IR v6 pass.
- [PP-OCRv2.onnx](https://github.com/opencv/opencv_zoo/blob/07c98fdf62a55c47b6ebbcfaa71adc7fff206d63/models/text_detection_ppdetect/text_detection_ppdetect_mobile_2022_Aug.onnx) IR v8 pass.
- [PP-OCRv3.onnx](https://github.com/opencv/opencv/files/9336150/model_PP-OCRv3_rec_infer.zip) IR v7 pass.
- ssd_mobilenet_v1_12.onnx IR v4, ai.onnx v10, **Partially correct, some weights are right value and some are 0.**
- [mobilenetv2](https://github.com/zihaomu/zihaomu/files/9316504/mobilenetv2-1.0_fp16.tar.gz) IR v3, fail.
- [mobilenetv2](https://github.com/zihaomu/zihaomu/files/9393786/mobilenetv2_fp16_v7.tar.gz), IR v7, pass.

I'm not sure now if the underlying issue is related to onnx proto or protobuf's c++ API.

**Comment by zihaomu** [comment]
Thanks for your detailed reply.
The [link you provided](https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/float16.py#L61-L73) is very useful for us. 
It looks like OpenCV only support the `raw_data` and not the `int32_data`. I will try to add this support.

**Comment by zihaomu** [comment]
Big thanks, we can load the float 16 models correctly in both cases.
