### ISSUE TITLE
convert_version for MaskRCNN and FasterRCNN causes segmentation fault

### ISSUE THREAD

**Issue by kshpv** [onnx/onnx#4489]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
When I try to `convert_version()` function for Mask RCNN or Faster RCNN models from [ONNX Model Zoo ](https://github.com/onnx/models/tree/main/vision/object_detection_segmentation), the segmentation fault occured.

### System information

- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Windows 10
- ONNX version (*e.g. 1.7*):  1.11
- Python version: 3.9

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
import onnx
from onnx.version_converter import convert_version
model = onnx.load('Faster-RCNN.onnx')
converted_model = convert_version(model, 13)
```
Models:
https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-12.onnx
https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/mask-rcnn/model/MaskRCNN-12.onnx

### Expected behavior
To obtain opset 13 version models

**Comment by jcwchen** [comment]
Hi @kshpv,
I can repro this seg fault issue with ONNX 1.11.0, but it seems resolved in the latest ONNX 1.12.0. I guess this PR helps: https://github.com/onnx/onnx/pull/4079. Note that although version_converter from ONNX 1.12.0 won't cause seg fault with MaskRCNN-12.onnx, it still cannot convert MaskRCNN-12.onnx because of this: https://github.com/onnx/onnx/issues/4101.
