### ISSUE TITLE
Relax the protobuf version requirement.

### ISSUE THREAD

**Issue by xkszltl** [onnx/onnx#4532]
# Bug Report

### Describe the bug

Protobuf now has 3.20.2, so recommend to write <4 instead:
- https://github.com/onnx/onnx/blob/895593af6ac17d4fe2749091659083d3b1246cae/requirements.txt#L2
- https://pypi.org/project/protobuf/3.20.2/

**Comment by jcwchen** [comment]
Hi @xkszltl,
Thank you for catching this! Fresh #4535 should fix this.

**Comment by NikolaBorisov** [comment]
Why <4? I need to use the latest version of protobuf and onnx.

**Comment by jcwchen** [comment]
There is a breaking change in Protobuf 4.21: https://github.com/protocolbuffers/protobuf/issues/10051. For now many Protobuf related project such as ONNX, PyTorch, TensorFlow still use Protobuf 3 to build wheels and it will bump into issues with these wheels with Protobuf 4 due to breaking change. (For example, https://github.com/onnx/onnx/issues/4222).

To workaround, a possible way might be building ONNX from source with Protobuf 4 (protoc>=21. and Python Protobuf >=4.21.) and then the installed onnx should be compatible with the latest Protobuf.

**Comment by snnn** [comment]
>  building ONNX from source with Protobuf 4

Then the user also needs to patch requirements.txt

**Comment by Zahlii** [comment]
With tensorflow 2.12 going to release soon (and allowing proto > 4), is there a way to relax this dependency?
As I am on a M2 chip, all older grpcio/protobuf versions cannot be installed directly, making it impossible for me to run latest tensorflow release candidate and train/export to ONNX.
