### ISSUE TITLE
The numpy_helper.from_array() method doesn't support bfloat16 type.

### ISSUE THREAD

**Issue by fatcat-z** [onnx/onnx#4618]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug

Numpy doesn't support bfloat16 yet. But in some case, like the example code below, it is possible to pass a numpy array whose dtype is bfloat16 into numpy_helper.from_array() method.

In our code, even we have defined a corresponding type for bfloat16 [here](https://github.com/onnx/onnx/blob/604af9cb28f63a6b9924237dcb91530649233db9/onnx/mapping.py#L43), but we still ignore bfloat16 type in our [code](https://github.com/onnx/onnx/blob/604af9cb28f63a6b9924237dcb91530649233db9/onnx/mapping.py#L129). Could anybody help me to understand why we ignore it in above code?

### Reproduction instructions
```
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import tensor_util
from onnx import numpy_helper

x_val = np.array([1, 2, 3])
test_tensor = tf.constant(x_val, dtype=tf.bfloat16)
test_tensor = tf.make_tensor_proto(test_tensor)
np_data = tensor_util.MakeNdarray(test_tensor)

print("Numpy Array dtype: ", np_data.dtype)

result = numpy_helper.from_array(np_data)

```

### Expected behavior
The code should not throw an exception.

**Comment by jcwchen** [comment]
Hi @fatcat-z,
The reason that onnx.mapping does not support bfloat16 for NumPy because native NumPy has not supported bfloat16 yet. See the full supported type list [here](https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases). That's why onnx cannot recognize np.bfloat16.

Based on the code you gave, it seems that TensorFlow somehow can enable NumPy o support bfloat16? IMO, if there is some way that the native NumPy without other dependency can create/manipulate bfloat16 array, we can add np.bfloat16 support in ONNX then.

**Comment by fatcat-z** [comment]
Yes, bfloat16 is not supported by Numpy offically yet. But TensorFlow has [its logic](https://github.com/tensorflow/tensorflow/blob/986affeadea999dcffc9b2271a7a9c4e2e4b8ddc/tensorflow/python/framework/tensor_util.py#L566) to handle such case, I believe we can have our own strategy to handle some existing case like my example.

In above code which ignores bfloat16 type, actually if we don't ignore it, those code will finally return float32 which is an acceptable type for Numpy so that the caller function could move on. 

Since Tensorflow has a solution to handle bfloat32 while converting a Tensor to Numpy array, the scenario in my example code will appear in more and more models even Numpy still cannot support bfloat16 natively. If ONNX doesn't have a solution to handle such case, it will be a potential issue for model conversion work.

**Comment by jcwchen** [comment]
> If ONNX doesn't have a solution to handle such case, it will be a potential issue for model conversion work.

Thank you for the explanation. I understand your concern. However, IIUC, now NumPy can recognize `np.dtype("bfloat16")` only if tensorflow is installed and imported. To keep ONNX compact, it's difficult to bring ONNX, as a neutral package, more build dependency. In principle, ONNX will only support things in official NumPy or Protobuf (from existing [requirements.txt](https://github.com/onnx/onnx/blob/main/requirements.txt)), because we cannot assume every ONNX user has other heavy libraries installed such as TensorFlow or PyTorch.

That's why I was wondering if there is a way to let native NumPy without any other dependency recognize np.bfloat16 somehow. If not, for now, I think a proper workaround might be having a special case handle for `onnx.numpy_helper.from_array` use (and other NumPy relevant functions) in tf2onnx if the type is np.bfloat16. Please let me know if you have other concern. Thanks!

**Comment by fatcat-z** [comment]
Sure, tf2onnx has added some logic to handle this case. I understand your thoughts about only supporting things in official Numpy, and it is reasonable. My suggestion is just something nice to have, just a reminder.
