### ISSUE TITLE
`onnx.checker.check_model` Failed to Identify Shape Incorrectness

### ISSUE THREAD

**Issue by leimao** [onnx/onnx#4705]
# Bug Report

### Is the issue related to model conversion?
No

### Describe the bug
`onnx.checker.check_model` failed to identify the shape incorrectness.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/17606112/207677509-4cc2d94f-5f7b-434f-b2e9-9b25b8b1ee00.png">

### System information

- OS Platform and Distribution: Ubuntu 22.04 
- ONNX version:  1.13.0
- Python version: 3.10.6

### Reproduction instructions

[conv_bug.onnx.zip](https://github.com/onnx/onnx/files/10230660/conv_bug.onnx.zip)

### Expected behavior
Expect throwing exceptions.

### Notes
N/A

**Comment by leimao** [comment]
It turns out that I accidentally used stride `[1,1,1,1]` instead of `[1,1]` for the Conv and somehow the checker did not find both problems. If I used stride `[1,1]`, the checker can find the output channel incorrectness. 
It is still a bug though.

**Comment by jcwchen** [comment]
Hi @leimao,
Thank you for providing the model to repro. I think such an incorrect strides originally can be found in the strict shape inference. (e.g., onnx.shape_inference.infer_shapes(model, strict_mode=True), onnx.checker.check_model(model, full_check=True)) It shows: `InferenceError: [ShapeInferenceError] Shape inference error(s): (op_type:Conv): [ShapeInferenceError] Attribute strides has incorrect size`.

**Comment by leimao** [comment]
Thanks @jcwchen. I did not know we have the argument `strict_mode` for `onnx.shape_inference.infer_shapes` and `full_check` for `onnx.checker.check_model`. They must be `False` (the default value?) when I was running my program. May I ask why they are not enabled by default? If a thorough checking does not take too much time, they should be enabled by default in my opinion. In addition, do we have docs/docstrings about those arguments?

**Comment by jcwchen** [comment]
> May I ask why they are not enabled by default? If a thorough checking does not take too much time, they should be enabled by default in my opinion

Good question. strict_mode was introduced due to two reasons:
1. ONNX shape inference was much improved in ONNX 1.8 and it broke quite a few old models. Sometimes although these models cannot pass ONNX shape inference, they can still run by ONNX backend (like ONNX Runtime). Definitely this is not the case for your example, because this model cannot be run by runtime anyway (strides has incorrect size).
2. Some ONNX shape inference users rely on shape_inference to get inferred shapes and they are fine if the shape inference stops at certain node (encounter an error). Also it is helpful for debugging, since users can still check previous inferred shapes.

Especially because of the 1. reason, to keep compatibility, strict_mode was set as false by default and so newer ONNX shape inference won't break some old models. For users who care about these shape inference errors, they can further enable strict_mode in onnx.shape_inference or full_check in onnx.checker. 

> In addition, do we have docs/docstrings about those arguments?

Sorry that currently there is no documents for these arguments, but you can find the comments for arguments here: https://github.com/onnx/onnx/blob/main/onnx/shape_inference.py#L20-L33. Please let me know if you have question about these arguments.

**Comment by leimao** [comment]
@jcwchen Thank you very much for the clarifications.

**Comment by leimao** [comment]
@jcwchen So do you still think it is a bug? If it is not, I can close it.

**Comment by jcwchen** [comment]
I think it is expected in the current stage. Ideally in the future ONNX should enable strict_mode by default (perhaps when major version jump) to catch shape inference errors in advance and prevent confusions. Feel free to close it if you don't have any other questions. Thank you!

**Comment by leimao** [comment]
@jcwchen Sounds good. Thank you. Closing the issue.
