### ISSUE TITLE
version number in master should be > than release branches

### ISSUE THREAD

**Issue by jesterhazy** [onnx/onnx#478]
if you clone onnx:master and pip install from source, then pip install any python package that depends on onnx, pip will replace installed version of onnx with (older) release version.

version number in master should be > release version to avoid this (perhaps with .devN label)

**Comment by bddppq** [comment]
I think pip install be default won't overwrite your previous installation, unless you add `-U` flag, which indicates you wanna update. This means we just need to keep the master version equal to the release version (It's should be always the case since merge release branches should be merged back to master The current situation that master version `<` released version should be a mistake in last release.) We are going to make a patch release today (https://github.com/onnx/onnx/issues/444) and will fix this issue.

**Comment by jesterhazy** [comment]
👍
