### ISSUE TITLE
ONNX design/larger feature process

### ISSUE THREAD

**Issue by ghost** [onnx/onnx#48]
As seen in the discussion in #9, I think there is some ambiguity when it comes to larger design/feature discussions and how to proceed. Eg:
> We've definitely discussed about functions and subgraphs in the design discussions.

...

> It was discussed quite a bit in our design meetings, and we even had some preliminary design. In the end, we decided to release only the parts that we felt safe and essential to get things started.

Is the plan to continue these design discussions in a public forum now that the project is public? My $0.02 is that we can instead do something like the [Kubernetes proposal doc](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#1-is-the-feature-wanted-make-a-design-doc-or-sketch-pr) or the [Rust language RFC](https://github.com/rust-lang/rfcs) process for larger features/IR design decisions.

Does a proposal doc PR as a concrete starting point sound like a reasonable idea for larger ideas/discussions for ONNX?

**Comment by ezyang** [comment]
The current plan is to continue using the issue tracker to track proposed changes, until we start needing to tackle features that are sufficiently large and complex to need an actual proposal document. (This may indeed be sooner rather than later, since RNN is a priority and we'll be coming out with a proposal in the near future.)

**Comment by prasanthpul** [comment]
We now have SIGs and WGs
