### ISSUE TITLE
Add function support in onnx

### ISSUE THREAD

**Issue by linkerzhang** [onnx/onnx#481]
Proposal as below, feel free to share your comments please. Thank you very much! @dzhulgakov @yuanbyu @ezyang @bddppq @ebarsoum @gramalingam 

You may refer to the whole proto file https://github.com/linkerzhang/onnx/blob/kezhan/add_function_to_onnx/onnx/onnx.in.proto.

```
// A named attribute containing either singular float, integer, string
// and tensor values, or repeated float, integer, string and tensor values.
// An AttributeProto MUST contain the name field, and *only one* of the
// following content fields, effectively enforcing a C/C++ union equivalent.
message AttributeProto {

  // Note: this enum is structurally identical to the OpSchema::AttrType
  // enum defined in schema.h.  If you rev one, you likely need to rev the other.
  enum AttributeType {
    UNDEFINED = 0;
    FLOAT = 1;
    INT = 2;
    STRING = 3;
    TENSOR = 4;
    GRAPH = 5;

    FLOATS = 6;
    INTS = 7;
    STRINGS = 8;
    TENSORS = 9;
    GRAPHS = 10;
  }

  // The name field MUST be present for this version of the IR.
  optional string name = 1;           // namespace Attribute
  optional bool is_ref = 21;          // if it's true, it means it's referring parent node's (referring to a function) attribute value.
  optional string ref_attr_name = 22; // if is_ref is true, ref_attr_name is the attribute name in parent function.

  // A human-readable documentation for this attribute. Markdown is allowed.
  optional string doc_string = 13;

  // The type field MUST be present for this version of the IR.
  // For 0.0.1 versions of the IR, this field was not defined, and
  // implementations needed to use has_field hueristics to determine
  // which value field was in use.  For IR_VERSION 0.0.2 or later, this
  // field MUST be set and match the f|i|s|t|... field in use.  This
  // change was made to accomodate proto3 implementations.
  optional AttributeType type = 20;   // discriminator that indicates which field below is in use

  // Exactly ONE of the following fields must be present for this version of the IR
  optional float f = 2;               // float
  optional int64 i = 3;               // int
  optional bytes s = 4;               // UTF-8 string
  optional TensorProto t = 5;         // tensor value
  optional GraphProto g = 6;          // graph
  // Do not use field below, it's deprecated.
  // optional ValueProto v = 12;         // value - subsumes everything but graph

  repeated float floats = 7;          // list of floats
  repeated int64 ints = 8;            // list of ints
  repeated bytes strings = 9;         // list of UTF-8 strings
  repeated TensorProto tensors = 10;  // list of tensors
  repeated GraphProto graphs = 11;    // list of graph
}

// Defines a function parameter.
message ParameterDeclProto {
  // The name of this parameter. Must be present.
  optional string name = 1;

  // The type/shape of this parameter.
  optional TypeProto type = 2; 

  // A human-readable doc string for this parameter. 
  optional string doc_string = 3; 
} 

// Defines a function attribute declaration.
message FuncAttrDeclProto {
  // The attribute name of the function. Must be present.
  optional string name = 1;

  // The type of this attribute.
  optional AttributeProto.AttributeType type = 2;
} 

// Defines a custom implementation of a function. 
message FunctionImplProto { 
  // The domain of this function implementation.
  optional string function_impl_domain = 1; 

  // The version of this implementation.
  optional int64 function_impl_version = 2; 

  // The URI of the executable. A runtime uses <domain> and <version> to
  // determine whether Compilation data itself saved in a separate file. 
  optional string executable_uri = 3;

  // The actual executable for this function implementation.
  optional bytes executable = 4;
} 
 
// Defines a function.
// We specify a function as a subgraph composed of ONNX ops. Any runtime can
// have a custom implementation optimized for the runtime. A runtime can use
// a matching custom implementation if there is one, or falls back to execute
// the subgraph.
// NOTE: We don't support recursive function.
message FunctionDefProto { 
  // The name of the function. MUST be present for this version of the IR. 
  optional string name = 1;
  
  // The domain of the function.
  optional string domain = 2;

  // The version of the function.
  optional int64 version = 3;

  // The input parameters of the function. 
  repeated ParameterDeclProto input_params = 4; 

  // The output parameters of the function. 
  repeated ParameterDeclProto output_params = 5;

  // The body of the function. 
  repeated NodeProto node = 6;

  // The function attributes' declaration.
  repeated FuncAttrDeclProto attr = 7;

  // An optional human-readable documentation for this function in the graph. 
  // MAY contain Markdown markup that conforms to http://commonmark.org/. 
  optional string doc_string = 8;

  // Custom implementations of this function. This enables runtime specific
  // implementations.
  repeated FunctionImplProto impl = 9;
 
  reserved 100 to 200; // for future extensions. 
}
```

**Comment by linkerzhang** [comment]
Function, as a subgraph (template), should be used in subgraph ops, say, loop (we're defining it). 
Function should also be used to resolve the problem that "Graph" is being an attribute type.

**Comment by linkerzhang** [comment]
You may notice that two more fields are added in AttributeProto to cover the case that an attribute is referring to a function attribute declaration (the data stored in parent node's AttributeProto actually).
 optional bool is_ref = 21;          // if it's true, it means it's referring parent node's (referring to a function) attribute value.
  optional string ref_attr_name = 22; // if is_ref is true, ref_attr_name is the attribute name in parent function.

After more discussion with @yuanbyu  the bool is_ref looks to be redundant and having ref_attr_name is good enough, since if the ref_attr_name is empty, we can know that the attribute contains real data not a reference without checking another separate flag.

**Comment by jamesr66a** [comment]
Hi @linkerzhang, could you elaborate on what problem you're solving with this proposal, and what an example use case is?

**Comment by ebarsoumMS** [comment]
@jamesr66a here some of the issue that this proposal solve:
1. HW acceleration, can map a single function to a HW implementation. This help us to design clean ONNX instead of fuse OPs manually.
2. Concise ONNX model.
3. Flexible RNN using Loop + Function (for RNN Cell).

**Comment by gramalingam** [comment]
Expanding on Emad's response above:

Ideally, it would be nice if RNN, LSTM, GRU can all be expressed as instances of the same loop/recurrence with a different body/cell: say, as Recurrence<RNN-Cell>, Recurrence<LSTM-Cell>, and Recurrence<GRU-Cell>(where Recurrence could be a Loop or a more specialized operator).

Each of RNN-Cell, LSTM-Cell, and GRU-Cell can, in turn, be defined in terms of more primitive operations (as in their corresponding equations), which can be represented as as graphs, say RNN-Cell-Graph, LSTM-Cell-Graph, and GRU-Cell-Graph.

Without named functions, we will end up duplicating RNN-Cell-Graph for every RNN (loss of a concise representation in the model), or ending up adding an operator called RNN (expanding the set of operators).

So, the proposal allows us to:
(a) Accommodate newer recurrent layers (for example),
(b) Without requiring all implementations to directly implement the new layer,
(c) While keeping models compact

**Comment by jamesr66a** [comment]
I agree that we should have some sort of abstraction to allow for common re-use of, for example, cells. But this proposal seems to also be trying to serve double-duty as replacing--for control flow ops--the graph body *itself* with the Function abstraction. If I understand correctly, this proposal provides no provision for accessing implicitly live values in an enclosing scope.  Note the below:

`
bool foobar = false;
int baz = 3;
for (int i=0; i<100; ++i) {
  bool abcd = !foobar; // Note I can access this due to lexical scoping
  if (baz < 10) {
    baz++;
  }
}
`

Note that we have well-defined semantics for lexical scoping in this code example and in the control flow proposal. This is possible because the blocks are defined within the context of their parent scope(s). Note that if we were to convert all of these control structure bodies to functions, we would need to explicitly mark all live-in and live-out values:

`
bool foobar = false;
int baz = 3;
for (int i=0; i<100; ++i) baz = for_loop_body(i, foobar, baz)

int conditional_body(baz) {
  return baz+1;
}

int for_loop_body(int i, bool foobar, int baz) {
  bool abcd = !foobar;
  return conditional_body(baz);
}
`

Our proposal is that a function can be *invoked* from a lexically-scoped subgraph, but the subgraph itself should not be conflated with this function abstraction. To do otherwise would unnecessarily complicate serialized models with (sometimes nested!) control structures.

Concretely, let's take a look at LSTM cells, in pseudo-deep-learning-C:

`
Tensor iW_f, iW_i, iW_o, iW_c;
Tensor hW_f, hW_i, hW_o, hW_g;
Tensor b_f, b_i, b_o, b_g

Tensor hidden_state_carried_dep;
Tensor cell_state_carried_dep;

vector<Tensor> y;
vector<Tensor> x;

// Assume * is overloaded as matmul, . is overloaded as Hadamard product
for (int i=0; i<seqlen; ++i) {
  Tensor f_t = sigmoid(iW_f * x[t] + hW_f * hidden_state_carried_dep + b_f);
  Tensor i_t = sigmoid(iW_i * x[t] + hW_i * hidden_state_carried_dep + b_i);
  Tensor o_t = sigmoid(iW_o * x[t] + hW_o * hidden_state_carried_dep + b_o);
  Tensor c_t = f_t . cell_state_carried_dep + i_t . sigmoid(iW_c*x[t] + hW_c * hidden_state_carried_dep + b_c);
  Tensor h_t = o_t . sigmoid(c_t);
  hidden_state_carried_dep = h_t;
  cell_state_carried_dep = c_t;
  y[i] = h_t;
}
`

The inputs to this code block are as follows: iW_f, iW_i, iW_o, iW_c, hW_f, hW_i, hW_o, hW_g, b_f, b_i, b_o, b_g, x.
The loop carried deps (count as both input and output) are: hidden_state_carried_dep, cell_state_carried_dep.
The outputs are: y.

So now I have a function signature that looks like:

`
y, hidden_state_carried_dep, cell_state_carried_dep = for_loop_body(iW_f, iW_i, iW_o, iW_c, hW_f, hW_i, hW_o, hW_g, b_f, b_i, b_o, b_g, x, hidden_state_carried_dep, cell_state_carried_dep)
`

One could argue you could fuse together the weight and bias matrices, but this has performance implications depending on backend and batch size. I think it's another interesting discussion about optimization opportunities with either representation and the trade-offs between expressibility in the IR vs expressibility in the frontend and semantics provided to optimizers. But ignoring the implications let's reformulate this as fused:

`
y, hidden_state_carried_deps, cell_state_carried_dep = for_loop_body(iW, hW, b, x, hidden_state_carried_dep, cell_state_carried_dep)
`

But this still becomes unnecessarily cumbersome when you want to compose this into a broader loop body, for example implementing Multiplicative Integration LSTM (https://arxiv.org/pdf/1606.06630.pdf). Say we have a standard LSTM cell with the following signature (affine layers factored out due to the nature of MI-lstm):

`y, hidden_state_carried_deps, cell_state_carried_dep = LSTMCell(gates, hidden_state_carried_dep, cell_state_carried_dep)
`

Then we write:

`
Tensor iW_f, iW_i, iW_o, iW_c;
Tensor hW_f, hW_i, hW_o, hW_c;
Tensor b_f, b_i, b_o, b_c;
Tensor alpha, beta_h, beta_i, b;

Tensor hidden_state_carried_dep;
Tensor cell_state_carried_dep;

vector<Tensor> y;
vector<Tensor> x;

// Assume * is overloaded as matmul, . is overloaded as Hadamard product
for (int i=0; i<seqlen; ++i) {
  Tensor affine_{f,i,o,c} = iW_{f,i,o,c} * x[t] + hW_{f,i,o,c} * hidden_state_carried_dep + b_{f,i,o,c};
  Tensor gates_{f,i,o,c} = x . alpha + beta_h . affine{f,i,o,c} + x . beta_i + b;
  y, hidden_state_carried_deps, cell_state_carried_dep = LSTMCell(gates, hidden_state_carried_dep, cell_state_carried_dep)
}
`

This is a perfectly reasonable representation in which a Funciton is *invoked* from a control structure body, whereas the body itself is a block, with access to values in the parent scope.

Equivalently, to explicitly capture live-in and live-out values in a function definition:

`
Tensor iW_f, iW_i, iW_o, iW_c;
Tensor hW_f, hW_i, hW_o, hW_c;
Tensor b_f, b_i, b_o, b_c;
Tensor alpha, beta_h, beta_i, b;

Tensor hidden_state_carried_dep;
Tensor cell_state_carried_dep;

vector<Tensor> y;
vector<Tensor> x;

for_loop_body(i_W, h_W, b, alpha, beta_h, beta_i, b) -> (y, hidden_state_carried_deps, cell_state_carried_deps) {
  Tensor affine_{f,i,o,c} = iW_{f,i,o,c} * x[t] + hW_{f,i,o,c} * hidden_state_carried_dep + b_{f,i,o,c};
  Tensor gates_{f,i,o,c} = x . alpha + beta_h . affine{f,i,o,c} + x . beta_i + b;
  y, hidden_state_carried_deps, cell_state_carried_dep = LSTMCell(gates, hidden_state_carried_dep, cell_state_carried_dep)
}
// Assume * is overloaded as matmul, . is overloaded as Hadamard product
for (int i=0; i<seqlen; ++i) for_loop_body(i_W, h_W, b, alpha, beta_h, beta_i, b)
`

Note that in all of these cases, having a well-defined semantics of lexical scope makes it so that a backend or any tools that wish to expressly enumerate the live-in values to a block can do so via analyzing the graph. The trade-off for strictly using Functions is increased complexity and size in the serialized model to simply represent information that is available implicitly.

This comment has been a summary of the considerations I've been making in choosing lexical scoping for the control flow ops, and assuming this Function proposal does not support behavior akin to lambdas, I argue that we should keep the Graph attribute as-is, or at least define a "block" semantics, distinct from the Function proposal.

**Comment by gramalingam** [comment]
I was just presenting the motivation for functions. 

Whether the loop-body should be a graph or a function or either is an orthogonal design decision. Having a graph or a function is roughly equivalent (semantically), and I am fine with using graphs to represent a loop-body.

**Comment by linkerzhang** [comment]
Following the new process, I'm adding a wiki https://github.com/onnx/onnx/wiki/Proposal----Adding-Function-into-ONNX for discussion please.

**Comment by RanACohen** [comment]
@linkerzhang can you add a link from that Wiki to this discussion?

**Comment by RanACohen** [comment]
I like the : [ref attribute change](https://github.com/linkerzhang/onnx/blob/kezhan/add_function/onnx/onnx.in.proto#L105)
But I do not understand the motivation of [adding function definition](https://github.com/linkerzhang/onnx/blob/kezhan/add_function/onnx/onnx.in.proto#L500). 

This whole feature (which as HW Vendor rep I like) can be implemented using graph definition which already exists + the ability to share attributes. why do we need to over-complicate the protobuf?
