### ISSUE TITLE
Activation of merge queue in onnx/onnx?

### ISSUE THREAD

**Issue by andife** [onnx/onnx#4884]
Hi, 
maybe we should activate merge queue (https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) in this repo here?

**Comment by jcwchen** [comment]
Thanks @andife. It seems useful. cc @prasanthpul

**Comment by prasanthpul** [comment]
enabled

**Comment by jcwchen** [comment]
Currently the merge queue is not working properly. See https://github.com/onnx/onnx/pull/4851#issuecomment-1428867484. We need to make some changes in our pipeline to accommodate it. Not sure whether DCO can be used in the merge queue though. I am confirming it with the GitHub team. If no, we might need to disable it for now. I will keep you in the loop.

**Comment by jcwchen** [comment]
With this PR: https://github.com/onnx/onnx/pull/4890, pipelines are now running, but I still cannot find a way to make DCO run in the merge queue... Here is the related issue: https://github.com/dcoapp/app/issues/199. I also asked [here](https://github.com/orgs/community/discussions/46757#discussioncomment-4964805).

Since it is really blocking us merging our PRs, I think for now we should disable it. @prasanthpul could you please disable merge-queue for now? Once the DCO issue has been resolved, we can re-enable it then. Thanks!

**Comment by jcwchen** [comment]
With the workaround: https://github.com/onnx/onnx/pull/5398, now merge queue has finally worked in onnx repo! TODO item has been tracked by: https://github.com/onnx/onnx/issues/5399. Close this issue as completed.
