### ISSUE TITLE
connect two onnx models as one

### ISSUE THREAD

**Issue by TMullerSG** [onnx/onnx#5006]
Hi, supposely i have two onnx models and i want to combine both of them to get the mean of the two output, how should i do?
 for example:
x=onnx.load("x.onnx")
y=onnx.load("y.onnx")

i want to have one onnx model which give the same result as x+y

thanks for any help

**Comment by jbachurski** [comment]
There are some utilities in `onnx.compose` in this repository that could help, like `onnx.compose.merge_models` - you'd need to prepare a third model which computes a mean of its inputs and then that could work.

I can also recommend a solution using [Spox](https://github.com/Quantco/spox). First you'll have to find all the input/output types of the models. Then you can use `spox.inline` to put the two models in the same model. With `spox.argument` you can create placeholder model inputs that you can forward the composed model inputs with. Then you can compute a mean (like arithmetic mean).

```py
import numpy as np
import onnx
import onnx.compose
import spox.opset.ai.onnx.v17 as op
from spox import argument, build, inline, Tensor

# I'll assume your model inputs are some tensors a, b of these types
# You can adapt this to your case
a = argument(Tensor(int, (256, 256, 3)))
b = argument(Tensor(np.float32, ('N',)))

# Load the models
model1 = onnx.load("out/model1.onnx")
model2 = onnx.load("out/model2.onnx")

# Inline the models and forward the arguments
# Also unwrap all the results - here assume there's just one
(r1,) = inline(model1)(a, b).values()
(r2,) = inline(model2)(a, b).values()

# Take the arithmetic mean
# This assumes the outputs are float32 (as op.constant(value_float=...) is)
r = op.div(op.add(r1, r2), op.constant(value_float=2))  

# Build the composed model with given model inputs and outputs (with names)
model = build({'first': a, 'second': b}, {'result': r})
# onnx.save(model, ...)
```

I hope you can work out a solution based on this, but let me know if I can help further (or if you have more details on the models, like what input/output types they have).

**Comment by praneeth5222** [comment]
Hi @jbachurski 
Can you also provide a sample example to combine two onnx models sequentially (i.e. output of the first model is passed as an input to the 2nd) which are of different domain (one is a sklearn onnx model and the other is a tensorflow one)

**Comment by jbachurski** [comment]
What do you mean of different domain? Spox should attempt to do version conversion to move the models to a common opset version, you can also try to use `onnx.version_converter` yourself to do that. Is there a specific exception you are getting?

**Comment by praneeth5222** [comment]
@justinchuby 
Thanks once again for your suggestion. I'm kind of new to ONNX and SPOX and I'm struggling with the in-line call
Do you mind providing me a quick sample to demonstrate what you have mentioned earlier to combine two ONNX models sequentially?
So my input to model 1 is a data frame containing 8 columns that are of type String. I guess signature will be something like ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8']. I'm unable to provide an input tensor that matches this requirement

I am trying to provide something like this - 
`(r1,) = inline(model_1)([(x, argument(Tensor(str, (None,1)))) for x in columns]).values()`
but I get the following error
`TypeError: inline callback missing required arguments: {'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8'}, signature ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8'] (defaults ['shape_tensor']) -> ['variable'].`

Model 1 output (and also model 2 input) will be 1400 columns of type float 64
I'm doing inline something like this - `(r2,) = inline(model_2)(argument(Tensor(float, (None,1400)))).values()`

Can you suggest me how do I fix inline for model 1 and how should I arrange them sequentially after I get the inline models?

**Comment by jbachurski** [comment]
Something like this should work, but I haven't  tested it:

```py
from spox import argument, Tensor, inline, build

column_names = ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8']

# Create a mapping of all the input columns, from strings to spox Vars (variables)
inputs = {name: argument(Tensor(str, (None,))) for name in column_names}

# Load model_1 and model_2
...

# Pass columns (inputs) by name with keyword arguments
(pred,) = inline(model_1)(**inputs).values()

# pred is a new Var that represents the output of model_1 
# - you want to pass it to model_2 now with another inline

# Pass pred as the sole argument to model2
(output,) = inline(model_2)(pred).values()

# output is a Var representing the output of model2 given model1's output

combined = build(inputs, {'output': output})
```

---

This attempt: 

```py
inline(model_1)([(x, argument(Tensor(str, (None,1)))) for x in columns]).values()
``` 
doesn't work because you are passing a list of pairs `tuple[str, Var]`. The format is either with positional or keyword arguments (`*args: Var` or `**kwargs: Var` - the keyword names are the column names). The above example passes by keyword arguments by doing `**inputs` on a `dict[str, Var]`.
I also wanted to add that `Tensor(str, (None, 1))` is a type of matrix `str[?][1]` where the second dimension is 1, not a vector `str[?]`. I assume you meant `Tensor(str, (None,))` here, which is a vector rather than a matrix, but you can correct it (Spox should raise if you use the wrong type).

This error:
```py
TypeError: inline callback missing required arguments: {'col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8'}, signature ['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8'] (defaults ['shape_tensor']) -> ['variable'].
```
indicates the model expected arguments named `['col1', 'col2', 'col3', 'col4', 'col5', 'col6', 'col7', 'col8']`, and you haven't passed any of them (there's also a message that the output is called `'variable'`). I assume you must have used a call like `inline(model_1)()` for that exact error to be raised, unless there's a bug in the message.

> Model 1 output (and also model 2 input) will be 1400 columns of type float 64
I'm doing inline something like this - `(r2,) = inline(model_2)(argument(Tensor(float, (None,1400)))).values()`

I will note that the type `Tensor(float, (None, 1400))` represents a matrix of float64 `?` by `1400`, so `float64[?][1400]`. I assume that is what you meant to say, rather than 1400 separate columns?

**Comment by praneeth5222** [comment]
Thank you so much @jbachurski for your detailed explanation. I have followed your instructions and I'm getting this error in the final combining step - 
`ValidationError: Graph must be in single static assignment (SSA) form, however 'col1' has been used as output names multiple times.`
I also got a warning saying - 
`Warning: opset domain 'ai.onnx.ml' is not supported.`

Can you advice me how do i proceed forward?

**Comment by praneeth5222** [comment]
@jbachurski 
Thank you for your prompt response. I'm using 0.7 Spox vesion itself and I have also validated individual models using `onnx.checker.check_model`
The only thing that I think I didn't handle is that the model 1 is a scikit learn and model 2 is a tensorflow model

This is my current complete code - 
```
from skl2onnx.common.data_types import StringTensorType
from skl2onnx import convert_sklearn
import tf2onnx
from spox import argument, Tensor, inline, build

# onehot_transformer is the one hot encoded model scikit learn model obtained from the previous pipeline
model_1 = convert_sklearn(onehot_transformer, 'onehot',
                             [(x, StringTensorType([None, 1])) for x in onehot_transformer.feature_names_in_])


# keras model is the tensorflow deep learning classifier model obtained from previous pipeline
input_signature = [tf.TensorSpec([None, 1416], tf.float32, name='one_hot_input')]
model_2, _ = tf2onnx.convert.from_keras(keras_model, input_signature)

# Create a mapping of all the input columns, from strings to spox Vars (variables)
inputs = {name: argument(Tensor(str, (None,1))) for name in onehot_transformer.feature_names_in_}
# Pass columns (inputs) by name with keyword arguments
(pred,) = inline(model_1)(**inputs).values()

(output,) = inline(model_2)(pred).values()

combined = build(inputs, {'output': output})
```

Can you kindly advice me?

**Comment by jbachurski** [comment]
Unfortunately it seems like an issue with naming that I have not caught in the past. My best guess is that `skl2onnx` or `tf2onnx` (likely the former) is using some construct that isn't getting renamed properly by `onnx.compose.add_prefix` which is used by Spox. 
If possible, it would be helpful if you could share the ONNX model files (you can dump them with `onnx.save(model_1, 'model_1.onnx')`), so that I can debug and fix the underlying issue. You might be able to put it as a `.zip` attachment here in GitHub.

As a workaround, maybe producing the model with different input names will avoid the name collision. Maybe you can try something like

```py
build(**{"__" + k: v for k, v in inputs.items()}, {'output': output})
```

**Comment by praneeth5222** [comment]
@jbachurski 
Please find the ONNX models [here](https://drive.google.com/drive/folders/1asHNsQwW-Ke2aQdwicfiFJ1bwAPqctUH?usp=share_link). Somehow I'm unable to add as an attachment, kindly request for access from the link

**Comment by jbachurski** [comment]
Thank you for providing the sample. That's an interesting bug, I'll try to create a bug fix in Spox, but I don't know the reason yet. It seems that somehow most renames are not performed at all. Please note the workaround I proposed in the previous comment seems to work, could you confirm it also does for you? 
The message `Warning: opset domain 'ai.onnx.ml' is not supported.` comes from the version converter, which is printing directly to STDERR even though it should not. I will try to make a fix for that here in the ONNX repo too.

**Comment by jbachurski** [comment]
I've discovered the source of the bug. The 'adapting' mechanism in Spox ensures that opset versions are consistent across all used operators when they are built. In this case, inlining also has support for this, and as your models had versions `11` and `15` adapting was performed. As it turns out, in that specific code path there is a bug which leads to renaming not being performed correctly in a version-converted model. There are two possible workarounds:

1. Perform version conversion yourself, to avoid Spox's adapting to kick in. As far as I see, you can do this with `model_1 = onnx.version_converter.convert_version(model_1, 15)` before you `inline`. This is done because your first model is at version 11, and the second is at version 15. Note that this call will print the `'ai.onnx.ml'` warnings from ONNX, which I'm fixing in [this PR](https://github.com/onnx/onnx/pull/5103). 
2. The above workaround with performing a manual renaming yourself also helps: `build(**{"__" + k: v for k, v in inputs.items()}, {'output': output})` (this line prefixes all model input names with `__`)

I will try and get a Spox fix ready for this specific case in the next version. Inlining is still a bit wonky as it's really tricky to 'normalise' arbitrary ONNX models, and is done on a best-effort basis.

**Comment by praneeth5222** [comment]
Thank you so much @jbachurski for your suggestions. I was able to combine the model with your first suggested approach.
I just have one more question.
Say if I wanted to combine another tensorflow model to the above merged model (all together, I wanted to combine 3 models), what is the best way to proceed forward?
So basically the output of the model 2 will be the input for model 3

**Comment by jbachurski** [comment]
You should be able to use the same approach as before, with calls like 

```py
...
(output2,) = inline(model_2)(pred).values()
(output3,) = inline(model_3)(output2).values()
...
```
If you have any other `Var`s you want to pass, you can do it either positionally or by name in the `inline(model)(...)` call. Just keep in mind a new `argument(...)` becomes a separate ONNX model input, so you should reuse them as necessary.

When it comes to using the workaround, I would still recommend doing version conversion manually until I push out a fix on the Spox side (`>0.7.0`), which might be this or next week.

**Comment by praneeth5222** [comment]
Thank you @jbachurski once again for your suggestion.
So I was able to save the combined model (which has 3 onnx models)
Now when I try to test the model using onnxruntime Inference session, can you suggest me how should I pass the input as?
I always am getting this error - `ValueError: Model requires 8 inputs. Input Feed contains 1`
I have tried to pass the input as dictionary or array with the shape (5, 8)

**Comment by jbachurski** [comment]
Hi @praneeth5222. I'm happy to see Spox worked out for you so far. 

If you're missing any outputs from the model that you were expecting to be there, maybe you didn't pass them to the outputs dict for `build`. If they are not from the final model, keep in mind you can also return outputs from preceding models. In [this](https://github.com/onnx/onnx/issues/5006#issuecomment-1500551178) code snippet of yours for instance, you could write `build(inputs, {'pred': pred, 'output': output})` to also return the output from the first model besides the second.
You could also compare the lists `model.output` (for `ModelProto`s) between the two models and see what's missing? Spox constructs a `Var` for every output, as named in that `model.output` list. You may have forgotten to pass some of them.

I'm not fully sure what would generate this sort of output from ONNX Runtime in the example you give:
```
[array([0, 0, 0, 0, 0], dtype=int64),
 [{0: 0.9965015649795532, 1: 0.0070548236383390},
  {0: 0.9942148327827454, 1: 0.0096996253311741},
  {0: 0.9957622289657593, 1: 0.0108639799052402},
  {0: 0.9961720108985901, 1: 0.0053693769270831},
  {0: 0.9961720108985901, 1: 0.0105181769270837}]]
```
I thought that ONNX Runtime never generates dictionaries like that, unless you're using some sort of extensions, processing the result, or using another runtime. If you meant that this is the output from the original library, maybe you should file a bug for the converter that the expected outputs are missing in ONNX.

If you think you encountered a bug and some outputs are missing, do try to produce a minimal example I could take a look at.

**Comment by praneeth5222** [comment]
hi @jbachurski 
Thank you for your suggestions.
So the expected outputs are not missing from the ONNX
```
[array([0, 0, 0, 0, 0], dtype=int64),
 [{0: 0.9965015649795532, 1: 0.0070548236383390},
  {0: 0.9942148327827454, 1: 0.0096996253311741},
  {0: 0.9957622289657593, 1: 0.0108639799052402},
  {0: 0.9961720108985901, 1: 0.0053693769270831},
  {0: 0.9961720108985901, 1: 0.0105181769270837}]]
```
So in the above dictionary, the value corresponding to 1 is the expected output which is the prediction probability for label 1 and I only need to extract these probabilities so that it is equivalent to the other spox model output.
For example I need to convert the above ONNX output to below way
```
[array([[0.00705482],
        [0.00969962],
        [0.01086397],
        [0.00536937],
        [0.0105181 ]]
```
The ONNX model has been generated using sklearn pipe something[ similar to this](http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_lightgbm.html)
Can you suggest me how do I transform the above mentioned ONNX model output (using any of the SPOX utility helpers) so that this output format will be in sync with the SPOX output.
I have also attached the [two ONNX models](https://drive.google.com/drive/folders/1vFTbGC_zmUFy-3fg1RgYldRilnLiOaeP?usp=sharing) for your reference

**Comment by praneeth5222** [comment]
Hi @jbachurski 
Let me know if my above statement is not clear. I would really appreciate if you could assist me with some SPOX utility helper to solve my problem

**Comment by jbachurski** [comment]
@praneeth5222 Thank you for your feedback using Spox. Apologies, but I did not have much free time to look into your issue.

It looks like your non-spox model is using `ZipMap`, which I have not seen used before in a model, as support of the `map` type in ONNX is extremely limited. Because of this, I had not implemented the type in Spox. This causes attempts to `inline` the model fails as it cannot de-serialize the output type (`ValueError: Cannot get Type from invalid protobuf (not tensor, sequence or optional)`). I'll open a PR in Spox to add `Map`, as it's a small change, but as far as I see support in ONNX itself is buggy and other exceptions are raised in e.g. shape inference. I'll also try to look into the source of this, but it will probably only be fixed in the next ONNX release cycle. 

---

Your best bet is to remove usage of `map` entirely. As I see from your `producer_name`, you are using `skl2onnx`. Consider following [this guide](http://onnx.ai/sklearn-onnx/auto_examples/plot_convert_zipmap.html) (I am not familiar with the inner workings of `skl2onnx` myself) to remove the `ZipMap` from the model. This should also cause the output format to be closer to what you might expect.

An alternative approach from going through `skl2onnx` is to remove the `ZipMap` node yourself from the raw `non_spox.onnx` model you have and use the value called `probabilities` as the output. 

```py
import onnx

non = onnx.load('non_spox.onnx')
non.graph.node.pop(-5)  # Remove the 'ZipMap' node - I found it manually by looking at the node list
non.graph.output.pop(-1)  # Remove the output map - 'output_probability'
# Add the probabilities as an input instead
prob_type = onnx.helper.make_tensor_type_proto(onnx.TensorProto.FLOAT, (None, 2))
prob_info = onnx.helper.make_value_info('probabilities', prob_type)
non.graph.output.append(prob_info)
onnx.save(non, 'non_spox_no_map.onnx')
```

Now you will have an `? x 2` tensor in the second output called `probabilities`. To extract only the probabilities, you can add in the [`Gather`](https://github.com/onnx/onnx/blob/main/docs/Operators.md#gather) operator to select index `1` across axis `1`. You can do this manipulating the ONNX directly, or in Spox:

```py
import onnx, spox
import spox.opset.ai.onnx.v17 as op  # Import Spox's opset module for the default ai.onnx domain

# The input names in your model
names = ['publisher_id', 'device_model', 'device_type', 'banner_size', 'creative_id', 'adomain', 'creative_type', 'bundle']
args = {name: spox.argument(spox.Tensor(str, (None, 1))) for _ in range(8) for name in names}
xprob = spox.inline(onnx.load('non_spox_no_map.onnx'))(*args.values())['probabilities']
prob = op.gather(xprob, op.const([1]), axis=1)  # Apply the Gather operator here
model = spox.build(args, {'prob': prob})
onnx.save(model, 'non_spox_fmt.onnx')
```

This seems to result in the same output format as you have in your other example - a `? x 1` tensor of probabilities.

**Comment by praneeth5222** [comment]
Thank you so much @jbachurski once again for your suggestion. Your solution solved my problem and right now my spox and non spox model are giving same outputs.

**Comment by praneeth5222** [comment]
Hi @jbachurski 
I'm facing a weird error when following your above mentioned suggestion.
When executing this specific line -` model = spox.build(args, {'prob': prob})`
I get this error  -
```
ValidationError: Nodes in a graph must be topologically sorted, however input 'Inline_0__argmax_output' of node: 
name: Inline_0__ArrayFeatureExtractor1 OpType: ArrayFeatureExtractor
 is not output of any previous nodes.
```
The weird part of this error is, this error only comes sometimes in between and this error doesn't arise majority of the times

Can you suggest me how do I solve this?

**Comment by jbachurski** [comment]
@praneeth5222 Does this happen on the same model files, or are you rerunning the converter too? It's possible that the converter is sometimes e.g. producing nodes in a different order and the `.pop(index)` calls invalidate the model. The solution I provided is a workaround and it's more difficult to provide one which doesn't assume what index the bad nodes are (except using the special converter flags, like I suggested, as in the skl2onnx guide).
Spox itself _should_ be deterministic, but if it happens on the same models (i.e. you have them saved on disk and are just `onnx.load`-ing them) I'd be happy to look into the bug, if you can provide the model artefacts.

**Comment by jbachurski** [comment]
Did you consider following the [guide](http://onnx.ai/sklearn-onnx/auto_examples/plot_convert_zipmap.html) I sent with the original solution to stop the converter from producing ZipMap nodes, instead of using the hack modifying the model in place? 
If you want to, you can also file an issue/PR with the converter, as this doesn’t seem like intended or good behaviour that the ordering is not deterministic.

If you really need to, you can make the hack slightly more robust by finding the only index of the node in `non.graph.node` with `node.op_type` (string) equal to ZipMap, and pop that index.
