### ISSUE TITLE
Refine docs for check_model

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5018]
Current version:

> Check the consistency of a model. An exception is raised if the test fails.

It would be good if we document the kind of checks done and the type of exception raised so users know what to catch for; as well as clarify that it also runs shape inference when strict is True. (Right now it says `if True, the function checks shapes can be inferred`）

Should we default `strict` to `True`? @jcwchen

**Comment by jcwchen** [comment]
> Should we default strict to True? @jcwchen

I guess you are saying full_check in onnx.checker.check_model? IIRC, we didn't set full_check by default due to compatibility. Previously onnx.checker.check_model does not check anything related to shape/type inference. Such a check was brought after https://github.com/onnx/onnx/pull/2367 (>=ONNX 1.7.0). Enabling full_check by default might cause some old models fail with onnx.checker, although they might be still runnable by runtime.

**Comment by cbourjau** [comment]
IMHO, it should not be considered a breaking change if a checker becomes better and gains more capabilities over time. Changing the default to fail on an incomplete check (e.g. missing type/shape inference for an Op) might be quite disruptive, though.
