### ISSUE TITLE
[PR436 Follow Up] Formalize Control Flow Ops and Move Out of Experimental

### ISSUE THREAD

**Issue by jamesr66a** [onnx/onnx#502]
Checking this in as experimental: https://github.com/onnx/onnx/pull/436

Once we've built out implementations up and down the translation stack we can finalize the ops and make them non-experimental

**Comment by gramalingam** [comment]
Since PR 436 has been merged, let me continue the discussion here. 

Is the goal to allow LoopIndexTensor as a generic operator (a special case of Gather), or to constraint its use where the index is allowed to be only the iteration variable?

In the latter case, I think that the best strategy is to use a scan/fold/reduce/map like operator: in this case, the operator will specify which axis of which tensor we are iterating over, and the "loop body graph" will take as a parameter the corresponding "LoopIndexTensor(j)" itself as a parameter rather than taking the loop-index "j" as a parameter, and there is no need to use "LoopIndexTensor". 

If there is a need to index more than one tensor (in a synchronized fashion), then we can generalize the above to a "zip" like operator (that takes multiple tensors, with an axis for each, and iterates over them in a synchronized fashion).

If we do use LoopIndexTensor, then I think its documentation should be changed and clarified (which I find confusing and ambiguous currently). It should not be restricted to "just the loop index variable".

**Comment by gramalingam** [comment]
There is one possible minor issue/problem with the way the loop-body-graph's output is used to specify the "scan-outputs" ... what happens if the same tensor T is both a loop-carried-dependence and a tensor to be included in the scan-output? Is the "output" list for a graph allowed to have duplicate names?

**Comment by RanACohen** [comment]
In many LSTM & RNN cases you need to keep an internal state between iterations.
This must be visible to this LoopIndexTensor as it needs to rotate the internal state per iteration.

Caffe2 has a similar layer (I think RNN is its type name) which does this.

**Comment by ArchRobison** [comment]
Can the control-flow ops be used recursively?  E.g., if graph G contains an If, can the then_branch be G?

**Comment by RanACohen** [comment]
namespace of 'value' nodes for sub-graphs should be local. No logic of allowing a sub-graph reference a node outside of it.

**Comment by prasanthpul** [comment]
Control flow is already official
