### ISSUE TITLE
What are context dependent functions?

### ISSUE THREAD

**Issue by justinchuby** [onnx/onnx#5077]
# Ask a Question

### Question

I see a `get_context_dependent_function` method but couldn't find documentation on what context dependent functions are.

**Comment by jbachurski** [comment]
I'm fairly certain these are operators which have a function representation, but only in a function-builder context. This happens when the body can't be expressed as a static `FunctionProto`, e.g. they need access to the input types or attribute values.

Compare for instance a 'context-less' function, `SoftPlus`:

https://github.com/onnx/onnx/blob/50eaceca9906a3b3aa55d1d66c0972c4c2759f87/onnx/defs/math/defs.cc#L1140-L1150

And the context-dependent `SoftMax` function builder:

https://github.com/onnx/onnx/blob/706559c779bd4c78d78365fe854701a0bcc75626/onnx/defs/math/defs.cc#L1017-L1031

I also found functions to be rather undocumented. It would be great if working with them was more ergonomic and there could be a better attempt made at minimizing the surface of the ONNX standard.

**Comment by justinchuby** [comment]
Thanks!
