### ISSUE TITLE
Permitting nan keys in LabelEncoder

### ISSUE THREAD

**Issue by adityagoel4512** [onnx/onnx#5092]
# Ask a Question

### Question
`LabelEncoder` defined under the [`ai.onnx.ml`](https://github.com/onnx/onnx/blob/main/docs/Operators-ml.md) domain explicitly says:

> For key look-up, bit-wise comparison is used so even a float NaN can be mapped to a value in 'values_' attribute.

It would be great to understand the rationale behind the decision to accept `NaN` keys.

Given there are potentially different bit representations of `NaN`, this might prove problematic both in terms of reasoning and also in terms of implementation. On the implementation point, [onnxruntime](https://github.com/microsoft/onnxruntime) does not support this behaviour - in the cpu implementation, a `std::unordered_map` is used which doesn't permit `NaN` as a key. 

I would argue that rather than adapting the runtime and adding complexity to support this, the specification should be changed. Accepting `NaN`s as valid keys complicates reasoning for programmers and runtime implementers: IEEE-754 `NaN`s don't equal themselves which makes the idea of mapping from a `NaN` not intuitive. 

### Further information
- Relevant Area: operators, specification

- Is this issue related to a specific model?
No

### Notes
Using [Spox](https://github.com/Quantco/spox) and onnxruntime to demonstrate that onnxruntime doesn't permit `NaN` keys (on CPU):

```
import spox.opset.ai.onnx.ml.v3 as ml
from spox import argument, build, Tensor
import onnxruntime
import numpy as np

VectorFloat32 = Tensor(np.float32, ('N',)) 
x = argument(VectorFloat32)
q = ml.label_encoder(x, keys_floats=[1., 2., 3., np.nan], values_strings=["X", "Y", "Z", "!!!"], default_string="Not here")
model = build({'x': x}, {'r': q})

session = onnxruntime.InferenceSession(model.SerializeToString())

result = session.run(None, {
    'x': np.array([1., 2., np.nan], dtype=np.float32)
})

print(result)
```

This returns:
`[array(['X', 'Y', 'Not here'], dtype=object)]` instead of `[array(['X', 'Y', '!!!'], dtype=object)]`

**Comment by cbourjau** [comment]
One may argue that there is more of a rational for `NaN` keys than for other floating point values: The `LabelEncoder` can be used to replace `NaN` values with something else. The problem is that using the bit representation to hash nan values is not serving this purpose since the user probably wants to replace NaN values regardless of their precise bit schema. 

Essentially, a runtime would need to define a custom hashing logic for floating point keys in this use case. In Rust, for example, there is the `ordered_float` crate which [implements](https://docs.rs/ordered-float/latest/src/ordered_float/lib.rs.html#158-167) a hashing logic for floating points that normalizes all `NaN` values. This allows it to be [used](https://docs.rs/ordered-float/latest/ordered_float/struct.OrderedFloat.html#impl-Hash-for-OrderedFloat%3CT%3E) in hash maps as "expected".
