### ISSUE TITLE
RuntimeWarning: overflow encountered in cast

### ISSUE THREAD

**Issue by lutzroeder** [onnx/onnx#5139]
# Bug Report

### Describe the bug

#4729 and #4774 for context

```
~/onnx/lib/python3.11/site-packages/onnx/backend/test/case/node/cast.py:137: RuntimeWarning: overflow encountered in cast
  input_values = np_fp32.astype(np.float16).astype(np.float32)
~/onnx/lib/python3.11/site-packages/onnx/backend/test/case/node/cast.py:306: RuntimeWarning: overflow encountered in cast
  input_values = np_fp32.astype(np.float16).astype(np.float32)
```

### System information
- OS Platform and Distribution: macOS arm64
- ONNX version (*e.g. 1.13*): main
- Python version: Python 3.11.3

### Notes

@jcwchen @xadupre introduced by #4805

**Comment by xadupre** [comment]
What is your version of numpy? I run the following code without any warning with numpy 1.23.5 and 1.24.2.

```python
import numpy as np
np_fp32 = np.array(
                    [
                        "0.47892547",
                        "0.48033667",
                        "0.49968487",
                        "0.81910545",
                        "0.47031248",
                        "0.816468",
                        "0.21087195",
                        "0.7229038",
                        "NaN",
                        "INF",
                        "+INF",
                        "-INF",
                    ],
                    dtype=np.float32,
               )
np_fp32.astype(np.float16).astype(np.float32)
```

**Comment by lutzroeder** [comment]
The warning only shows on first invoke. Processor [type](https://github.com/onnx/onnx/issues/4774#issuecomment-1382460457) might be another pivot.

```py
>>> import numpy
>>> numpy.__version__
'1.24.2'
>>> x = numpy.array([ "1000000" ], dtype=numpy.float32)
>>> print(x)
[1000000.]
>>> y = x.astype(numpy.float16).astype(numpy.float32)
<stdin>:1: RuntimeWarning: overflow encountered in cast
>>> print(y)
[inf]
```

**Comment by jcwchen** [comment]
Hi @lutzroeder,
Thanks for reporting. I can repro it on M1 machine (other platforms work fine without warning though). I am confirming with numpy team: https://github.com/numpy/numpy/issues/23606 to understand whether the warning is expected, because such a warning doesn't happen when casting super large float64 to float32 on M1.

**Comment by jcwchen** [comment]
This issue is slightly different from https://github.com/onnx/onnx/issues/4774. Actually this overflow cast warning happens globally (on my Windows 10, Ubuntu 20.04, Mac (Intel/M1)) when using numpy>=1.24. numpy introduced this warning intentionally since 1.24 and they also provide a way to suppress it: `np.errstate(overflow="ignore")`: https://github.com/numpy/numpy/issues/23606#issuecomment-1512752172. Although it throws a warning, the behavior seems expected (larger float to smaller float becomes infinite and reverse will become infinite and loss precision)

I guess the numpy code here in ONNX is to test the boundary when casting floats? If yes, perhaps it is just fine?

**Comment by lutzroeder** [comment]
@jcwchen investigating this some more the root issue seems that this test code is executed when running `collect_snippets`. Any subclass of [Base](https://github.com/onnx/onnx/blob/0d1f14422cf8912e561bcb02d455917935ff3346/onnx/backend/test/case/base.py#L41) when imported seems to trigger [export](https://github.com/onnx/onnx/blob/0d1f14422cf8912e561bcb02d455917935ff3346/onnx/backend/test/case/base.py#L41) running test code. Is that by design?

See #5154

**Comment by jcwchen** [comment]
> investigating this some more the root issue seems that this test code is executed when running collect_snippets. Subclasses of [Base](https://github.com/onnx/onnx/blob/0d1f14422cf8912e561bcb02d455917935ff3346/onnx/backend/test/case/base.py#L45) when imported seems to trigger [export](https://github.com/onnx/onnx/blob/0d1f14422cf8912e561bcb02d455917935ff3346/onnx/backend/test/case/base.py#L41) running test code. Is that by design?

Thank you for investigating. I have directly replied this question here: https://github.com/onnx/onnx/issues/5154#issuecomment-1515333139.
