### ISSUE TITLE
[Feature request] Generate the ONNX and ONNX-ML operator doc in one run

### ISSUE THREAD

**Issue by jcwchen** [onnx/onnx#5377]
### System information

Main branch

### What is the problem that this feature solves?

Previously ONNX CI does not run `ONNX_ML=0 python onnx/defs/gen_doc.py` to correctly update `Operators.md`: https://github.com/onnx/onnx/pull/5367. It easily brings confusion and I don't see benefit of making doc generation separate.

### Describe the feature

Just like an old closed PR: https://github.com/onnx/onnx/pull/3467: Generate ONNX and ONNX-ML operator doc in one run for simplicity and prevent confusions.

### Will this influence the current api (Y/N)?

Y. `python onnx/defs/gen_doc.py` will produce documents for ONNX and ONNX-ML in one shot.

### Feature Area

Doc generation

### Are you willing to contribute it (Y/N)

Yes

**Comment by jbachurski** [comment]
Is there a documented reason why there's a special build setting for ONNX ML at all? I never figured out a reason why. It creates unnecessary duplication and complication in the codebase, and seemingly with no real benefit (the binary size difference is likely negligible). Would this be due to it once being an experimental feature?
