### ISSUE TITLE
AttributeError: module 'onnx' has no attribute 'load_from_string'

### ISSUE THREAD

**Issue by alskdjfasdfsadf** [onnx/onnx#5388]
Hello, thank you for your hard work. The following error occured while using onnx. 

I used the code : 
import torch.onnx

# Step 1: Load your PyTorch model from the specified path (load to the same device as available)
model_path = "/home/user/background_segmentation_model.pth"
device = "cuda" if torch.cuda.is_available() else "cpu"  # Check if CUDA/GPU is available
model = torch.load(model_path, map_location=device)
model.to(device)  # Move the model to the same device as the input tensor

import io
import numpy as np

batch_size = 1
model.eval()
dummy_data = torch.empty(1, 3, 224, 224, dtype=torch.float32, device=device)

# Step 3: Export the model to ONNX
torch.onnx.export(
    model,
    dummy_data,
    "output.onnx",
    export_params=True,
    opset_version=11,
    do_constant_folding=True,
    input_names=["input"],
    output_names=["output"],
    dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}},
)

and the following error occured: 
File "/home/user/toonnx.py", line 18, in <module>
    torch.onnx.export(
  File "/home/user/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/user/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1620, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/home/user/.local/lib/python3.10/site-packages/torch/onnx/_internal/onnx_proto_utils.py", line 239, in _add_onnxscript_fn
    model_proto = onnx.load_from_string(model_bytes)
AttributeError: module 'onnx' has no attribute 'load_from_string'

what can I do to fix this error?

**Comment by justinchuby** [comment]
Consider upgrading onnx? What's the version of onnx on your machine?

**Comment by xadupre** [comment]
You can also use something like `onnx.load(io.BytesIO(model_bytes))`.

**Comment by siddharthksah** [comment]
`pip install --upgrade onnx
`
After updating the onnx package, try running your code again. It should resolve the AttributeError and allow you to export the PyTorch model to ONNX successfully.

**Comment by henbucuoshanghai** [comment]
same error,  and pip install --upgrade onnx   not work
,how to solve it

**Comment by henbucuoshanghai** [comment]
======= Diagnostic Run torch.onnx.export version 2.1.0.dev20230627+cu118 =======
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================


 torch.onnx.export(model,
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 507, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1639, in _export
    proto = onnx_proto_utils._add_onnxscript_fn(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/onnx_proto_utils.py", line 230, in _add_onnxscript_fn
    model_proto = onnx.load_from_string(model_bytes)
AttributeError: module 'onnx' has no attribute 'load_from_string'

**Comment by justinchuby** [comment]
Were you running a script in a directory called onnx? If so cd out of the directory and run the script again. Le 16 janv. 2024 à 00:03, henbucuoshanghai ***@***.***> a écrit :﻿Re: [onnx/onnx] AttributeError: module 'onnx' has no attribute 'load_from_string' (Issue #5388)======= Diagnostic Run torch.onnx.export version 2.1.0.dev20230627+cu118 =======verbose: False, log level: 40======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================torch.onnx.export(model,File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 507, in export_export(File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1639, in _exportproto = onnx_proto_utils._add_onnxscript_fn(File "/usr/local/lib/python3.10/dist-packages/torch/onnx/_internal/onnx_proto_utils.py", line 230, in _add_onnxscript_fnmodel_proto = onnx.load_from_string(model_bytes)AttributeError: module 'onnx' has no attribute 'load_from_string'—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you commented on the thread.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zengqingfu1442** [comment]
mark

**Comment by fengkh** [comment]
mark

**Comment by fengkh** [comment]
did you solve this error? same situation on my onnx

**Comment by gilljon** [comment]
Install ONNX pip package to remediate the situation.

**Comment by JoeyRedfield** [comment]
In addition to the folder cannot be named onnx, the executable pyfile name cannot be named `onnx.py`.
After upgrading onnx, it is best to set opset_version=12.
