### ISSUE TITLE
Merging two models fail when the resulting exceeds maximum protobuf size of 2GB

### ISSUE THREAD

**Issue by L-lowliet** [onnx/onnx#5489]
# Bug Report

### Describe the bug

![image](https://github.com/onnx/onnx/assets/53377110/d405567c-df93-40ab-b7cb-9ac4f513f3e2)
When I use the **onnx.compose.merge_models** function to merge two onnx models, an error will be reported. The main reason is that my merged model exceeds 2G. After I comment out the running code pointed by the arrow above, it can run normally. But the process of model checking is missing. Later, when I exported the merged onnx model, I set **save_as_external_data** to **True**. After learning to the method linked below, I reloaded the exported onnx model to perform a model check and shape_inference.
[https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md](url)

### System information

 ONNX version：1.13.1
onnx-weekly ：1.15.0 dev20230807
（I have tried both of the above）

**Comment by jcwchen** [comment]
Hi @L-lowliet,
Similar as https://github.com/onnx/onnx/issues/5234. Currently a single Protobuf object cannot exceed 2GB due to Protobuf limitation. I would suggest try to load models without external data before merge, as mentioned in https://github.com/onnx/onnx/issues/5234#issuecomment-1553781303.
