### ISSUE TITLE
Result accuracy is different with PyTorch

### ISSUE THREAD

**Issue by YI-MAX-YAN** [onnx/onnx#5490]
**The difference with PyTorch result is common in onnx?**
This figure shows the difference between onnx(left)  and  @PyTorch(right).
![image](https://github.com/onnx/onnx/assets/59284392/d6016847-8384-4940-a71d-f9e77720ff97)

**Comment by jcwchen** [comment]
Hi @YI-MAX-YAN,
It's a broad question. The result difference between two different frameworks could be caused by few possible reasons:
1. (Conversion) When conversion from PyTorch to ONNX, it's possible that there are some gaps/issues between the original model and the converted model. You can use `onnx.checker.check_model(model, full_check=True)` to fastly validate the converted onnx model or use https://netron.app/ to inspect whether the converted ONNX model is same as the original one (although nowadays models are typically huge).
2. (Runtime) Different platform/execution provider might cause slight result difference. You can imagine the kernels on difference hardware won't always behave exactly the same -- which runtime did you run your ONNX model?
3. (Runtime) Different precision for these two models.

+1 @justinchuby Back to your provided example -- the output actually looks quite close to me (the distance is generally smaller than 10^-5). As long as the output difference does not influence the model's performance, the converted onnx model should be fine. If it does have impact on performance, we need to further check whether it's a converter issue or runtime issue.

**Comment by YI-MAX-YAN** [comment]
Thank you all for your responses. The difference in results here will affect my modelling results. Because of the use of scale_table in the model to quantify the data, there exists a need for the model to be accurate to FP32 to have the correct results.
