### ISSUE TITLE
[Feature request] Replace Onnx IR File Format instead of Protobuf

### ISSUE THREAD

**Issue by TechScribe-Deaf** [onnx/onnx#5500]
### System information

Any

### What is the problem that this feature solves?

Removing Protobuf alleviates few hard limits found in Protobuf. Protobuf have a hard limit of 2 GB serialization and is particularly fragile between versions (had to install 3.20.* version of Protobuf) and it comes up as a problem when attempting to do training on Llama 2 when saving checkpoint that the 2gb limit is encountered.

### Alternatives considered

My proposal is as thus that we build an IR bitcode file and readable file format in the same methodology that LLVM IR are done in a sense that it would reduce the barrier of entry for those interested in contributing to Onnx and it would be aligned toward the goal of making ONNX IR the open data format for neural net data.

If we HAVE TO have a serialization then we could use JSON to alleviates the 2GB limit and all data or constants be referred to as files from within the IR code.

### Describe the feature

Removal of Protobuf to alleviate fragility of versionings and 2gb hard limit in serialization.

### Will this influence the current api (Y/N)?

Y

### Feature Area

Safe to say, it affects everything.

### Are you willing to contribute it (Y/N)

Yes

### Notes

I was told by other members of Onnx on slack to open a bug report here. There is an interest for this on ONNX 2.

**Comment by justinchuby** [comment]
Many things are valid and agreed by many. Just offering a perspective on why I think there is still value in keeping protobuf as a serialization target and the data structure definition (instead of getting rid of it completely).

1. They can be understood and manipulated without depending on the ONNX code base. One only needs the proto file to read, manipulate and write to the model. One advantage imo for the ONNX format is its portability (compared to custom defined bitcode or customized serialization format), because protobuf is implemented in virtually any language.
2. Compared to JSON, the data structure is cleanly and rigorously defined and enforced by protobuf itself. The proto file is easier to read and maintain than, say, a json schema. It is also faster at serialization.

In terms of the 2GB limit, I would like to understand it better: was there any limitation if you store the weights external to the model structure itself (which tend to be much smaller than 2GB)?

Again this is not to say we should not consider other solutions or allowing multiple serialization targets, but I would like to point out upsides of protobuf that may be potentially overlooked.

**Comment by justinchuby** [comment]
> particularly fragile between versions (had to install 3.20.* version of Protobuf)

Could you elaborate? I am curious to learn more here.

**Comment by justinchuby** [comment]
For the IR, there is also https://github.com/onnx/onnx-mlir and https://onnx.ai/onnx/repo-docs/Syntax.html. Do you have any thoughts on these?

**Comment by TechScribe-Deaf** [comment]
I will get the full error log for Protobuf errors when I get home, sorry again!

**Comment by TechScribe-Deaf** [comment]
Ok, unfortunately, the server that prints this error is no longer working (old hardware bought off Ebay, so I couldn't print off more information about Protobuf at this time.)

**Comment by justinchuby** [comment]
Were you able to reproduce the error anywhere else?

**Comment by snnn** [comment]
ONNX's shape inference code heavily depends on protobuf.  So, unless your model is statically shaped, you will still need to use protobuf.

**Comment by justinchuby** [comment]
Support for JSON is added in https://github.com/onnx/onnx/pull/5523. That said json is always supported via protobuf for free.

**Comment by linkerzhang** [comment]
Interesting.

@TechScribe-Deaf in case you missed, onnx designed a way to store weights in external files, does that work for your case please?

**Comment by norlesh** [comment]
Considering that language models are routinely several gigabytes in size there needs to be an alternate format to using Protocol Buffers - especially when Googles own documentation states "Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy." - as for separating the buffer and weights into different files then there needs to be additional conventions established to deal with handling and storing entire directories - having a single file per model is far more desirable.

**Comment by justinchuby** [comment]
Related https://github.com/onnx/onnx/wiki/%5BDraft%5D-Proposal-for-ONNX-archive-file-format
