### ISSUE TITLE
INT8 quantization model from torch to onnx slower than FP32 model on cpu

### ISSUE THREAD

**Issue by minhhotboy9x** [onnx/onnx#6030]
I quantized a simple CNN model in pytorch and converted it to onnx. When I tested the runtime of int8 model and fp32 model on CPU, the int8 model was slower. Here my code:
[Google colab](https://drive.google.com/file/d/1-2bfKGPXTQP1FItFYRBE82MVFv1hsaEj/view?usp=sharing)
The result of inference each model 1000 times:
```
FP32: 10.28 secs
INT8: 15.52 secs
```
How that is possible? Does anyone solve this problem?

**Comment by justinchuby** [comment]
To realize the performance / memory benefits, operators need to be implemented to support INT8 on specific hardware. For further information it would be helpful to open an issue in the microsoft/onnxruntime repository. Thanks. Closing the issue here for now. Please feel free to link the new issue here if you are creating one in microsoft/onnxruntime.
