### ISSUE TITLE
How to modify Slice attribute

### ISSUE THREAD

**Issue by salanzewei** [onnx/onnx#6139]
# Ask a Question

### Question
I want to add `steps` parametre in Slice node,but I can't get the Slice input parametres,how can I get the Slice input parametres and change it?  

### Further information
my Slice node input parametres show in the below image,what 's the meaning of `const_starts__19`?Shouldn't `starts` be 0 or 1?
![捕获2](https://github.com/onnx/onnx/assets/74665291/9a0edc95-9248-4ad6-a1b9-550b77e6d8a9)
when I try to get the input parametres,I only get this:`inputs:  ['model/p_re_lu_2/add:0', 'const_starts__19', 'const_ends__20', 'const_axes__30']`how can I create Slice `steps` parametres and set value?

**Comment by titaiwangms** [comment]
@justinchuby Could you take this? Also, I think using IR might be pretty easy?

**Comment by justinchuby** [comment]
I think `const_starts__19` is the output of a Constant node. To create steps, create a new Constant node with the desired value, then add its output as an input to the Slice node (as a high level process).

@titaiwangms currently the input list in the IR are immutable so users will need to copy the node to a new node. So that's not entirely straightforward but entirely doable.

**Comment by titaiwangms** [comment]
Python API: https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md

**Comment by salanzewei** [comment]
> Python API: https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md

Thank you so much, I found `onnx-graphsurgen`can modify node  through create a new node and replace old node.
