### ISSUE TITLE
n-bit data type

### ISSUE THREAD

**Issue by jeyblu** [onnx/onnx#6326]
# Ask a Question

### Question

Can you describe how ONNX will support n-bit data types, e.g. [4-bit data type](https://github.com/onnx/onnx/pull/5811). Will it be through making ops like [matmulnbits](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/contrib_ops/cpu/quantization/matmul_nbits.cc#L82) or through other ways like expressing the n-bit ops using dequantizelinear and quantizelinear? Thanks.

**Comment by gramalingam** [comment]
IMO: quantize/dequantize is the preferred approach. Ideally, any op like `matmulnbits` could be defined as a function (Dequantize => MatMul => Quantize). Other suggestions/opinions welcome.

**Comment by titaiwangms** [comment]
@gramalingam Should we close this?

**Comment by georgen117** [comment]
As the author of #6500 I agree with @gramalingam that the ideal approach to handling N-Bits is using a quantize/dequantize (Q/DQ) approach. However, Q/DQ is currently limited to the data types supported i.e. int4, int8, etc.

My initial approach for MatMulNBits was to add a new operator UnpackNBits that would take a packed N-Bit data and unpack it to the closest supported data type for example: 2-bit -> 4-bit,  3-bit -> 4-bit, 5-bit -> 8-bit etc.  This only works for integer data types.

The reason I didn't introduce an UnpackNBits with MatMulNBits was it didn't solve all the issues to make it a function instead of an Operator. I needed additional changes I was not comfortable suggesting. I decided to contribute MatMulNBits as an Operator.

**Comment by gramalingam** [comment]
Yes, the QDQ is the preferred approach in the long term. But to get there, we need to define other n-bit datatypes (for 2, 3, 5, etc.). And add/extend the Q and DQ ops to support these datatypes.

Until that happens, matmulnbits as an op seems a reasonable tactic.
