### ISSUE TITLE
Model split failure using onnx.utils.extract_model

### ISSUE THREAD

**Issue by bkaruman** [onnx/onnx#6328]
# Bug Report

### Describe the bug
I am trying to split [Phi-3 INT4 ONNX](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct-onnx/tree/main/cpu_and_mobile/cpu-int4-rtn-block-32-acc-level-4) for profiling experiments. 

### System information

OS Platform and Distribution (*e.g. Linux Ubuntu 20.04*): Windows
 ONNX version (*e.g. 1.13*):1.16.2
 Python version:3.12

### Reproduction instructions

import onnx

input_path = "E:\models\phi3-mini-4k-instruct-cpu-int4-rtn-block-32-acc-level-4.onnx"
output_path = "E:\tmp.onnx"
num_layers=1
input_names = ["input_ids"]
output_names=["/model/embed_tokens/Gather/output_0"]
onnx.utils.extract_model(input_path, output_path, input_names, output_names)

I see the following error:
onnx.onnx_cpp2py_export.checker.ValidationError: No Op registered for SimplifiedLayerNormalization with domain_version of 14

==> Context: Bad node spec for node. Name: /model/layers.0/input_layernorm/LayerNorm OpType: SimplifiedLayerNormalization

ONNX checker seems to be failing, due to contrib_ops in the models? Is there another way to split models that have contrib ops?

**Comment by gramalingam** [comment]
A combination of a couple of factors seem to be at cause here.

In the ONNX utility, it makes sense to do [this check](https://github.com/onnx/onnx/blob/81b253794220d760eb06fe892a2844e179dd58c6/onnx/utils.py#L227) only if `check_model` is true, just like for the output a few lines later. (But the check on input may be intended to avoid trying to process ill-formed models.)

The check itself should, ideally, not failed due to the presence of custom ops. I guess the problem here is that onnxruntime (erroneously) has registered this custom op in the ONNX domain (see [here](https://github.com/microsoft/onnxruntime/blob/628c0a8f0ee25eda0731310eadaec34c53a5da69/onnxruntime/core/graph/contrib_ops/contrib_defs.cc#L2982). That might be a more involved problem to fix.

**Comment by gramalingam** [comment]
With the fix in the above PR, you can use `onnx.utils.extract_model(input_path, output_path, input_names, output_names, check_model=False)` to work around the issue

**Comment by bkaruman** [comment]
> With the fix in the above PR, you can use `onnx.utils.extract_model(input_path, output_path, input_names, output_names, check_model=False)` to work around the issue

Great. Thank you for the fix.
