### ISSUE TITLE
Failure on converting from onnx model to caffe2 model

### ISSUE THREAD

**Issue by qzhong0605** [onnx/onnx#790]
I following the `onnx` tutorials to import models from `ONNX` to `Caffe2`[https://github.com/onnx/tutorials/blob/master/tutorials/OnnxCaffe2Import.ipynb](url). But I can't success to do that. 
The error message is the following:

>  onnx-1.1.1-py2.7-linux-x86_64.egg/onnx/optimizer.pyc  in optimize(model, passes)
     40                   'fuse_transpose_into_gemm']
     41     if not isinstance(model, ModelProto):
---> 42         raise ValueError('Optimizer only accepts ModelProto, incorrect type 
    {}'.format(type(model)))
     43 
     44     model_str = model.SerializeToString()
 ValueError: Optimizer only accepts ModelProto, incorrect type: <type 'str'>

I obtain the `onnx` using git and build it on myself. And I look into the `onnx/backend.py` on `Caffe2`. I found that the `onnx model` has been serialized. Now it's been serialized again on the `optimizer.py` on `onnx`, which is on the method `optimize(model, passes=None)`. In the method `optimize(model, passes=None)` of `optimizer.py` on `onnx`, it's regard as a non-serialized `onnx` model.

Is anything wrong when designing interfaces?

**Comment by qzhong0605** [comment]
`jajdjdjdjdjdjdj
jdjjdjajj
ajdjjd`

**Comment by bddppq** [comment]
This is a recent change in the optimizer api that changed to take ModelProto instead of serialized bytes as input (same for output). Corresponding update to caffe2 has been made here https://github.com/pytorch/pytorch/commit/aab0bd3c132892d27851a6411910e17917b031b9, please install caffe2 from our github master again to include this new change (just in case you are not aware, [caffe2 and pytorch repos have merged together now](https://github.com/caffe2/caffe2/issues/2439)).

**Comment by qzhong0605** [comment]
Thanks. I learned that `caffe2` and `pytorch` repos had merged together now.  But I don't aware that the optimizier api has also changed.
Thank your reply!
