### ISSUE TITLE
pip install on Windows issues

### ISSUE THREAD

**Issue by kit1980** [onnx/onnx#807]
I'm trying to install from source according to https://github.com/onnx/onnx/blob/master/docs/CONTRIBUTING.md

I'm using Windows 10 and Visual Studio 2017 with Visual C++ tools for CMake installed.

The first issue I had was
```
    CMake Error at CMakeLists.txt:5 (project):
      Generator
        NMake Makefiles
      does not support platform specification, but platform
        x64
      was specified.
```

The next problem was nmake doesn't support maxcpucount parameter.
```
NMAKE : fatal error U1065: invalid option 'm'
```

These are the changes to setup.py that allowed me to proceed:
```
--- a/setup.py
+++ b/setup.py
@@ -161,7 +161,8 @@ class cmake_build(setuptools.Command):
                 if 8 * struct.calcsize("P") == 64:
                     # Temp fix for CI
                     # TODO: need a better way to determine generator
-                    cmake_args.append('-DCMAKE_GENERATOR_PLATFORM=x64')
+                    # cmake_args.append('-DCMAKE_GENERATOR_PLATFORM=x64')
+                    pass
             if ONNX_ML:
                 cmake_args.append('-DONNX_ML=1')
             if 'CMAKE_ARGS' in os.environ:
@@ -175,7 +176,8 @@ class cmake_build(setuptools.Command):

             build_args = [CMAKE, '--build', os.curdir]
             if WINDOWS:
-                build_args.extend(['--', '/maxcpucount:{}'.format(self.jobs)])
+                pass
+                # build_args.extend(['--', '/maxcpucount:{}'.format(self.jobs)])
             else:
                 build_args.extend(['--', '-j', str(self.jobs)])
             subprocess.check_call(build_args)
```

After these changes it compiles successfully, but linking produces tons of errors, please see the attached file:
[onnxsetuplog.txt](https://github.com/onnx/onnx/files/1940213/onnxsetuplog.txt)

Any suggestions how to proceed from here?

**Comment by houseroad** [comment]
@raymondxyang could you take a look?

**Comment by raymondxyang** [comment]
Hi thanks for reporting and helping solving the problems first. The current blocking problem is that pybind11 used in onnx_cpp2py_export project cannot take debug static library. That why the protobuf lib should be build with /MT instead of /MTd. We would suggest 1. Get protobuf from Conda 2. Build protobuf (2.6.1) from source with configuration /MT explicitly. Hopefully this can solve your issue.

The modified cmake part in first two issues is aimed to fully utilize and adapt different environment on build system. We can discuss if we should add more configurable parameters to enable customization.

**Comment by kit1980** [comment]
@raymondxyang, thanks for looking.
I'm confused about your suggestion "1. Get protobuf from Conda".
I'm already using protobuf from conda (installed via `conda install -c conda-forge protobuf`:     libprotobuf: 3.5.2-vc14_0 and protobuf:    3.5.2-py36_vc14_0).
Am I missing something?

**Comment by raymondxyang** [comment]
Sorry for the mistake. The protobuf is good actually, with 'MT' configuration. Looks like what is not correct is the configuration for the cpp2py_export project. Can you manually set it in Visual Studio project properties to /MT instead of /MTd? It should be set to MT by default. I ll double check it later.

**Comment by kit1980** [comment]
I've found the issue.
Checking for empty CMAKE_BUILD_TYPE must be done before project(), otherwise it will be already set to Debug. So the build was Debug by default, despite the "defaulting to Release" intent.

**Comment by kit1980** [comment]
#812

**Comment by linkerzhang** [comment]
Closing the issue since PR merged.
