### ISSUE TITLE
More operators: where, >= and <=?

### ISSUE THREAD

**Issue by zasdfgbnm** [onnx/onnx#870]
How about adding the following three new operators?
`Where`, `GreaterOrEqual`, `LessOrEqual`

Would these be helpful?

**Comment by zasdfgbnm** [comment]
Can anyone make any comment on this?  I just need to know if they are contribute welcome. These ops are useful to me, and if it is contribute welcome, I can easily add it as I did in https://github.com/onnx/onnx/pull/869

For the `GreaterOrEqual` and `LessOrEqual`, we already have `Greater` , `Less`, `Equal`, and `Or`, but it is not a good idea to express `>=` as `> or =`, since many ISAs support `>=` instructions natively.

Also for the `Where`, it is also widely supported:
https://www.tensorflow.org/api_docs/python/tf/where
https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.where.html
https://pytorch.org/docs/master/torch.html#torch.where
http://docs.chainer.org/en/stable/reference/generated/chainer.functions.where.html
https://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.where

**Comment by bddppq** [comment]
For `GreaterOrEqual` and `LessOrEqual`, since as you have pointed out they can be composed by existing ops, so I feel it's better to not add them (or we could use the newly added `Function` to introduce these composed ops). @linkerzhang 
For `Where`, this can be implemented as `If` with the two graph attributes only containing one single Constant Node. @jamesr66a @zdevito

**Comment by zasdfgbnm** [comment]
@bddppq Thanks a lot for your quick reply!

As a user, I'm totally happy with the solution of composing `GreaterOrEqual` and `LessOrEqual` by existing ops. It might just be a bit annoying for DL framework developers, e.g. they might need to write code to optimize `a > b or a = b` or `not a < b` to `a >= b` to turn 2 tensor operations into 1 for better performance.

For the `Where`, your reply completely sounds good to me. Maybe I should go to my framework and implement the onnx export part this way.

**Comment by zasdfgbnm** [comment]
@bddppq Can we really implement `Where` as a condition plus two constant node? I don't understand the document of `If` well, but to me it looks like the `cond` should be a bool tensor that contains only one element, and there is no broadcasting at all for the condition and two graphs.

**Comment by kit1980** [comment]
I don't think `Where` can be implemented with `If`, because you need to select some elements from the second input, and some elements from the third input. Also, to be compatible with TensorFlow, it needs to return indices of non-zero elements if the second and third inputs are null.
I'm working on `Where` PR, should be ready soon.

**Comment by prasanthpul** [comment]
Where was added and >= and <= can be composed. If you want, you can submit PR with functions for >= and <=
