### ISSUE TITLE
pytest: error: unrecognized arguments: --nbval --current-env --cov=onnx --cov-report

### ISSUE THREAD

**Issue by guoyejun** [onnx/onnx#975]
i use  anaconda on ubuntu 16.04, and have done 'pip install pytest-cov nbval' within anaconda env.

after run 'python setup.py install', i run 'pytest', and got the following error:
(pyenv_onnx) yguo18@yguo18-skl-u1604:/work/ml/onnx_work/onnx$ pytest
usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --nbval --current-env --cov=onnx --cov-report
  inifile: /work/ml/onnx_work/onnx/setup.cfg
  rootdir: /work/ml/onnx_work/onnx

**Comment by bddppq** [comment]
you need to pip install nbval

**Comment by shaharv** [comment]
I've faced a similar issue on Ubuntu 19.04, and came here googling, so posting this hoping it may be useful for others.

```
pytest: error: unrecognized arguments: --nbval --current-env
```

For me, this was due to a a python version incompatiblity. `pytest` was python 2, while system python version was 3:

```
$ python -V
Python 3.7.3
$ file /usr/bin/pytest
/usr/bin/pytest: a /usr/bin/python2 script, ASCII text executable

```

To fix this, install `python3-pytest`. Then, run tests with `pytest-3`, instead of `pytest`.

For `--cov`, make sure the `pytest-cov` package is installed: `pip3 install pytest-cov`.

**Comment by ondrejzacha** [comment]
Another possible solution I found after googling around:
Make sure `pytest` and `nbval` are installed in and run from the same environment. 
(check `which pytest` and `pip freeze | egrep "pytest|nbval").

My `pytest` call was using the global installation (as opposed to the one inside my virtualenv), which did not have access to `nbval`.

**Comment by marimeireles** [comment]
Try installing `nbval` with conda `conda -c conda-forge install nbval`. Worked for me, catalina 10.15.6.
